fake discord server
hannibal00212/SkyHanni pull request #1009
Opened 2024-02-15 19:21 UTC by hannibal002

2024-02-19 10:48 UTC, CalMWolfs requested changes
This should also link to https://hypixel.net/threads/all-about-skyblock-account-security.5231557/

2024-02-19 10:48 UTC, CalMWolfs commented on docs/FAKE_DISCORD_SERVER.md
> +### Someone else logged in into my account, but i can still access the account myself
```suggestion
### Someone else logged in into my account, but I can still access the account myself
```

2024-02-19 10:48 UTC, CalMWolfs commented on docs/FAKE_DISCORD_SERVER.md
> +Wait 24 hours and enable multiplayer mode again.
I was told its longer than that to be safe, probably more like a week

2024-02-19 10:48 UTC, CalMWolfs commented on docs/FAKE_DISCORD_SERVER.md
> +> The fake server does not allow you to write in the chat.
I think this is misleading as I do believe you can type in the channels (though some may be locked behind "verification") but the chat history is a good point

2024-04-19 18:12 UTC, Thunderblade73 approved these changes
It does the job to inform about the fake server.

2024-09-07 21:18 UTC, closed without merging