Add sack HUD
hannibal00212/SkyHanni pull request #1029
Opened 2024-02-19 22:46 UTC by nea89o

2024-02-19 23:08 UTC, CalMWolfs requested changes
just a few small things, one other thing, haven't tested yet.

Also maybe I don't understand but what advantage does `ItemStack.getNBTName()` add over existing ItemStack methods?

2024-02-19 23:08 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/data/SackAPI.kt
> +    ) = LorenzUtils.sendCommandToServer("gfs $item $amount")
I think this was adressed in https://github.com/hannibal002/SkyHanni/pull/968 and the cooldown was found to be 1.65 seconds

2024-02-19 23:08 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/data/SackAPI.kt
> +     * Get a list of all known items the sacks.
This line doesnt make sense

2024-02-19 23:08 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/SackHudConfig.java
> +    public List<NEUInternalName> trackedItems = new ArrayList<>();
Instead of saving this here maybe move to SackData and either have it be profile specific or in general

2024-02-19 23:08 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/SackHudConfig.java
> +        desc = "Configure the items display in your Sack HUD"
```suggestion
        desc = "Configure the items display in your Sack HUD."
```

2024-02-20 10:29 UTC, nea89o commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/SackHudConfig.java
> +    public List<NEUInternalName> trackedItems = new ArrayList<>();
Why would it be in sack data? This has nothing to do with the sack data. It is what you want to be displayed in the HUD, not what is stored in your sacks.

2024-02-20 10:29 UTC, nea89o commented on src/main/java/at/hannibal2/skyhanni/data/SackAPI.kt
> +     * Get a list of all known items the sacks.
That's the risk you run when you review a PR that is explicitly marked as "not ready for review".

2024-02-20 10:34 UTC, nea89o commented
> Also maybe I don't understand but what advantage does `ItemStack.getNBTName()` add over existing ItemStack methods?

I'll add a javadoc for other people like you. Maybe if you waited until the PR was marked as "ready to review", you would've saved you and me that work.

2024-07-02 07:30 UTC, hannibal002 commented
old

2024-07-02 07:30 UTC, closed without merging