Feature: Add more messages to chat hider
hannibal00212/SkyHanni pull request #1030
Opened 2024-02-20 02:04 UTC by martimavocado

adds the following messages to the annoying category:
- not enough breaking power for gems
- useless messages for skymall and jacob's event artifact

adds a toggle to hide skymall perk message outside mining islands
adds a toggle to hide jacob's event artifact message outside garden

adds .inMiningIsland to LocationUtils

2024-02-20 08:32 UTC, alexiayaa commented
Nitpick: I'm pretty sure Sky Mall won't work in Gold Mine or Deep Caverns, so should be hidden there too. (You would probably only be there for bestiary, or exp share cores if Ironman, after unlocking the Dwarven Mines).

2024-02-20 21:18 UTC, martimavocado commented
> I'm pretty sure Sky Mall won't work in Gold Mine or Deep Caverns, so should be hidden there too.

Some perks still work outside Dwarven Mines, but the ones that don't, also don't work in crystal hollows from the testing i did a few weeks ago

2024-03-02 21:46 UTC, hannibal002 requested changes

2024-03-02 21:46 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/LocationUtils.kt
> +    fun inMiningIsland() = IslandType.GOLD_MINES.isInIsland() || IslandType.DEEP_CAVERNS.isInIsland()
This belongs in LorenzUtils. LocationUtils is currently only for utils functions around LorenzVec, not for skyblock related functions. We should maybe change this in the future and move all "isinSkyBlock" etc stuff around, but not in this pr.

2024-03-02 21:46 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
> +        "§eNew buff§r§r§r:(.*)"
hypixel moment

2024-03-02 22:47 UTC, hannibal002 approved these changes

2024-03-02 22:47 UTC, merged