Add: Feature for Skill Progress
hannibal00212/SkyHanni pull request #1051
Opened 2024-02-25 03:27 UTC by superhize

Still WIP

- [ ]  Option to change text display depending of % completed
- [ ] Option to change the progress bar color depending on the skill

2024-04-17 23:41 UTC, CalMWolfs requested changes
Havent tested in game yet but a few code style stuff

2024-04-17 23:41 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/features/skillprogress/SkillColorConfig.java
> +    @ConfigOption(name = "Enable Display Color", desc = "Change the text color in the display based on percentage completed")
```suggestion
    @ConfigOption(name = "Enable Display Color", desc = "Change the text color in the display based on percentage completed.")
```

2024-04-17 23:41 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillButtonInInventory.kt
> +    }
Could extract these into a fucntion that makes them and just changes the first line

2024-04-17 23:41 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/utils/ConditionalUtils.kt
> +
?

2024-04-17 23:41 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillTooltip.kt
> +        if (inventoryName == "Your Skills" && stack.getLore().any { it.contains("Click to view!")})  {
i think the formatting here was correct before

2024-06-16 18:01 UTC, hannibal002 requested changes
not tested in game yet

2024-06-16 18:01 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/api/SkillAPI.kt
> +                "icon" -> {
move into a new function. the function is already 120 lines long

2024-06-16 18:01 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillButtonInInventory.kt
> +        if (event.inventory is ContainerLocalMenu && showItem) {
please change this if to early return

2024-06-16 18:01 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillButtonInInventory.kt
> +        if (showItem) {
early return again

2024-06-16 18:01 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillTooltip.kt
> +                if (line.contains("Skill Avg.")) {
add early return (continue)

2024-06-16 18:01 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillUtil.kt
> +    fun getColorForLevel(level: Int): String {
where are those values from? similar to dungeon colors?

2024-07-08 14:44 UTC, superhize commented on src/main/java/at/hannibal2/skyhanni/features/skillprogress/SkillUtil.kt
> +    fun getColorForLevel(level: Int): String {
This use SkyBlock level color divided by 4

We talked about that here https://canary.discord.com/channels/997079228510117908/1163373629204086894/1212246272228982835

2024-10-24 02:43 UTC, superhize commented
I will probably close this and split it into multiple smaller pr

2025-05-13 06:59 UTC, hannibal002 commented
![image](https://github.com/user-attachments/assets/a6e3f0b1-09ab-4c69-a84d-50a523ee5b50)

2025-05-13 06:59 UTC, closed without merging