Geyser fixes
hannibal00212/SkyHanni pull request #1054
Opened 2024-02-25 09:26 UTC by Obsidianninja11

- Added a max distance to geyser box
- Added option to only show geyser box while holding lava rod
- holdingLavaRod and holdingWaterRod in fishingAPI

https://discord.com/channels/997079228510117908/1211104046845530122

2024-02-25 10:09 UTC, hannibal002 requested changes
works fine in game

2024-02-25 10:09 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/fishing/FishingAPI.kt
> +
remove empty line

2024-02-25 10:09 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/GeyserFishing.kt
> +        if (geyser?.distanceToPlayerIgnoreY()!! > 96) return
use `val geyser = geyser ?: return` instead of `!!`

2024-02-25 20:35 UTC, Obsidianninja11 commented on src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/GeyserFishing.kt
> +        if (geyser?.distanceToPlayerIgnoreY()!! > 96) return
so shadow geyser? (I think that's what it's called)

2024-02-26 15:21 UTC, hannibal002 approved these changes

2024-02-26 15:23 UTC, merged