Consistent enhanced backspace
hannibal00212/SkyHanni pull request #1090
Opened 2024-03-02 06:12 UTC by Obsidianninja11

Makes enhanced backspace (delete whole word/line) consistent across sh and other programs.
Also adds keyboard manager functions for detecting when these keys are pressed.

Needs testing on MacOS. I was told these were the right keys that work in discord and other programs, but I wasn't able to test it myself.

2024-03-02 06:14 UTC, Obsidianninja11 commented
Do note that it changes the keys that shwords uses
(Previously shift+backspace for word, ctrl+backspace for line)

2024-03-08 19:29 UTC, Obsidianninja11 commented
It isn't really backend
It changes how "enhanced backspace" works for users too slightly
in shwords it was shift back for one word, ctrl back for line
now it's consistent keybinds (ctrl back and ctrl shift back)
also the functionality was changed very slightly to be like how it is in other apps
before the highlighted space would've been deleted, now it won't be
an` `example

2024-03-11 15:42 UTC, hannibal002 requested changes
If this change is not backend, change the changelog to improvement, please.
Also, i don't think the current description is understandable for average users.

(The feature works as intended for me btw)

2024-03-17 18:47 UTC, merged

2024-03-17 18:47 UTC, hannibal002 commented
Forgot to approve :(