refactor melody quick restart
hannibal00212/SkyHanni pull request #1096
Opened 2024-03-02 21:35 UTC by Zickles

2024-03-02 21:36 UTC, hannibal002 commented
Please give your PRs descriptions/titles that help us understand what you are doing without immediately looking at the code

2024-03-03 00:56 UTC, CalMWolfs requested changes
I feel that the when statements here can be removed and instead you can put and statements inside of the if statements so the code is more readable

e.g. ` if (config.quickRestart && isMenuGui(event.inventoryName) ) {`

2024-03-03 04:14 UTC, Zickles commented
> Please give your PRs descriptions/titles that help us understand what you are doing without immediately looking at the code. (questions like "is this a bug", is this just code cleanup", etc)

Sorry about that swear i added one tbh

2024-03-03 21:37 UTC, hannibal002 approved these changes

2024-03-03 21:37 UTC, merged