Improve visitor getting
hannibal00212/SkyHanni pull request #1121
Opened 2024-03-08 06:42 UTC by CalMWolfs

## Dependencies
- #1120 

## What
Improve the way we get visitors from tablist

## Changelog Fixes
+ Fixed checking more lines than we needed when looking for new visitors. - CalMWolfs
    * This will stop spam when the tablist changes come to main server.

## Changelog Technical Details
+ Use a repo pattern for getting the visitor count. - CalMWolfs

2024-03-08 09:37 UTC, hannibal002 requested changes
![image](https://github.com/hannibal002/SkyHanni/assets/24389977/74589abf-c7e5-43d7-8666-74560c3d01a0)


<details>
<summary>Tab List</summary>

Header:

§r§bYou are playing on §r§e§lMC.HYPIXEL.NET§r
§r§r§r§r§s§r

Body:

'          §r§b§lCoop §r§f(2)'
'§8[§r§5391§r§8] §r§bhannibal2 §r§7☢'
'§baeymii §r§7(Offline 35d+§r§7)'
'          §r§5§lGuests §r§f(0)'
'       §r§3§lServer Info'
'§b§lArea: §r§7Garden'
' Server: §r§8mini93BK'
' Gems: §r§a430'
' Copper: §r§c71,491'
' Garden Level: §r§aXV'
'§b§lComposter:'
' Organic Matter: §r§e536k'
' Fuel: §r§9283k'
' Time Left: §r§a58s'
' Stored Compost: §r§21.6k'
'§b§lVisitors: §r§f(§r§b11m§r§f)'
' §r§cSpaceman'
' §r§dMaeve'
'       §r§6§lAccount Info'
'§e§lProfile: §r§aZucchini'
' Pet Sitter: §r§bN/A'
' Bank: §r§61B/1B'
' Interest: §r§e11 Hours'
'§e§lSkills: §r§aForaging 50: §r§c§lMAX'
' Speed: §r§f✦140'
' Farming Fortune: §r§6☘499'
' Milestone: §r§aWheat 32: §r§369%'
' Wheat Fortune: §r§6☘80'
'§e§lEvent: §r§bElection Over!'
' Starts In: §r§e9h'
'§e§lJacob's Contest:'
' Starts In: §r§e38m'
' §r§e○ §r§fCocoa Beans'
' §r§6☘ §r§fPotato'
' §r§e○ §r§fPumpkin'

Footer:

§r
§r§r§a§lActive Effects§r
§r§r§7§r§7You have §r§e1 §r§7active effect. Use "§r§6/effects§r§7" to see it!§r
§r§r§5Night Vision I§r§r§r
§r§r§r§r§s§r
§r§r§d§lCookie Buff§r
§r§r§f3 years, 5 months§r
§r§r§r§r§s§r
§r§r§aRanks, Boosters & MORE! §r§c§lSTORE.HYPIXEL.NET§r

</details>

2024-03-08 09:39 UTC, CalMWolfs commented
I see, only tested with not full visitors on alpha. And did the full and not unlocked test on main. Looks like this fix will have to wait until it's on live server

2024-03-08 23:36 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/garden/visitor/GardenVisitorTimer.kt
> +        "garden.visitor.timer.time.new",
Sadly this needs to be a new pattern otherwise the user is spammed with number format exceptions 😔

2024-03-13 19:26 UTC, hannibal002 approved these changes
works for me

2024-03-13 19:26 UTC, merged