Added atmospheric display + fixed typo
hannibal00212/SkyHanni pull request #1131
Opened 2024-03-09 23:18 UTC by Obsidianninja11

## Dependencies
- Show outside sb

## What
Adds atmospheric filter display to the show outside list, and fixes typo in the Jacobs contest option in it

## Changelog Improvements
+ Added option to show atmospheric filter display outside SB. - Obsidian

## Changelog Fixes
+ Fixed typo in Show outside list for Jacobs contest . - Obsidian

2024-03-10 01:42 UTC, CalMWolfs requested changes
If someone previously had show jacob contests outside of skyblock on it is now off

2024-03-11 15:46 UTC, hannibal002 requested changes

2024-03-11 15:46 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/enums/OutsideSbFeature.kt
> +    NEXT_JACOB_CONTEST("Next Jacobs's Contest"),
Write a config migration event for this. Currently. Without testing, I can say it will not only not copy over the value. It will even wipe the whole config (the technical error is that the value is named next_jacob_context in the config, and it can't find the corresponding enum in java code). Or even worse: it could set itself to null, and then we have null values in a config element that will cause crashes on config rendering.

2024-03-11 19:43 UTC, Obsidianninja11 commented on src/main/java/at/hannibal2/skyhanni/config/enums/OutsideSbFeature.kt
> +    NEXT_JACOB_CONTEST("Next Jacobs's Contest"),
can't get config migration to work
https://discord.com/channels/997079228510117908/1094190239532208228/1216657069717852231

2024-03-15 06:42 UTC, Obsidianninja11 commented
When I was testing the config migration, it wasn't working for misc.showOutsideSB.NEXT_JACOB_CONTEXT, but it was working for others
I thought i did it right, so maybe other people test?

2024-03-15 06:49 UTC, CalMWolfs commented
> When I was testing the config migration, it wasn't working for misc.showOutsideSB.NEXT_JACOB_CONTEXT, but it was working for others I thought i did it right, so someone else test?

there is no config migration in this pr so i can tell you it wont work

2024-03-15 06:51 UTC, Obsidianninja11 commented
> wont

i commented before pushing on accident

2024-03-15 07:00 UTC, CalMWolfs reviewed
:(


[crash-2024-03-15_17.59.22-client.txt](https://github.com/hannibal002/SkyHanni/files/14612000/crash-2024-03-15_17.59.22-client.txt)

2024-03-17 08:51 UTC, nea89o commented on src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
> +        event.move(28, "misc.showOutsideSB.NEXT_JACOB_CONTEXT", "misc.showOutsideSB.NEXT_JACOB_CONTEST")
```suggestion
        event.move(28, "misc.showOutsideSB", "misc.showOutsideSB") { JsonArray().apply {
            it.map { if(it.asString == "NEXT_JACOB_CONTEXT") JsonString("NEXT_JACOB_CONTEST") else it }.forEach { this.add(it) }
        }}
```

2024-03-17 18:42 UTC, hannibal002 requested changes
Nea's suggestion, also, is https://github.com/hannibal002/SkyHanni/pull/1131#pullrequestreview-1928213126 already done?

2024-04-08 21:47 UTC, Obsidianninja11 commented on src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
> +        event.move(28, "misc.showOutsideSB.NEXT_JACOB_CONTEXT", "misc.showOutsideSB.NEXT_JACOB_CONTEST")
Idk how to get this to work

2024-04-09 13:39 UTC, CalMWolfs approved these changes

2024-04-09 13:51 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
> +        event.move(28, "misc.showOutsideSB.NEXT_JACOB_CONTEXT", "misc.showOutsideSB.NEXT_JACOB_CONTEST")
fixed it for you

2024-04-09 18:31 UTC, hannibal002 approved these changes

2024-04-09 18:31 UTC, merged