Pet rarity on pet drop message
hannibal00212/SkyHanni pull request #1136
Opened 2024-03-10 15:57 UTC by ItsEmpa

## What
Adds the rarity of the dropped pet to its drop message.

## Changelog New Features
+ Added rarity text to pet drop messages. - Empa

2024-03-10 15:57 UTC, jani270 commented
> This pull request has conflicts with the base branch "beta". Please resolve those so we can test out your changes.

lol

2024-03-10 15:58 UTC, ItsEmpa commented
oops

2024-03-10 20:19 UTC, hannibal002 requested changes
Have not tested, just code cleanup.
Please provide us with an example Hypixel message so we can test this feature.

2024-03-10 20:19 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/chat/ChatConfig.java
> +            "§6§lPET DROP! §r§5§lEPIC §r§5Slug §6(§6+1300☘)"
Those reset characters aren't needed (a color also resets previous color + formatting)
```suggestion
            "§6§lPET DROP! §5§lEPIC §5Slug §6(§6+1300☘)"
```

2024-03-10 20:19 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/chat/RareDropMessages.kt
> +    val config get() = SkyHanniMod.feature.chat.petRarityDropMessage
can be private

2024-03-10 20:19 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/chat/RareDropMessages.kt
> +        if (!config) return;
remove semicolon

2024-03-10 20:19 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/chat/RareDropMessages.kt
> +        "(?<message1>§6§lPET DROP!|§5§lGREAT CATCH! §r§bYou found a §r§7\\[Lvl 1]) (?:§r)?§(?<rarityColor>.)(?<petName>[^§(.]+)(?<message2>.*)"
better names for message1 and message2, maybe typeOfDrop and magicFind?

2024-03-10 20:19 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/chat/RareDropMessages.kt
> +        } ?: return
Join declaration and assignment for those variables, and move the creation of the new chat component also inside the matchMatcher block.

2024-03-10 20:19 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/chat/RareDropMessages.kt
> +            "$message1 §r§$rarityColor§l${colorCodeToRarity(rarityColor.first()).uppercase()} §r§$rarityColor$petName$message2"
Remove the two `§r`

2024-03-10 21:39 UTC, ItsEmpa commented
done. some examples of hypixel messages are
```
§5§lGREAT CATCH! §r§bYou found a §r§7[Lvl 1] §r§aGuardian§r§b.
§6§lPET DROP! §r§5Baby Yeti §r§b(+§r§b168% §r§b✯ Magic Find§r§b)
§6§lPET DROP! §r§5Slug §6(§6+1300☘)
```
also made sure `§6§lPET DROP! §r§5Baby Yeti` worked in case hypixel sends a message without any magic find/farming fortune in them

2024-03-11 16:34 UTC, hannibal002 requested changes
Tested with the test strings. slug and baby yeti worked fine, just guardian didnt work

<details>
<summary>Image</summary>

![image](https://github.com/hannibal002/SkyHanni/assets/24389977/27fc5a07-d184-4935-bb2d-938cd32c083d)

</details>


Furthermore, not sure why, but it looks like my test logic got called multiple times. Will fix this independently of this pr.

2024-03-11 16:42 UTC, hannibal002 approved these changes
Never mind. My testing logic was broken. It works all as expected!

<details>
<summary>Image</summary>

![image](https://github.com/hannibal002/SkyHanni/assets/24389977/a95c6c32-4f1c-4029-a2f7-96d7b7f0df35)

</details>

2024-03-11 16:43 UTC, merged