Allow tping when in an infested plot
hannibal00212/SkyHanni pull request #1140
Opened 2024-03-11 06:53 UTC by Obsidianninja11

## What
Adds a toggle to allow tping with the pest teleport hotkey while already in an infested plot.

## Changelog Improvements
+ Allow using teleport hotkey when in an infested plot. - Obsidian

2024-03-11 16:18 UTC, hannibal002 requested changes
I like the option, but the name and description is a bit confusing imo. maybe toggle the logic, and make it default enabled. (block while in invested block)

2024-03-15 06:39 UTC, Obsidianninja11 commented
> I like the option, but the name and description is a bit confusing imo. maybe toggle the logic, and make it default enabled. (block while in invested block)

Idk what i'd name it with this

2024-03-16 05:27 UTC, CalMWolfs approved these changes
code looks good

2024-03-23 23:57 UTC, hannibal002 approved these changes

2024-03-23 23:57 UTC, merged