Backend: Widget abstractions
hannibal00212/SkyHanni pull request #1150
Opened 2024-03-12 18:36 UTC by Thunderblade73

## What
Wraps all widgets under an enum (I have a solution to update it remotely for this enum, just not yet implemented).
It also adds an widget update event that should reduce the usage of TabListUpdateEvent.

## Changelog Technical Details
+ Added Tab Widget abstraction. - Thunderblade73

2024-03-12 19:40 UTC, Thunderblade73 commented
open to review but garden patterns are still missing. Since Garden is closed at the moment.

2024-03-12 19:46 UTC, Thunderblade73 commented
@nea89o Would you mind taking a look at this PR and providing your feedback?

2024-03-12 20:24 UTC, nea89o requested changes

2024-03-12 20:24 UTC, nea89o commented on src/main/java/at/hannibal2/skyhanni/utils/repopatterns/RepoPatternManager.kt
> +    fun getUnusedPatterns(prefix: String): List<Pattern> {
Can you add a javadoc here indicating that this is a dangerous method (since it circumvents the exclusivity map)?

2024-03-12 20:24 UTC, nea89o commented on src/main/java/at/hannibal2/skyhanni/utils/repopatterns/RepoPatternManager.kt
> +        if (config.forceLocal.get()) return emptyList()
Maybe verify the prefix here to be of the normal pattern plus a `.`

2024-03-22 18:40 UTC, hannibal002 commented
Is somethign already using this?

2024-03-22 18:40 UTC, Thunderblade73 commented
Nope, only listed in copytablist

2024-03-22 21:08 UTC, Thunderblade73 commented
> Is something already using this?
See #1240 for that

2024-04-19 17:55 UTC, Thunderblade73 commented
Can a maintainer move this to 0.26.
I won't be able to fix the issue with the Pr before 0.25 release.

2024-06-02 08:24 UTC, CalMWolfs approved these changes
worked for me

2024-06-02 09:02 UTC, hannibal002 requested changes
Two problems:

<details>
<summary>Event too complex</summary>

The current system needs this workaround:

<details>
<summary>Image</summary>

![image](https://github.com/hannibal002/SkyHanni/assets/24389977/99065c44-9e89-48ac-8d5f-3e031140c071)

</details>

(See https://github.com/hannibal002/SkyHanni/pull/1977 for more info)

I'd suggest, we remove `NewValues` and `Clear` and instead fire `Event(EnumType, List)`, with either changed values or an empty list if not found.

</details>

<details>
<summary>No event when no widget</summary>

Another problem is that the event is not getting sent when the widget is disabled when word switch. I don't want to assume the widgets are always disabled if the event is not sent (and then show an "open /tab and enable widget" display for the first second after world switch).

</details>

2024-06-02 14:01 UTC, CalMWolfs approved these changes
changes lgtm

2024-06-03 17:38 UTC, hannibal002 approved these changes

2024-06-03 17:38 UTC, merged