Feature: Plot Menu Highlighting
hannibal00212/SkyHanni pull request #1181
Opened 2024-03-15 19:27 UTC by ILike2WatchMemes

## What
Added Plot Menu Highlighting Feature, highlights plots in the desk menu "Configure Plots" based on 4 different statuses:
- has pests
- has active spray
- is plot player is currently in
- is locked

## Changelog New Features
+ Plot Menu Highlighting - ILike2WatchMemes
    * Added plot highlighting based on plot status.

2024-03-21 20:35 UTC, hannibal002 requested changes
Not tested in game, just code cleanup ideas

2024-03-21 20:35 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/garden/GardenConfig.java
> +    public PlotMenuHighlightingConfig plotMenuHighlighting = new PlotMenuHighlightingConfig();
not sure if this is out of scope for this pr (so please tell me if you prefer that we do this change in another pr later):

Move this plotMenuHighlighting, plotIcon and plotPrice all in one category "plot inventory"

2024-03-21 20:35 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/garden/GardenConfig.java
> +    public PlotMenuHighlightingConfig plotMenuHighlighting = new PlotMenuHighlightingConfig();
Also move all in one new package
![image](https://github.com/hannibal002/SkyHanni/assets/24389977/641a0d20-fa0f-4fe1-b207-47acacf688b8)

2024-03-21 20:35 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/inventory/PlotMenuHighlighting.kt
> +    private var highlightedPlots: MutableList<Pair<GardenPlotAPI.Plot, String>> = mutableListOf()
shorter variation
```suggestion
    private var highlightedPlots = mutableListOf<Pair<GardenPlotAPI.Plot, String>>()
```

2024-03-21 20:35 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/inventory/PlotMenuHighlighting.kt
> +    private fun handleCurrent(slot: Slot, plot: GardenPlotAPI.Plot, status: PlotStatusTypes) {
This is duplicate code, please extract into another function
![image](https://github.com/hannibal002/SkyHanni/assets/24389977/af632470-dd82-4277-b29c-da1fc5d6e33a)

2024-03-21 20:35 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/inventory/PlotMenuHighlighting.kt
> +        val list: MutableList<String> = mutableListOf()
```suggestion
        val list = mutableListOf<String>()
```

2024-03-21 20:35 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/inventory/PlotMenuHighlighting.kt
> +        var lowest = if (array.size != 0) 999 else return 999
instead of 999, work with null

2024-03-21 20:35 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/inventory/PlotMenuHighlighting.kt
> +            list.clear()
instead of clearing the list every iteration, create a new list each time

2024-03-21 20:35 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/inventory/PlotMenuHighlighting.kt
> +    fun onBackgroundDrawn(event: GuiContainerEvent.BackgroundDrawnEvent) {
do not check all items and their tooltips in the render tick. Rather, use InventoryOpenEvent to cache the data you need, then only render in the background draw event.

2024-03-21 22:38 UTC, ILike2WatchMemes commented on src/main/java/at/hannibal2/skyhanni/config/features/garden/GardenConfig.java
> +    public PlotMenuHighlightingConfig plotMenuHighlighting = new PlotMenuHighlightingConfig();
maybe inventory.plots?

2024-03-21 23:44 UTC, ILike2WatchMemes commented
> not sure if this is out of scope for this pr (so please tell me if you prefer that we do this change in another pr later):
> 
> Move this plotMenuHighlighting, plotIcon and plotPrice all in one category "plot inventory"

(resolved convo for pull)

2024-03-22 18:16 UTC, hannibal002 requested changes
just a personal preference: move the events first, then the utils functions.

2024-03-22 18:16 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/inventory/plots/GardenPlotMenuHighlighting.kt
> +        return if(lowest == 999) null else lowest
auto reformatting (missing empty space between `if` and open bracket)

2024-03-22 18:16 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/inventory/plots/GardenPlotMenuHighlighting.kt
> +        return if(lowest == 999) null else lowest
Kotlin already has ways to deal with this.
```suggestion
        return array.mapNotNull { status -> config.deskPlotStatusTypes.find { it == status } }
            .minOfOrNull { config.deskPlotStatusTypes.indexOf(it) }
```

2024-03-22 18:16 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/inventory/plots/GardenPlotMenuHighlighting.kt
> +            val plot = plots.find { it.inventorySlot == slot.slotIndex } ?: continue
use `GardenPlotAPI.plots` here please.

2024-03-22 18:16 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/garden/PlotMenuHighlightingConfig.java
> +    public enum PlotStatusTypes {
please use singular name for enums

2024-03-22 18:16 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/inventory/plots/GardenPlotMenuHighlighting.kt
> +    private fun isHighlighted(plot: GardenPlotAPI.Plot) = highlightedPlots.any { it.first == plot }
make highlightedPlots a map, so that we can use highlightedPlots[plot] here instead of any {it == plot}

2024-03-22 18:16 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/inventory/plots/GardenPlotMenuHighlighting.kt
> +        for (slot in InventoryUtils.getItemsInOpenChest()) {
You dont check if the feature is enabled here

2024-03-22 20:20 UTC, hannibal002 requested changes
Does work with plots, does not show the plot I'm standing on for me

2024-03-22 20:20 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/inventory/plots/GardenPlotMenuHighlighting.kt
> +        val isCurrent = isCurrentHighlight(plot, status)
inline those two functions.

2024-03-22 20:24 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/garden/PlotMenuHighlightingConfig.java
> +    public List<PlotStatusType> deskPlotStatusTypes = new ArrayList<>();
Maybe fill this list with the four values in preferred default order. (we still have the enabled toggle so its not default enabled)

2024-03-23 17:58 UTC, hannibal002 approved these changes
maybe add support for "currently pasting" in the future

2024-03-23 17:59 UTC, merged