Open contest browser
hannibal00212/SkyHanni pull request #1185
Opened 2024-03-16 00:48 UTC by Obsidianninja11

## What
Adds a keybind to open a contest on elitebot.dev when clicking with the key held.
Also supports opening other contest pages on elitebot.dev such as upcoming, main page, and your contests.

I realized after making this that this is a dupe of #915. I think my logic is a bit simpler though.

## Changelog New Features
+ Allow opening contests on elitebot.dev. - Obsidian

2024-03-16 09:43 UTC, hannibal002 requested changes
Works for me.

Can we change it to open on key click alone, not key press + mouse click?
Also maybe show the information "press <keybind> to open this event in elite farming" in the item tooltip.

2024-03-16 09:43 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/JacobFarmingContestConfig.java
> +    public int openOnline = Keyboard.KEY_NONE;
rename the toggle to "open elitebot" instead

2024-03-16 09:43 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/GardenNextJacobContest.kt
> +import at.hannibal2.skyhanni.events.*
do not use wildcard imports. we have a global setting file to disable this behaviour in intellij.

2024-03-16 09:43 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/contest/FarmingContestAPI.kt
> +import at.hannibal2.skyhanni.events.*
same problem here

2024-03-16 09:43 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/contest/JacobFarmingContestsInventory.kt
> +import at.hannibal2.skyhanni.events.*
and here

2024-03-16 09:43 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/contest/JacobFarmingContestsInventory.kt
> +        val invName = InventoryUtils.openInventoryName()
dont use abbreviations (inventoryName)

2024-03-16 09:43 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/contest/JacobFarmingContestsInventory.kt
> +        val name = event.slot.stack.name
rename to itemName to readability

2024-03-16 09:43 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/contest/JacobFarmingContestsInventory.kt
> +                    ChatUtils.chat("Opening contest in elitebot.dev")
Those three lines are duplicated a bit below. Create a function `openContestWebsite(year, month, day)` instead and use it twice

2024-03-16 09:43 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/contest/JacobFarmingContestsInventory.kt
> +    fun onSlotClick(event: SlotClickEvent) {
This function is very long. Try to extract it into multiple smaller functions.

2024-03-16 09:43 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/JacobFarmingContestConfig.java
> +    @ConfigOption(name = "Open Online", desc = "Opens the contest on §eelitebot.dev§7 when clicking with this key held.")
Add the info that this works both in jacobs menu and calendar.

2024-03-16 21:44 UTC, Obsidianninja11 commented
> Can we change it to open on key click alone, not key press + mouse click?

Maybe add a toggle?
I like using ctrl+click for this

2024-03-17 01:44 UTC, Obsidianninja11 commented
> Can we change it to open on key click alone, not key press + mouse click?

I didn't do this yet

2024-04-01 18:49 UTC, hannibal002 approved these changes

2024-04-01 18:56 UTC, merged