Feature: Quiver Display
hannibal00212/SkyHanni pull request #1190
Opened 2024-03-16 13:50 UTC by ItsEmpa

## What
Adds a Quiver Display that shows the amount of arrows you have. Also makes QuiverAPI use the item in the 9th slot of the hotbar to get more accurate numbers.

TODO:

- [ ] Only update Quiver Display when bow in hand or held one recently
- [ ] Option to only show Quiver Display with bow in inventory

<details>
<summary>Images</summary>

![image](https://github.com/hannibal002/SkyHanni/assets/42304516/b93fb414-cbf3-4c72-be72-177cc82cfd42)

</details>

## Changelog New Features
+ Added Quiver Display. - Empa

## Changelog Improvements
+ Use quiver Item in 9th hotbar slot for QuiverAPI - Empa

## Changelog Fixes
+ Fixed not changing current arrow with different colors. - Empa

## Changelog Technical Details
+ Added slot to OwnInventoryItemUpdateEvent - Empa

2024-03-18 13:37 UTC, ItsEmpa commented
Finished what i wanted to do with this (mostly), only thing left in my todo is merging the dungeon and kuudra enter/complete events into an instance event, but apart from that it should be ready for review.

2024-03-18 13:40 UTC, ItsEmpa commented
The description and names of the new configs also still have to be improved

2024-04-07 18:46 UTC, hannibal002 requested changes
works fine in game.
maybe split "display" and "warning" up into different categories?

2024-04-07 18:46 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/gui/GUIConfig.java
> +    public QuiverDisplayConfig quiverDisplay = new QuiverDisplayConfig();
id argue this belongs into combat category

2024-04-07 18:46 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/gui/QuiverDisplayConfig.java
> +    public boolean enabled = true;
either make this default disabled or show "while bow in hand" per default.

2024-04-07 18:46 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/gui/QuiverDisplayConfig.java
> +    public boolean reminderAfterRun = false;
id argue to have this default enabled. 
also a bit uncrear: is this part of the display, or can you hide the display always and just have this warning?

2024-04-07 18:46 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/gui/QuiverDisplay.kt
> +        event.move(31,"config.inventory.quiverAlert","config.gui.quiverDisplay.lowQuiverNotification")
remove the `config.` part

2024-04-07 18:46 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/gui/QuiverDisplay.kt
> +            add(Renderable.string(" §b${amount}x"))
please add `addSeparators()`

2024-04-10 10:09 UTC, hannibal002 requested changes
looks like it works fine in game

2024-04-10 10:09 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/gui/quiver/QuiverDisplay.kt
> +            add(Renderable.itemStack(itemStack, 1.68))
A bit too large:
![image](https://github.com/hannibal002/SkyHanni/assets/24389977/1eaf52b6-c908-4fd9-ab61-eb0bb57beae3)

2024-04-10 10:09 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
> +        public Map<NEUInternalName, Integer> arrowAmount = new HashMap<>();
this feels it could cause config resets?

2024-04-10 10:12 UTC, ItsEmpa commented on src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
> +        public Map<NEUInternalName, Integer> arrowAmount = new HashMap<>();
i asked you this some weeks ago and you told me it was fine and didnt need config migration iirc

2024-04-10 10:13 UTC, ItsEmpa commented on src/main/java/at/hannibal2/skyhanni/features/gui/quiver/QuiverDisplay.kt
> +            add(Renderable.itemStack(itemStack, 1.68))
need to update it since the itemstack rendering changes

2024-04-13 06:35 UTC, hannibal002 approved these changes

2024-04-13 06:35 UTC, merged