Backend: KuudraAPI
hannibal00212/SkyHanni pull request #1209
Opened 2024-03-18 12:05 UTC by ItsEmpa

## What
Adds a KuudraAPI, and the events KuudraEnterEvent and KuudraCompleteEvent

Needed for #1190 

## Changelog Technical Details
+ Added KuudraAPI. - Empa
+ Added KuudraEnterEvent and KuudraCompleteEvent. - Empa

2024-03-24 11:39 UTC, CalMWolfs requested changes
just these two smaller changes i think

2024-03-24 11:39 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/nether/KuudraAPI.kt
> +    )
```suggestion
    private val patternGroup = RepoPattern.group("data.kuudra")

    private val tierPattern by patternGroup.pattern(
        "scoreboard.tier",
        " §7⏣ §cKuudra's Hollow §8\\(T(?<tier>.*)\\)"
    )
    private val completePattern by patternGroup.pattern(
        "chat.complete",
        "§.\\s*(?:§.)*KUUDRA DOWN!"
    )
```
Seeing as there is only two patterns may as well do something like this. Also this is made on web so no clue if it compiles though it should

2024-03-24 11:39 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/nether/KuudraAPI.kt
> +
```suggestion
}

```
remove extra lines

2024-03-24 11:45 UTC, ItsEmpa commented
done

2024-03-24 11:52 UTC, CalMWolfs approved these changes

2024-04-03 19:25 UTC, hannibal002 approved these changes

2024-04-03 19:25 UTC, merged