Feature: Bonus Pest Chance Display
hannibal00212/SkyHanni pull request #1216
Opened 2024-03-19 03:58 UTC by Zickles

## What
Adds a display that displays your bonus pest chance and shows if it is enabled or not.

![image](https://github.com/hannibal002/SkyHanni/assets/76439587/7f0e71a5-7aa2-4424-b450-14e124277e9c)

## Changelog New Features
+ Bonus Pest Chance Display. - Zickles
    * Displays your bonus pest chance and if you have it enabled or not.

2024-03-23 12:46 UTC, ItsEmpa commented
i feel like it could look better with the same formatting as the stats breakdown, but making it be red instead of gray when disabled

![image](https://github.com/hannibal002/SkyHanni/assets/42304516/a777b843-2b54-4a1b-9be5-9c5597eb6b20)
![image](https://github.com/hannibal002/SkyHanni/assets/42304516/f987a5cc-4d3a-43f5-855b-a0bd9264a8f8)

2024-03-24 15:53 UTC, Zickles commented
alright

2024-04-23 09:47 UTC, hannibal002 requested changes
Works already fine for me. I've just added a bunch of small suggestions.

2024-04-23 09:47 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/garden/pests/BonusPestChanceConfig.java
> +    public Position pos = new Position(5, -115, false, true);
rename to positino for consistency

2024-04-23 09:47 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/garden/GardenConfig.java
> +    public BonusPestChanceConfig bonusPestChanceDisplay = new BonusPestChanceConfig();
rename to bonusPestChance for consistency

2024-04-23 09:47 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/BonusPestChanceDisplay.kt
> +    private var display = emptyList<List<Any>>()
since we only work with strings, we can change this to `emptyList<String>`

2024-04-23 09:47 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/BonusPestChanceDisplay.kt
> +        if (GardenAPI.toolInHand == null) return
use GardenAPI.hasFarmingToolInHand()

2024-04-23 09:47 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/BonusPestChanceDisplay.kt
> +        event.tabList.firstNotNullOfOrNull {
firstNotNullOfOrNull will stop when the second regex will match, also we are not working with the result. so using `for (it : event.tabList) {` and `break` feels more intuitive.

2024-04-23 09:47 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/BonusPestChanceDisplay.kt
> +    private var tabPestBonusStatus: Boolean = false
Reset those values on world swich or profile switch

2024-04-23 09:47 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/BonusPestChanceDisplay.kt
> +            updatedDisplay.addAsSingletonList("§fEnabled: §cFalse")
What is enabled here? Be a bit more descriptive please

2024-04-23 09:47 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/BonusPestChanceDisplay.kt
> +        updatedDisplay.addAsSingletonList("§fBonus Pest Chance§7: §2ൠ$tabPestBonus")
please use §7 instead of §7 for consistency

2024-12-20 02:50 UTC, CalMWolfs commented
Your pull request has been inactive for an extended period and appears to be either a draft or awaiting resolution of merge conflicts or requested changes. Therefore, I am closing it for now. Feel free to reopen it when it’s ready for review.

2024-12-20 02:50 UTC, closed without merging