Feature: Soulbound Item Symbol and Text Remover
hannibal00212/SkyHanni pull request #1233
Opened 2024-03-21 21:32 UTC by Zickles

## What
Adds the option to put a symbol next to soulbound items, color is based off if its coop soulbound or fully soulbound.
Adds the option to remove the "* Co-op Soulbound *" or "* Soulbound *" text from the  bottom of your items

![image](https://github.com/hannibal002/SkyHanni/assets/76439587/d1ca69b6-8378-4491-8c15-3f7a4f8577bd)

## Changelog New Features
+ Soulbound Item Symbol and Text Remover. - Zickles
    * Adds symbol next to soulbound items and or removes the soulbound text from the bottom of the item.

2024-03-21 21:34 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/SoulboundItemIcon.kt
> +            if (line == "§8§l* §8Co-op Soulbound §8§l*") {
make these a repopattern

2024-03-21 21:34 UTC, Thunderblade73 requested changes

2024-03-21 21:34 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/SoulboundItemIcon.kt
> +            if (line.contains("§8§l* §8Soulbound §8§l*") || line.contains("§8§l* §8Co-op Soulbound §8§l*")) {
pattern

2024-03-21 21:34 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/SoulboundItemIcon.kt
> +        }
cache this checking. Since this is run for every item every frame.

2024-03-22 16:52 UTC, hannibal002 requested changes

2024-03-22 16:52 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/SoulBoundItemConfig.java
> +    public boolean icon = false;
better name. how about "showSymbol"?

2024-03-22 16:52 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/SoulBoundItemConfig.java
> +    public boolean text = false;
better name. how about "removeTooltip"?

2024-03-26 20:01 UTC, CalMWolfs requested changes

2024-03-26 20:01 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/inventory/SoulboundItemIcon.kt
> +            if (line.contains("§8§l* §8Soulbound §8§l*") || line.contains("§8§l* §8Co-op Soulbound §8§l*")) {
Pattern

2024-03-26 20:01 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/inventory/SoulboundItemIcon.kt
> +                break
Why break instead of just returning

2024-03-26 20:01 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/inventory/SoulboundItemIcon.kt
> +    )
These should be part of a pattern group. Maybe "inventory.item.soulbound"

Then first pattern is "coop" and second is "player"

Also missing an empty line after the patterns

2024-12-20 02:45 UTC, CalMWolfs commented
Your pull request has been inactive for an extended period and appears to be either a draft or awaiting resolution of merge conflicts or requested changes. Therefore, I am closing it for now. Feel free to reopen it when it’s ready for review.

2024-12-20 02:45 UTC, closed without merging