Improvement: Cookie Buff Timer
hannibal00212/SkyHanni pull request #1292
Opened 2024-03-27 14:29 UTC by ItsEmpa

## What
Stores and uses the time until cookie buff runs out instead of depending on tablist. Also changes the formatting of it to show in only 1 line.

## Changelog Improvements
+ Made Cookie Buff timer in Custom Scoreboard work without tablist. - Empa

2024-03-27 15:39 UTC, j10a1n15 requested changes
Not tested when eating another cookie, rest works fine ingame
You could also add that image of the new design you send me

2024-03-27 15:39 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/data/BitsAPI.kt
> +        get() = profileStorage?.boosterCookieExpiryTime ?: 0
```suggestion
        get() = profileStorage?.boosterCookieExpiryTime.asTimeMark() ?: SimpleTimeMark.farPast()
```

2024-03-27 15:39 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/data/BitsAPI.kt
> +            profileStorage?.boosterCookieExpiryTime = value
```suggestion
            profileStorage?.boosterCookieExpiryTime = value.toMillis()
````

2024-03-27 15:39 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/data/BitsAPI.kt
> +    var cookieBuffTime: Long
```suggestion
    var cookieBuffTime: SimpleTimeMark
```

2024-03-27 15:39 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/data/BitsAPI.kt
> +                cookieBuffTime = 0L
```suggestion
                cookieBuffTime = SimpleTimeMark.farPast()
```

2024-03-27 15:39 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/data/BitsAPI.kt
> +                if (noCookieActiveSBMenuPattern.matches(line)) cookieBuffTime = 0L
```suggestion
                if (noCookieActiveSBMenuPattern.matches(line)) cookieBuffTime = SimpleTimeMark.farPast()
```

2024-03-27 15:39 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/data/BitsAPI.kt
> +                    if (noCookieActiveCookieMenuPattern.matches(nextLine)) cookieBuffTime = 0L
```suggestion
                    if (noCookieActiveCookieMenuPattern.matches(nextLine)) cookieBuffTime = SimpleTimeMark.farPast()
```

2024-03-27 15:39 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/data/BitsAPI.kt
> +                    cookieBuffTime = SimpleTimeMark.now().plus(duration).toMillis()
```suggestion
                    cookieBuffTime = SimpleTimeMark.now().plus(duration)
```

2024-03-27 15:39 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/data/BitsAPI.kt
> +                    cookieBuffTime = SimpleTimeMark.now().plus(duration).toMillis()
```suggestion
                    cookieBuffTime = SimpleTimeMark.now().plus(duration)
```

2024-03-27 16:25 UTC, j10a1n15 approved these changes
tested ingame (ate a cookie), worked fine

2024-03-27 21:42 UTC, hannibal002 requested changes
After first time updating to this, you need to open the SkyBlock menu once for the data to get loaded.
Please either show the red info "open sb menu" in the tab list or keep using the not precise tab list information until precise SkyBlock menu information is loaded.

2024-04-03 18:16 UTC, j10a1n15 approved these changes

2024-04-03 18:16 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
> +    BitsAPI.cookieBuffTime?.let {
```suggestion
    return BitsAPI.cookieBuffTime?.let {
        informationFilteringConfig.hideEmptyLines && BitsAPI.hasCookieBuff()
    } ?: true
```

2024-04-03 18:17 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
> +    BitsAPI.cookieBuffTime?.let {
Whoops missclicked approved and request changes, that suggestion didnt seem to apply for all three lines too

2024-04-05 17:22 UTC, hannibal002 approved these changes

2024-04-05 17:23 UTC, merged