Fix: Black Hotbar Slots
hannibal00212/SkyHanni pull request #1293
Opened 2024-03-27 16:40 UTC by Thunderblade73

## What
Fixed the issue with the black hotbar slots for good, be "reseting" the state as a last thing for the GuiOverlayRenderEvent event. It could make issue if the inistial state where diffrent, but can't fix that because it's hard to get the state out of the GlStateManger since everything is private and there are no geters only setters.

## Changelog Fixes
+ Fixed Hotbar loosing it's trancperancy. - Thunderblade73
    * This was the case if the skill progress none textered bar was rendered.

2024-03-27 21:19 UTC, CalMWolfs reviewed
Why do we do this here instead of just doing it where the event is called. That seems like it would make more sense to me

2024-03-27 21:33 UTC, Thunderblade73 commented
Because there are multiple places (2) where the event is called. Easier to do it inside the event as last thing.

2024-03-27 21:58 UTC, CalMWolfs requested changes
Maybe instead of calling one event function the proper name and the other "e" you can call it the eventNamePre and eventNamePost

2024-03-27 22:02 UTC, Thunderblade73 commented
Wait, e is not intended to be here. 😅.
it was just my Debug entry point to figure the default state of GLStatManager out.

2024-03-28 23:16 UTC, CalMWolfs approved these changes

2024-03-29 14:06 UTC, merged