Technical Improvement: Mayor Overwrite
hannibal00212/SkyHanni pull request #1302
Opened 2024-03-28 10:27 UTC by j10a1n15

## What
This Pull Request adds the option to overwrite the currently active mayor using a dropdown.

<details>
<summary>Images</summary>

Uploading 2024-03-28 11-23-31.mp4…

</details>

## Changelog Technical Details
+ Added config option to overwrite current mayor. - j10a1n15
    * This replaces all "Always <mayor>" options.

2024-03-28 12:09 UTC, alexiayaa requested changes

2024-03-28 12:09 UTC, alexiayaa commented on src/main/java/at/hannibal2/skyhanni/features/garden/farming/GardenCropSpeed.kt
>      }
GitHub won't let me make this a proper suggestion, but just make this:
```kotlin
fun finneganPerkActive() = Perk.FARMING_SIMULATOR.isActive
```

2024-04-03 09:42 UTC, CalMWolfs requested changes

2024-04-03 09:42 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/event/diana/GriffinBurrowHelper.kt
> -                ChatUtils.clickableChat("§cEnable Always Diana in the config!", "sh always diana")
maybe here instead of removing this you direct them to the new debug thing

2024-04-03 21:26 UTC, CalMWolfs requested changes

2024-04-03 21:26 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/event/diana/GriffinBurrowHelper.kt
> +                ChatUtils.userError("§cSelect Diana as mayor overwrite!")
Should probably stay a clickable chat but send you to sh assume mayor

2024-04-04 22:39 UTC, CalMWolfs approved these changes

2024-04-05 22:35 UTC, hannibal002 requested changes

2024-04-05 22:35 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/data/MayorAPI.kt
> +        get() {
please dont modify perks and activePerks on each current mayor access. instead use mayor api and config change event/real mayor update actions to determine the states

2024-04-07 08:08 UTC, hannibal002 approved these changes
works fine

2024-04-07 08:30 UTC, merged