Fix: Party Finder patterns
hannibal00212/SkyHanni pull request #1303
Opened 2024-03-28 18:29 UTC by martimavocado

## What
Fixes some patterns for the party finder, namely the note, price, carry and perm/vc

## Changelog Fixes
+ Fixed note detection in the Party Finder. - martimavocado

2024-03-28 20:37 UTC, hannibal002 requested changes

2024-03-28 20:37 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonFinderFeatures.kt
> +            "123".toPattern()
456

2024-03-28 23:18 UTC, CalMWolfs approved these changes

2024-03-29 14:07 UTC, hannibal002 approved these changes

2024-03-29 14:07 UTC, merged