Improvement: Added Mining Event Icons
hannibal00212/SkyHanni pull request #1305
Opened 2024-03-28 19:51 UTC by Thunderblade73

## What
Adds icons to the mining events display and multiple objects on how to display them.

## Changelog Improvements
+ Added Mining Event Icons. - Thunderblade73

## Changelog Technical Details
+ Added darken shader. -  VixidDev

2024-05-07 13:56 UTC, CalMWolfs requested changes

2024-05-07 13:56 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningEventConfig.java
> +    public boolean islandAsIcon = false;
This crashes me on launch, maybe just name the new variable compressFormat

2024-05-07 14:39 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningEventConfig.java
> +    public boolean islandAsIcon = false;
it's because the move doesn't happen, since config version is 45 now and not 31 anymore.

2024-05-28 12:55 UTC, CalMWolfs approved these changes
worked

2024-05-29 21:00 UTC, merged