Feature: Stereo Harmony Display
hannibal00212/SkyHanni pull request #1324
Opened 2024-03-31 09:05 UTC by ItsEmpa

## Dependencies
- #1318 

## What
Adds a Stereo Harmony Display, showing what vinyl the InfiniVacuum is currently playing and what pest spawns are boosted by it.

<details>
<summary>Images</summary>

![image](https://github.com/hannibal002/SkyHanni/assets/42304516/069d556b-e35f-4dc3-9c99-d849e84e50cd)
![image](https://github.com/hannibal002/SkyHanni/assets/42304516/f88f63c1-9405-47de-9440-b90e764e45d4)

</details>

## Changelog New Features
+ Added Stereo Harmony Display. - Empa
    * Options to show/hide boosted crop and pest icons.

2024-04-07 18:30 UTC, hannibal002 requested changes
Code looks clean and the feature works fine!

A bit annoying to have this default enabled AND always visible. 
please add the `GardenAPI.isCurrentlyFarming()` check and create a toggle "show always". Then either default disable the whole feature and have always in garden enabled, or default enable the feature but have this "always enabled" disabled.

Please add text here. Even if not necessary, just for consistency.
![image](https://github.com/hannibal002/SkyHanni/assets/24389977/b87f4d2d-673d-4064-92a1-ac96f655c3a1)

2024-04-07 18:31 UTC, ItsEmpa commented
oops i had the config descriptions done but i must have forgotten to commit it, will do

2024-04-08 12:04 UTC, CalMWolfs requested changes

2024-04-08 12:04 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestType.kt
> +enum class PestType(val displayName: String, val damageIndicatorBoss: BossType, val spray: SprayType, val vinyl: VinylType, val internalName: NEUInternalName, val cropIcon: ItemStack) {
instead of storing the item here can you maybe store the CropType that is associated with each pest and get the item through that

2024-04-10 00:20 UTC, CalMWolfs approved these changes
code looks fine, didnt test in game

2024-04-10 07:51 UTC, hannibal002 requested changes

2024-04-10 07:51 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/garden/pests/StereoHarmonyConfig.java
> +    public boolean alwaysShow = false;
Please indicate that this display normally only shows while farming.
Maybe something like this:
![image](https://github.com/hannibal002/SkyHanni/assets/24389977/7e602cb3-953e-4a44-ad4c-41b340939384)

2024-04-10 10:12 UTC, hannibal002 approved these changes

2024-04-10 10:13 UTC, merged