Improvement: Overflow Garden Levels
hannibal00212/SkyHanni pull request #1325
Opened 2024-03-31 14:53 UTC by ItsEmpa

## What
Adds support for showing overflow garden levels on the skyblock menu and desk tooltips, and toggles for enabling/disabling that and overflow garden level up messages.

## Changelog Improvements
+ Added support for showing overflow garden levels outside the Garden Level Display. - Empa
+ Added options to toggle overflow garden levels and overflow level up messages. - Empa

2024-03-31 15:12 UTC, ItsEmpa commented
Note: need someone with garden level 15+ to test this

2024-03-31 21:45 UTC, superhize requested changes

2024-03-31 21:45 UTC, superhize commented on src/main/java/at/hannibal2/skyhanni/features/garden/GardenLevelDisplay.kt
> +        "§7§8Max level reached!"
```suggestion
        "§5§o§7§8Max level reached!"
```

2024-04-23 14:58 UTC, hannibal002 approved these changes

2024-04-23 14:58 UTC, merged