Fix: Supercraft /gfs not working for 1,000+ items
hannibal00212/SkyHanni pull request #1351
Opened 2024-04-03 21:46 UTC by alexiayaa

## What
Fixed the Supercraft /gfs prompt not showing when you crafted 1,000 or more items.

## Changelog Fixes
+ Fixed the Supercraft /gfs prompt not showing when you crafted 1,000 or more items. - Alexia Luna

2024-04-03 21:48 UTC, CalMWolfs requested changes
You have to make a new patter as this will cause an NPE for users on old versions that super craft more than 1000 items

2024-04-03 21:49 UTC, alexiayaa commented
Right, I forgot about that.

2024-04-03 21:51 UTC, alexiayaa commented
Any suggestions on the new pattern name? We need some sort of convention for this. There's also another pull request I was going to make that has the same issue.

2024-04-03 22:06 UTC, CalMWolfs approved these changes

2024-04-04 18:05 UTC, hannibal002 approved these changes

2024-04-04 18:05 UTC, merged