Backend: Switch from LorenzUtils.inDungeons to IslandType.CATACOMBS.isInIsland()
hannibal00212/SkyHanni pull request #1378
Opened 2024-04-07 10:25 UTC by j10a1n15

## What
Since IslandType.CATACOMBS.isInIsland has been working for quite a while, its finally time to actually start using it. This Pull Request replaces all instances

## Changelog Technical Details
+ Switch from LorenzUtils.inDungeons to IslandType.CATACOMBS.isInIsland(). - j10a1n15

2024-04-07 10:37 UTC, CalMWolfs requested changes
Also I feel to keep consistancy with RiftApi and GardenApi we should use `DungeonsApi.inDungeons()` instead of `IslandType.CATACOMBS.isInIsland` but dungeon api just use the `IslandType.CATACOMBS.isInIsland` instead of checking the dungeon floor. 

If you/others dont want to do this then just the one change

2024-04-07 10:37 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonTeammateOutlines.kt
> +    private fun isEnabled() = LorenzUtils.inSkyBlock && IslandType.CATACOMBS.isInIsland() && config.highlightTeammates
can remove the inSkyblock check here as isInIsland already checks that

2024-04-07 12:06 UTC, CalMWolfs approved these changes
also optimised imports across the whole project (only 4 files got changed)

2024-04-09 18:49 UTC, hannibal002 approved these changes

2024-04-09 18:49 UTC, merged