Fix: Item Size in Crop Milestones GUI
hannibal00212/SkyHanni pull request #1424
Opened 2024-04-10 22:23 UTC by martimavocado

## What
Fixes the item scale in the Crop Milestones, Mooshroom Crop Milestones, and Best Crop GUIs to be closer to how it used to be.
<details>
<summary>Images</summary>

old:
![image](https://github.com/hannibal002/SkyHanni/assets/39881008/fbea4bc8-f774-46ea-95af-7447ceeacbd9)

new: 
![image](https://github.com/hannibal002/SkyHanni/assets/39881008/edc80bb8-8137-47d3-ba7f-ccb66c4d76c6)

</details>

## Changelog Fixes
+ Fixed item sizes in the Crop Milestone display. - martimavocado

2024-04-11 05:30 UTC, Thunderblade73 commented
Use NeuItems.itemFontSize instead of 0.8. Since that should fit better here.

2024-04-12 00:59 UTC, CalMWolfs approved these changes

2024-04-12 12:22 UTC, hannibal002 requested changes
This pr does not change anything. The default value for `itemScale` is already `NEUItems.itemFontSize`, see https://github.com/hannibal002/SkyHanni/blob/85138c09082541e0b9c8b9b50c9e7afce2e03101/src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt#L531
Therefore, the bug is still there.
![image](https://github.com/hannibal002/SkyHanni/assets/24389977/af0ab2a1-a68e-4c1e-a050-65782d543b15)

2024-04-12 15:34 UTC, martimavocado commented
something broke since this pr and the current beta, itemScale doesn't seem to do anything anymore, any ideas why?

2024-04-12 17:06 UTC, Thunderblade73 commented
Made a Pr to this that fixes that.
https://github.com/martimavocado/SkyHanni/pull/46

2024-04-12 17:08 UTC, hannibal002 commented
> Made a Pr to this that fixes that. [martimavocado#46](https://github.com/martimavocado/SkyHanni/pull/46)

At this point, you can simply create a pr to beta instead, cleaner change diff :)

2024-04-13 00:54 UTC, martimavocado commented
closing in favor of thunderblade opening a new pr with the new fix

2024-04-13 00:54 UTC, closed without merging