New Feature: Excavation Profit Tracker
hannibal00212/SkyHanni pull request #1432
Opened 2024-04-12 09:34 UTC by hannibal002

## Dependencies
- #1431

## What
Profit tracker for excavation in new mining area

<details>
<summary>Images</summary>

![image](https://github.com/hannibal002/SkyHanni/assets/24389977/9288c8c6-f7b6-4792-af3f-005125c45b8e)

</details>

## Changelog New Features
+ Added Excavation Profit Tracker. - hannibal2
    * shows when inside excavation inventory in glacial cave.

2024-04-12 09:58 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/features/mining/ExcavatorProfitTrackerConfig.java
> +        desc = "Count all drops you gain while excavating fossils in the Glacial Cave."
i think it is glacial tunnels

2024-04-12 10:00 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/mining/ExcavatorProfitTrackerConfig.java
> +        desc = "Count all drops you gain while excavating fossils in the Glacial Cave."
fixed

2024-04-12 10:47 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/mining/ExcavatorProfitTrackerConfig.java
> +        desc = "Count all drops you gain while excavating fossils in the Glacial Cave."
fixed

2024-04-13 11:43 UTC, ItsEmpa requested changes

2024-04-13 11:43 UTC, ItsEmpa commented on src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/ExcavatorProfitTracker.kt
> +                "${scrapItem.itemName}§7: §c${NumberUtil.format(scrapPrice)}",
make the price spent be shown as a negative number, to be consistent with the slayer profit tracker

```suggestion
                "${scrapItem.itemName}§7: §c-${NumberUtil.format(scrapPrice)}",
```

2024-04-13 11:43 UTC, ItsEmpa commented on src/main/java/at/hannibal2/skyhanni/features/mining/fossilexcavator/ExcavatorProfitTracker.kt
> +        addAsSingletonList(tracker.addTotalProfit(profit, data.timesExcavated, "excarvation"))
should be "excavation" not "excarvation"
```suggestion
        addAsSingletonList(tracker.addTotalProfit(profit, data.timesExcavated, "excavation"))
```

2024-04-13 19:33 UTC, ItsEmpa approved these changes

2024-04-13 20:05 UTC, merged