Improvement: Added Display Options to Powder
hannibal00212/SkyHanni pull request #1442
Opened 2024-04-14 00:56 UTC by j10a1n15

## Dependencies
- ![image](https://github.com/hannibal002/SkyHanni/assets/45315647/aabf2e3a-0ab0-43a0-9da0-c8b264d0bb8c)

## What
This Pull Request adds display options (available, total, available & total) to the custom scoreboard.

<details>
<summary>Images</summary>

![image](https://github.com/hannibal002/SkyHanni/assets/45315647/9ea43dcb-5cde-4b8d-901e-a39b79c63f95)
![image](https://github.com/hannibal002/SkyHanni/assets/45315647/8e972688-16e6-410c-bce5-f5e6b2ac6e11)
![image](https://github.com/hannibal002/SkyHanni/assets/45315647/82593c59-1d71-40e4-87e4-2d34e6c82de1)

![image](https://github.com/hannibal002/SkyHanni/assets/45315647/09a0b28d-32ef-48ef-8513-5e969626d205)

</details>

## Changelog Improvements
+ Added different display options for Powder in Custom Scoreboard. - j10a1n15

2024-05-30 09:49 UTC, Thunderblade73 commented
To fix the merge conflict merge [hotmAPI](https://github.com/Thunderblade73/SkyHanni/tree/hotm-API) into it

2024-06-01 02:10 UTC, CalMWolfs requested changes

2024-06-01 02:10 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/Storage.java
idk what happened here but yea

2024-06-01 12:30 UTC, CalMWolfs approved these changes

2024-06-13 18:49 UTC, merged