Backend: Graph Editor
hannibal00212/SkyHanni pull request #1454
Opened 2024-04-15 17:19 UTC by Thunderblade73

## Dependencies
- #1405

## What
Adds an editor in which you can make a graph ingame.
Also has an implementation of Dijkstras Algorithm (was to lazy for A*).

<details>
<summary>Images</summary>

![image](https://github.com/hannibal002/SkyHanni/assets/85900443/d2e5c0f9-2093-4db4-bc18-c57d0545c9ca)

</details>

## Changelog Technical Details
+ DevTool Graph Editor. - Thunderblade73

2024-06-01 00:48 UTC, CalMWolfs requested changes
Seemed to mostly work from my testing, except it took a few minutes to work out how I was supposed to use it. Some instructions would be nice, possibly togglable with a keybind and would show in the editing gui. Also I would love chat feedback, as i had no clue what was happening. 
Lastly, the default keybind of t for text just opened the chat for me until I rebound it

2024-06-05 14:28 UTC, ThatGravyBoat requested changes

2024-06-05 14:28 UTC, ThatGravyBoat commented on src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
> +        loadModule(GraphEditor)
Use `SkyHanniModule` annotation instead

2024-06-06 07:54 UTC, CalMWolfs approved these changes

2024-06-10 01:11 UTC, merged