Feature: Add Ignored users for Party Commands
hannibal00212/SkyHanni pull request #1469
Opened 2024-04-16 23:15 UTC by martimavocado

## What
Adds `/shignore` which lets you blacklist certain people from using party commands.
This has several sub-commands, including `add`, `remove`, `list` and `clear`. 
- `add` and `remove` always take another argument, being the username to add/remove. 
- `list` takes an optional argument, checking if a given username is ignored, or listing every username when none is given.
- `clear` clears the list with a confirmation prompt.
- when no subcommands are taken, it will assume a add/remove toggle for the given username. 

<details>
<summary>Images</summary>

![image](https://github.com/hannibal002/SkyHanni/assets/39881008/e08133ea-7122-4915-81fe-5120b5855ea5)

![image](https://github.com/hannibal002/SkyHanni/assets/39881008/dc66bae0-651c-4cb5-b67d-1abd730caaeb)
![image](https://github.com/hannibal002/SkyHanni/assets/39881008/024f494b-ec11-4e95-8f84-f2c3e526a72f)

![image](https://github.com/hannibal002/SkyHanni/assets/39881008/dc9876fa-a455-480d-9fc1-e17d3caf227a)

![image](https://github.com/hannibal002/SkyHanni/assets/39881008/ac903710-1309-439f-af2b-dd3929b3a414)
![image](https://github.com/hannibal002/SkyHanni/assets/39881008/00e2826e-a75f-4f6e-a45b-ad7eec6eeefc)

![image](https://github.com/hannibal002/SkyHanni/assets/39881008/50a6ddb4-c708-4b4e-b5a7-4222d7244fa9)

</details>

## Changelog New Features
+ Added /shignore. - martimavocado
    * This lets you block users from running party commands.

2024-04-17 07:47 UTC, CalMWolfs requested changes
also can you please do the generic changes (make functions private and change the config variable to be called config) like in #1464

2024-04-17 07:47 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/commands/PartyChatCommands.kt
> +            ChatUtils.chat("§cIgnoring chat command from ${event.author}. Unblock them using *unblacklist command here*.")
seems to be missing a command here

2024-04-17 07:49 UTC, ItsEmpa commented on src/main/java/at/hannibal2/skyhanni/features/commands/PartyChatCommands.kt
> +            ChatUtils.chat("§cIgnoring chat command from ${event.author}. Unblock them using *unblacklist command here*.")
i assume the missing command is `/shignore remove <name>`. could make this a clickable message that runs that command when clicked

2024-04-17 07:50 UTC, ItsEmpa commented on src/main/java/at/hannibal2/skyhanni/features/commands/PartyChatCommands.kt
> +            ChatUtils.chat("§cIgnoring chat command from ${event.author}. Unblock them using *unblacklist command here*.")
also i feel like there should be a toggle to disable this message

2024-04-17 14:26 UTC, CalMWolfs approved these changes
Haven't tested in game but code looks fine

2024-04-23 21:34 UTC, hannibal002 requested changes
I thought we wanted to use Hypixel's  /ignore list, not create our own?

2024-04-23 21:36 UTC, CalMWolfs commented
> I thought we wanted to use Hypixel's /ignore list, not create our own?

Own ignore list is fine here I think, this is like a list of not trusted party members but they arent bad enough to be fully blocked from being in the party, or at least that is my understanding

2024-04-23 22:08 UTC, martimavocado commented
> I thought we wanted to use Hypixel's /ignore list, not create our own?

if this is the case that wasn't very clear for me from the conversation in the discord thread, but i could redo this to use hypixel's list instead of a custom one if you think that's better

2024-04-23 22:23 UTC, hannibal002 commented
i dont think thats better, i just thought we decided to do it this way. if this was not clear, im fine with the current version as well

2024-04-25 07:31 UTC, hannibal002 approved these changes
works now

2024-04-25 07:31 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/misc/PartyCommandsConfig.java
> +    public List<String> blacklistedUsers = new ArrayList<>();
move to storage

2024-04-25 07:32 UTC, hannibal002 requested changes
missclick

2024-05-01 10:33 UTC, hannibal002 requested changes
merge conflicts

2024-05-01 17:41 UTC, hannibal002 approved these changes
![image](https://github.com/hannibal002/SkyHanni/assets/24389977/35e39842-a07d-48e2-a05c-10f62c949ccd)

2024-05-01 17:49 UTC, merged