Feature: add guide to dungeon hub races
hannibal00212/SkyHanni pull request #1471
Opened 2024-04-17 06:09 UTC by SeRaid743

## Dependencies
- https://github.com/hannibal002/SkyHanni-REPO/pull/153

## What
Add guide to dungeon hub races for all three races. Only works for Nothing; No return races

<details>
<summary>Images</summary>

![image](https://github.com/hannibal002/SkyHanni/assets/77941535/3fcd49e3-d14b-44d1-81d7-c72b20a2e161)

</details>

## Changelog New Features
+ Add dungeon hub race waypoints. - seraid

## Changelog Technical Details
+ added NamedParkourJson. - seraid

2024-04-18 15:18 UTC, CalMWolfs approved these changes

2024-04-21 09:43 UTC, CalMWolfs requested changes

2024-04-21 09:43 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/NamedParkourJson.kt
This should not be a map of maps, NamedParkourJson should only be `Map<String, ParkourJson>` and then a further `DungeonHubRacesJson` data class should hold a `Map<String, NamedParkourJson>`

2024-04-22 07:43 UTC, CalMWolfs approved these changes

2024-04-23 21:57 UTC, hannibal002 requested changes, later dismissed
works fine, except it breaks on every ability use (e.g. aote teleport). this is part of ParkourHelper, maybe you can fix it?

2024-04-23 21:57 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonsRaceGuide.kt
> +        parkourHelpers[currentRace]?.render(event)
can we store the ParkourHelper instance in the variable currentRace? that way we dont need to do one map lookup each frame

2024-04-24 06:17 UTC, CalMWolfs commented
> works fine, except it breaks on every ability use (e.g. aote teleport). this is part of ParkourHelper, maybe you can fix it?

In my opinion this is not a problem as the feature is not made to work for the later races. The whole feature is written to only work with Nothing at all; No return races. In these races you cannot use abilities so this will never break. This is made as just a little guide for beginners as once you are at the point of using abilities and pearls these waypoints do not provide much use.

2024-05-01 09:02 UTC, hannibal002 approved these changes

2024-05-01 09:02 UTC, merged