Backend: Improves performance of item backgrounds and borders
hannibal00212/SkyHanni pull request #1497
Opened 2024-04-19 21:51 UTC by ThatGravyBoat

## What
This PR moves the item backgrounds and borders from being a map in `ItemRenderBackground` to a variable stored in `CachedItemData` this is far more performant than a map with itemstack as a key due to the nature of itemstack and its data it being a key requires it to loop through the values to find it because itemstack does not implement hashcode and localcache uses equals for hash checks when not told to do otherwise, this should also allow the data to be dereferenced when the stack does which should not allow any references of the item to stay around even when the item does not exist anywhere.

## Changelog Technical Details
+ Move item background and border data into `CachedItemData` - ThatGravyBoat

2024-04-20 02:39 UTC, CalMWolfs approved these changes
worked for me

2024-04-23 07:00 UTC, hannibal002 requested changes
Works fine in my dev env, just the gray effect needs to go.

2024-04-23 07:00 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/itemabilities/abilitycooldown/ItemAbilityCooldown.kt
> +            event highlight color.addOpacity(opacity)
While holding an item with active ability, the whole screen gets a gray effect.
![image](https://github.com/hannibal002/SkyHanni/assets/24389977/625010b7-1996-4bf0-9716-fcbefbd4c54f)
![image](https://github.com/hannibal002/SkyHanni/assets/24389977/4c86d186-7d6f-4ca3-a20b-40f99f522c3a)

2024-04-23 07:00 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/itemabilities/abilitycooldown/ItemAbilityCooldown.kt
> +    private var items = mapOf<String?, List<ItemText>>()
We always check a non-nullable key for the map, the key should not be nullable.

2024-04-23 07:00 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/itemabilities/abilitycooldown/ItemAbilityCooldown.kt
> +            { it.key.getIdentifier() },
filter out when getIdentifier() returns null

2024-04-23 14:11 UTC, hannibal002 requested changes
while inside inventories, slots with items on them have a different background to other items. this does not happen when pressing E. maybe because of an NEU fancy overlay thing? does not happen in skyblock menu, but in other menus, e.g. bazaar
![image](https://github.com/hannibal002/SkyHanni/assets/24389977/b48656e5-2d27-4a96-9f07-8aee36317f07)

![image](https://github.com/hannibal002/SkyHanni/assets/24389977/dd5595ae-4539-497e-af14-22916dde154b)

2024-04-23 14:36 UTC, ThatGravyBoat commented
I cant reproduce, you must have a feature enabled that is conflicting with the highlight changes

2024-04-23 14:40 UTC, ThatGravyBoat commented
you have the feature HideNotClickableItems on which does that to show which items you cant click

2024-04-25 07:13 UTC, hannibal002 requested changes
<details>
<summary>colours in /tab look desaturated now.</summary>

![image](https://github.com/hannibal002/SkyHanni/assets/24389977/f6213369-5fa9-4b4a-8f53-018bb848e0ec)

</details>


<details>
<summary>same in inventory</summary>

![image](https://github.com/hannibal002/SkyHanni/assets/24389977/2a2af809-9889-4086-b3ea-db92199675a2)

</details>

I think this affects all 35 usages of `infix fun Slot.highlight(color: LorenzColor) {`.

2024-04-25 09:36 UTC, ThatGravyBoat commented
Okay fixed this, I by accident removed the lighting when fixing that color setting and attribute changes that were already there that caused the whole screen to have its colored changed.

2024-04-25 09:58 UTC, hannibal002 approved these changes
works fine for me

2024-04-25 09:59 UTC, merged