Feature: Mineshaft click to gfs ascension rope
hannibal00212/SkyHanni pull request #1542
Opened 2024-04-24 21:05 UTC by j10a1n15

## What
This Pull Request adds a feature which allows to user to get an Ascension Rope from sack.
With this Item you can now leave the mineshaft and still get the leaving rewards.

<details>
<summary>Images</summary>

I changed the text to yellow, didnt bother getting a new screenshot
![image](https://github.com/hannibal002/SkyHanni/assets/45315647/7ce21290-f3a4-4144-a260-cb5af37d91c2)

</details>

## Changelog New Features
+ Click to get an Ascension Rope from sacks in the Mineshaft. - j10a1n15

2024-04-24 21:06 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/mining/MiningNotifications.kt
> +                        ChatUtils.clickableChat("Click here to get an Ascension Rope!", "/gfs ASCENSION_ROPE 1")
please use the gefFromSackApi. (Has a clickable chat variant)

2024-04-24 22:33 UTC, Thunderblade73 commented
This new function, I don't like. Since creating a primitivItem stack is simple to do and also is possible to cach in this case. The method btw. is .toPrimitivStack for NeuInternalNames (not sure if I mistyped the function name).

2024-04-25 08:06 UTC, hannibal002 requested changes
small changes

2024-04-25 08:06 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/api/GetFromSackAPI.kt
> +        text: String = "§lCLICK HERE§r§e to grab §ax${amount} §9${item.asString()}§e from sacks!"
```suggestion
        text: String = "§lCLICK HERE§r§e to grab §ax${amount} §9${item.itemName}§e from sacks!"
```

2024-04-25 08:06 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/mining/MiningNotificationsConfig.java
> +        "§cOnly works if you have an Ascension Rope in your sacks.")
```suggestion
    @ConfigOption(
        name = "Get Ascension Rope",
        desc = "Click on a chat message to get an Ascension Rope when you're at 90 Cold and in the §bMineshaft§7. " +
            "§cOnly works if you have an Ascension Rope in your sacks."
    )
```

2024-04-25 08:06 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/mining/MiningNotifications.kt
> +        "§9§lBRRR! §r§bYou're freezing! All you can think about is getting out of here to a warm campfire..."
```suggestion
        "§9§lBRRR! §r§bYou're freezing! All you can think about is getting out of here to a warm campfire\\.\\.\\."
```

2024-04-25 08:29 UTC, hannibal002 approved these changes

2024-04-25 08:29 UTC, merged