Improvement: Better Custom Scoreboard Alignment
hannibal00212/SkyHanni pull request #1566
Opened 2024-04-27 11:47 UTC by j10a1n15

## What
Describe what this pull request does, including technical details, screenshots, links to discord, etc.

<details>
<summary>Images</summary>

</details>

## Changelog New Features
+ Cool new feature. - your_name_here
    * extra info

## Changelog Improvements
+ Improved cool feature. - your_name_here
    * Extra info.

## Changelog Fixes
+ Fixed cool feature. - your_name_here
    * Extra info.

## Changelog Technical Details
+ Something technical you changed in the backend. - your_name_here
    * Extra info.

## Changelog Removed Features
+ Removed cool feature. - your_name_here
    * Extra info.

2024-04-29 22:13 UTC, CalMWolfs requested changes
few small things

2024-04-29 22:13 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
> +    const val CONFIG_VERSION = 42
this needs to be 43 now

2024-04-29 22:13 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/AlignmentConfig.java
> +    @ConfigOption(name = "Align Horizontally", desc = "Align the scoreboard on the horizontal axis.")
```suggestion
    @ConfigOption(name = "Horizontal Alignment", desc = "Alignment for the scoreboard on the horizontal axis.")
```

2024-04-29 22:13 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/features/gui/customscoreboard/AlignmentConfig.java
> +    @ConfigOption(name = "Align Vertically", desc = "Align the scoreboard on the vertical axis.")
```suggestion
    @ConfigOption(name = "Vertical Alignment", desc = "Alignment for the scoreboard on the vertical axis."
```

2024-04-29 22:13 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
> +        event.move(42, "$displayPrefix.alignment.alignRight", "$displayPrefix.alignment.horizontalAlignment") {
```suggestion
        event.move(43, "$displayPrefix.alignment.alignRight", "$displayPrefix.alignment.horizontalAlignment") {
```

2024-04-29 22:13 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
> +        event.move(42, "$displayPrefix.alignment.alignCenterVertically", "$displayPrefix.alignment.verticalAlignment") {
```suggestion
        event.move(43, "$displayPrefix.alignment.alignCenterVertically", "$displayPrefix.alignment.verticalAlignment") {
```

2024-04-29 22:15 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/config/ConfigUpdaterMigrator.kt
> +    const val CONFIG_VERSION = 42
```suggestion
    const val CONFIG_VERSION = 43
```

2024-04-29 22:18 UTC, CalMWolfs approved these changes
code looks good, havent tested in game

2024-04-30 10:50 UTC, hannibal002 requested changes
just code cleanup stuff. have not tested yet

2024-04-30 10:50 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
> +                JsonPrimitive(HorizontalAlignment.RIGHT.name)
move `JsonPrimitive(` outside the if. same below)

2024-04-30 10:50 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
> +                JsonPrimitive(RenderUtils.VerticalAlignment.CENTER.name)
make RenderUtils import consistent

2024-04-30 10:50 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
> +            if (alignmentConfig.horizontalAlignment != HorizontalAlignment.DONT_ALIGN
maybe use `with(alignmentConfig) {` here

2024-04-30 10:50 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/RenderBackground.kt
>          if (
please move the whole if block into a new function for readabilty

2024-04-30 10:50 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
> +        DONT_ALIGN("Don't Align")
missing comma

2024-04-30 17:12 UTC, hannibal002 approved these changes

2024-04-30 17:12 UTC, merged