Fix: SkyHanni forcing Vanilla Scoreboard to show while using Apec
hannibal00212/SkyHanni pull request #1592
Opened 2024-04-29 10:51 UTC by j10a1n15

## What
This Pull Request fixes SkyHanni forcing the Vanilla Scoreboard to be shown, when using Apec while having the Custom Scoreboard disabled.

## Changelog Fixes
+ Fixed SkyHanni showing the Vanilla Scoreboard when using Apec. - hannibal2, j10a1n15

2024-04-29 12:33 UTC, hannibal002 requested changes
disabling custom scoreboard does not show vanilla scoreboard again. first disabling "hide vanilla scoreboard" works though.
tested in dev env without apec
![image](https://github.com/hannibal002/SkyHanni/assets/24389977/75a3f3be-0b5d-4432-88dd-052e1382f9a1)

2024-04-29 18:42 UTC, hannibal002 requested changes

2024-04-29 18:42 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
> +            if (!isHideVanillaScoreboardEnabled()) dirty = true
code duplication (see above)

2024-04-30 10:02 UTC, hannibal002 requested changes
works well without apec in dev env

2024-04-30 10:03 UTC, hannibal002 approved these changes
Missclick

2024-04-30 10:03 UTC, merged

2024-04-30 10:04 UTC, j10a1n15 commented
> works well without apec in dev env

also tried with apec in normal env, seems to have worked in there