added timer to hoppity egg gui and chat messages
hannibal00212/SkyHanni pull request #1625
Opened 2024-05-01 13:42 UTC by SeRaid743

## What
Added chat messages until next egg spawn and until next hoppity event. 
Added timer until next spawn to the egg gui

<details>
<summary>Images</summary>

![image](https://github.com/hannibal002/SkyHanni/assets/77941535/1da0f82a-dc8e-4539-ae44-f64d512b5f21)

</details>

## Changelog New Features
+ Added time until next hoppity event in chat message for egg locator. - seraid

## Changelog Improvements
+ Added time until next egg. - seraid

2024-05-01 13:43 UTC, SeRaid743 commented
waiting until hoppity event so it can be tested properly

2024-05-01 18:00 UTC, hannibal002 requested changes
If we want those changes in beta before the next Hoppity event, please split into two prs. I would rather not review code I can't test.

2024-05-01 18:00 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
> +            event.chatComponent.appendText("\n§eNext Hoppity's Hunt in §b${timeUntil.format()}")
```suggestion
            ChatUtils.chat("§eNext Hoppity's Hunt in §b${timeUntil.format()}")
```

2024-05-01 18:00 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggType.kt
> +        return SkyBlockTime.now().copy(hour = resetsAt, minute = 0, second = 0).asTimeMark().timeUntil()
```suggestion
        val now = SkyBlockTime.now()
        if (now.hour >= resetsAt) {
            return now.copy(day = now.day + 1, hour = resetsAt, minute = 0, second = 0)
                .asTimeMark().timeUntil()
        }
        return now.copy(hour = resetsAt, minute = 0, second = 0).asTimeMark().timeUntil()
```

2024-05-02 10:15 UTC, SeRaid743 commented on src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
> +            event.chatComponent.appendText("\n§eNext Hoppity's Hunt in §b${timeUntil.format()}")
if i do this it will send the chat messages in the wrong order

2024-05-02 10:18 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
> +            event.chatComponent.appendText("\n§eNext Hoppity's Hunt in §b${timeUntil.format()}")
We could just hide the original message entirely?

2024-05-03 09:55 UTC, hannibal002 commented
![image](https://github.com/hannibal002/SkyHanni/assets/24389977/6c97b90a-ca8b-488a-ab55-735035e5a6fa)

2024-05-03 09:55 UTC, hannibal002 commented
![image](https://github.com/hannibal002/SkyHanni/assets/24389977/45dd62df-e20b-4430-bb17-9919a2682115)
![image](https://github.com/hannibal002/SkyHanni/assets/24389977/b5efada6-613d-43a9-b9c7-1414355ffd82)

2024-05-03 10:03 UTC, hannibal002 approved these changes

2024-05-03 10:04 UTC, merged