Improvement: egg hunt include note
hannibal00212/SkyHanni pull request #1675
Opened 2024-05-03 22:41 UTC by hannibal002

## What
Sharing the name of the rabbit hunt egg note in chat.

## Changelog Improvements
+ Sharing the name of the rabbit hunt egg note in chat. - hannibal2

2024-05-03 23:06 UTC, CalMWolfs requested changes
havent tested in game but the rest of the changes look good

2024-05-03 23:06 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
> +        "§d§lHOPPITY'S HUNT §r§dYou found a §r§.Chocolate (?<meal>\\w+) Egg §r§d(?<note>.*)§r§d!"
will not match this:
§d§lHOPPITY'S HUNT §r§dYou found a §r§9Chocolate Lunch Egg §r§dnear the §r§5Dark Auction§r§d!
or
§d§lHOPPITY'S HUNT §r§dYou found a §r§6Chocolate Breakfast Egg §r§din §r§cUnincorporated Territory§r§d!

2024-05-03 23:14 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
> +        "§d§lHOPPITY'S HUNT §r§dYou found a §r§.Chocolate (?<meal>\\w+) Egg §r§d(?<note>.*)§r§d!"
i dont understand

2024-05-03 23:20 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
> +        "§d§lHOPPITY'S HUNT §r§dYou found a §r§.Chocolate (?<meal>\\w+) Egg §r§d(?<note>.*)§r§d!"
> i dont understand

these two messages dont match your new pattern

2024-05-03 23:21 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsManager.kt
> +        "§d§lHOPPITY'S HUNT §r§dYou found a §r§.Chocolate (?<meal>\\w+) Egg §r§d(?<note>.*)§r§d!"
wait never mind i'm going crazy

2024-05-03 23:21 UTC, CalMWolfs approved these changes
nvm

2024-05-03 23:22 UTC, CalMWolfs requested changes

2024-05-03 23:22 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsShared.kt
> +            val note = groupOrNull("note")
```suggestion
            val note = groupOrNull("note")?.removeColor()
```

2024-05-03 23:27 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEggsShared.kt
> +            val note = groupOrNull("note")
fair

2024-05-04 01:50 UTC, CalMWolfs approved these changes

2024-05-04 01:54 UTC, merged