Fix: Grammar within FishingProfitTracker.kt
hannibal00212/SkyHanni pull request #1678
Opened 2024-05-03 23:57 UTC by raaaaaven

## What
Improved the grammar within FishingProfitTracker

## Changelog Improvements
+ Fixed a typo within fishing profit tracker.

2024-05-03 23:57 UTC, CalMWolfs approved these changes

2024-05-04 00:11 UTC, hannibal002 requested changes
now word it good without the word something please

2024-05-04 00:38 UTC, martimavocado commented
fix author in changelog maybe

2024-05-04 00:41 UTC, raaaaaven commented
> fix author in changelog maybe

woopsie

2024-05-04 00:53 UTC, hannibal002 approved these changes

2024-05-04 00:53 UTC, merged