Feature: Hide tooltips while in the Harp.
hannibal00212/SkyHanni pull request #1700
Opened 2024-05-04 21:54 UTC by raaaaaven

## What
Remove the tooltip inside the Harp.

<details>
<summary>Images</summary>

![image](https://github.com/hannibal002/SkyHanni/assets/168305416/f5aeeb65-48f9-42ef-aeaf-dd5994510bd1)

</details>

## Changelog New Features
+ Hides the item tooltips inside the Harp - raven

2024-05-04 21:56 UTC, Thunderblade73 requested changes

2024-05-04 21:56 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/HarpFeatures.kt
> +            event.toolTip.clear()
use event.cancel here instead

2024-05-04 22:00 UTC, raaaaaven commented on src/main/java/at/hannibal2/skyhanni/features/inventory/HarpFeatures.kt
> +            event.toolTip.clear()
should be done now

2024-05-06 15:03 UTC, hannibal002 approved these changes

2024-05-06 15:03 UTC, merged