Improvement: Compact Dicer Tracker
hannibal00212/SkyHanni pull request #1735
Opened 2024-05-07 21:40 UTC by Jordyrat

## What
Shortened the Dicer Tracker and added an option for a compacted version.

<details>
<summary>Images</summary>

![image](https://github.com/hannibal002/SkyHanni/assets/77755681/e55a5a1e-438f-4f43-ab3c-4a5e65167a7a)
![image](https://github.com/hannibal002/SkyHanni/assets/77755681/b17feacd-e4b3-4816-a48c-463dbef31e68)

</details>

## Changelog Improvements
+ Shortened Dicer RNG Drop Tracker Display. - Jordyrat
+ Added option for a compacted Dicer RNG Drop Tracker Display - Jordyrat

2024-05-07 21:46 UTC, Thunderblade73 commented
The changelog shouldn't be two entries here.

2024-05-07 22:03 UTC, Jordyrat commented
> The changelog shouldn't be two entries here.

Updated; wasn't sure since it's 2 changes.

2024-06-01 01:21 UTC, CalMWolfs requested changes

2024-06-01 01:21 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/garden/farming/DicerRngDropTracker.kt
> +        var compactLine = ""
this should be inside the if statement where it is used

2024-06-01 01:21 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/garden/farming/DicerRngDropTracker.kt
also add a few line breaks in drawDisplay to make it more readable

2024-06-01 02:44 UTC, CalMWolfs approved these changes

2024-06-01 10:11 UTC, merged