Feature: cofl ah search item
hannibal00212/SkyHanni pull request #1743
Opened 2024-05-08 20:15 UTC by hannibal002

## What
Added an Item in AH search browser that allows searching for this item on https://sky.coflnet.com/

<details>
<summary>Images</summary>

![image](https://github.com/hannibal002/SkyHanni/assets/24389977/39fbefd5-9e6d-48d9-88d1-212e5c235139)
opens https://sky.coflnet.com/item/HYPERION?range=day

</details>

## Changelog New Features
+ Added an Item in AH search browser that allows searching for this item on coflnet.com. - hannibal2

2024-05-08 20:22 UTC, Ekwav commented on src/main/java/at/hannibal2/skyhanni/features/inventory/auctionhouse/AuctionHouseOpenPriceWebsite.kt
> +        cookieDurationPattern.matchMatcher(event.inventoryName) {
Looks like a copy paste error
```suggestion
    private val ahSearchPattern by patternGroup.pattern(
        "title.search",
        "Auctions: \"(?<searchTerm>.*)\""
    )

    private var searchTerm = ""
    private var displayItem: ItemStack? = null

    @SubscribeEvent
    fun onInventoryOpen(event: InventoryFullyOpenedEvent) {
        if (!isEnabled()) return
        ahSearchPattern.matchMatcher(event.inventoryName) {
```

2024-05-09 06:08 UTC, Ekwav approved these changes

2024-05-09 06:08 UTC, Ekwav commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/AuctionHouseConfig.java
> +    @ConfigOption(name = "Price Website", desc = "Adds a button to the Auction House that will open the item page in §ccoflnet.com§7.")
To be consistent between both descriptions
```suggestion
    @ConfigOption(name = "Price Website", desc = "Adds a button to the Auction House that will open the item page in §csky.coflnet.com§7.")
```

2024-05-09 06:41 UTC, Obsidianninja11 commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/AuctionHouseConfig.java
> +    @ConfigOption(name = "Price Website", desc = "Adds a button to the Auction House that will open the item page in §ccoflnet.com§7.")
Why is coflnet red?
Shouldn't it be yellow?
also what Ekwav said. sky.coflnet.com is the website

2024-05-09 08:12 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/AuctionHouseConfig.java
> +    @ConfigOption(name = "Price Website", desc = "Adds a button to the Auction House that will open the item page in §ccoflnet.com§7.")
Yellow are only commands, red is important stuff. e.g. the name of an external service.

![image](https://github.com/hannibal002/SkyHanni/assets/24389977/291c6cb3-de90-4b1a-a7c9-3cb87ca66174)

2024-05-11 08:36 UTC, CalMWolfs requested changes
just this

2024-05-11 08:36 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/inventory/auctionhouse/AuctionHouseOpenPriceWebsite.kt
> +        "Auctions: \"(?<searchTerm>.*)\""
Does not match long patterns

![image](https://github.com/hannibal002/SkyHanni/assets/94038482/7283f200-ef08-41ed-982d-fe61886825f3)

2024-05-14 07:59 UTC, hannibal002 commented
suddently this error happens
<details>
<summary>Stack trace</summary>

```
SkyHanni 0.25.Beta.26: Caught an URISyntaxException in AuctionHouseOpenPriceWebsite at SlotClickEvent: Illegal character in path at index 43: https://sky.coflnet.com/api/mod/open/Golden Dragon
 
Caused by java.net.URISyntaxException: Illegal character in path at index 43: https://sky.coflnet.com/api/mod/open/Golden Dragon
at java.net.URI$Parser.fail(URI.java:2848)
at java.net.URI$Parser.checkChars(URI.java:3021)
at java.net.URI$Parser.parseHierarchical(URI.java:3105)
at java.net.URI$Parser.parse(URI.java:3053)
at java.net.URI.<init>(URI.java:588)
at SH.utils.OSUtils.openBrowser(OSUtils.kt:16)
at SH.features.inventory.auctionhouse.AuctionHouseOpenPriceWebsite.onSlotClick(AuctionHouseOpenPriceWebsite.kt:83)
at SH.mixins.hooks.GuiContainerHook.onMouseClick(GuiContainerHook.kt:62)
at MC.client.gui.inventory.GuiContainer.handler$onMouseClick$zza000(GuiContainer.java:2307)
at MC.client.gui.inventory.GuiContainer.handleMouseClick(GuiContainer.java:629)
at MC.client.gui.inventory.GuiContainer.mouseClicked(GuiContainer.java:388)
at MC.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:555)
at MC.client.gui.GuiScreen.handleInput(GuiScreen.java:524)
at MC.client.Minecraft.runTick(Minecraft.java:1674)
at MC.client.Minecraft.runGameLoop(Minecraft.java:1024)
at MC.client.Minecraft.run(Minecraft.java:349)
at MC.client.main.Main.main(Main.java:124)
```

</details>

when i try to fix it with this

<details>
<summary>Patch</summary>

Index: src/main/java/at/hannibal2/skyhanni/features/inventory/auctionhouse/AuctionHouseOpenPriceWebsite.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/main/java/at/hannibal2/skyhanni/features/inventory/auctionhouse/AuctionHouseOpenPriceWebsite.kt b/src/main/java/at/hannibal2/skyhanni/features/inventory/auctionhouse/AuctionHouseOpenPriceWebsite.kt
--- a/src/main/java/at/hannibal2/skyhanni/features/inventory/auctionhouse/AuctionHouseOpenPriceWebsite.kt(revision 0a5ccaa3d6be5113c8f4d6def9d966a1df720712)
+++ b/src/main/java/at/hannibal2/skyhanni/features/inventory/auctionhouse/AuctionHouseOpenPriceWebsite.kt(date 1715673321561)
@@ -17,6 +17,7 @@
 import net.minecraft.item.ItemStack
 import net.minecraftforge.fml.common.eventhandler.EventPriority
 import net.minecraftforge.fml.common.eventhandler.SubscribeEvent
+import java.net.URLEncoder
 import kotlin.time.Duration.Companion.seconds
 
 class AuctionHouseOpenPriceWebsite {
@@ -79,7 +80,8 @@
         if (event.slotId != 8) return
         event.isCanceled = true
         if (lastClick.passedSince() > 0.3.seconds) {
-            val url = "https://sky.coflnet.com/api/mod/open/$searchTerm"
+            val search = URLEncoder.encode(searchTerm, "UTF-8")
+            val url = "https://sky.coflnet.com/api/mod/open/$search"
             OSUtils.openBrowser(url)
             lastClick = SimpleTimeMark.now()
         }


</details>
then the website links me to start page instead to the item page

2024-05-16 12:39 UTC, Ekwav approved these changes

2024-05-16 22:30 UTC, CalMWolfs approved these changes
code lgtm

2024-05-16 22:48 UTC, merged