Feature + Fix: Added new chat filters, Fixed: Healer Orb Pickup
hannibal00212/SkyHanni pull request #1750
Opened 2024-05-09 15:10 UTC by Mikecraft1224

## What
Added chat filters for rare drops from chests, sacrifice and fixed healer orb pickups

## Changelog New Features
+ Added new chat filters. - Mikecraft1224
    * Rare dungeon chest rewards and sacrifice messages from other players.

## Changelog Fixes
+ Fixed healer orb pickup hider. - Mikecraft1224

2024-05-10 22:06 UTC, CalMWolfs approved these changes
code lgtm

2024-05-24 12:50 UTC, hannibal002 requested changes, later dismissed
adad regex-test cases

2024-05-24 12:50 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
> +    private val sacrificePatterns = listOf(
please insert regex-test cases

2024-05-24 12:50 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
> +    private val rareDropsMessages = listOf(
please insert regex-test cases

2024-05-26 00:35 UTC, CalMWolfs approved these changes

2024-05-26 11:30 UTC, merged