Feature: Ghost Profit Tracker
hannibal00212/SkyHanni pull request #1753
Opened 2024-05-10 10:10 UTC by ItsEmpa

## What
### WIP
Removes the Ghost Counter and replaces it with a Ghost Profit Tracker, to keep it consistent with other profit trackers, and to fix various issues with it.

TODO: 

- [ ] Migrate data from ghost counter to ghost profit tracker
- [ ] Rename configs to ghost profit tracker
- [ ] Store allowed items in repo
- [ ] Remove old ghost counter code

## Changelog New Features
+ Added Ghost Profit Tracker. - Empa
    * This replaces the now outdated and buggy Ghost Counter.

## Changelog Removed Features
+ Removed Ghost Counter. - Empa

2024-10-25 06:19 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/combat/ghosttracker/GhostTracker.kt
> +    )
Needs regex tests

2024-10-25 08:18 UTC, CalMWolfs approved these changes

2024-11-12 21:03 UTC, hannibal002 requested changes
![image](https://github.com/user-attachments/assets/e1eb618e-609d-4117-87b0-96126f9ab0dc)


```
SkyHanni 0.28.Beta.12: Caught a RepoError in GhostTracker at RepositoryReloadEvent: Repo file 'constants/GhostDrops.json' not found.
 
Caused by at.hannibal2.skyhanni.data.repo.RepoError: Repo file 'constants/GhostDrops.json' not found.
	at SH.data.repo.RepoUtils.getConstant(RepoUtils.kt:98)
	at SH.features.combat.ghosttracker.GhostTracker.onRepoReload(GhostTracker.kt:397)
	at SH.data.repo.RepoManager.reloadRepository$lambda$9(RepoManager.kt:195)
	at SH.utils.DelayedRun.onThread$lambda$2(DelayedRun.kt:45)
	at SH.data.repo.RepoManager.reloadRepository(RepoManager.kt:189)
	at SH.data.repo.RepoManager.reloadLocalRepo(RepoManager.kt:96)
	at SH.config.commands.Commands.devTest$lambda$199$lambda$198(Commands.kt:631)
	at net.minecraftforge.client.ClientCommandHandler.executeCommand(ClientCommandHandler.java:72)
	at MC.client.gui.GuiScreen.sendChatMessage(GuiScreen.java:446)
	at MC.client.gui.GuiScreen.sendChatMessage(GuiScreen.java:437)
	at MC.client.gui.GuiChat.keyTyped(GuiChat.java:111)
	at MC.client.gui.GuiScreen.handleKeyboardInput(GuiScreen.java:578)
	at MC.client.gui.GuiScreen.handleInput(GuiScreen.java:534)
	at MC.client.Minecraft.runTick(Minecraft.java:1674)
	at MC.client.Minecraft.runGameLoop(Minecraft.java:1024)
	at MC.client.Minecraft.run(Minecraft.java:349)
	at MC.client.main.Main.main(Main.java:124)
```

2024-11-24 00:28 UTC, hannibal002 requested changes
the code looks good

but the kill detection doesnt work
![image](https://github.com/user-attachments/assets/77fd3e92-04ca-497a-a152-f20dc1b55572)

2024-11-24 21:06 UTC, merged