Backend: Use HypixelCommands
hannibal00212/SkyHanni pull request #1769
Opened 2024-05-11 20:06 UTC by ItsEmpa

## What
Changes all usages of ChatUtils.sendCommandToServer to HypixelCommands instead, and cleaned up some classes.

## Changelog Technical Details
+ Removed all usages of ChatUtils.sendCommandToServer in favor of HypixelCommands. - Empa

2024-05-14 09:53 UTC, CalMWolfs requested changes

2024-05-14 09:53 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/event/diana/InquisitorWaypointShare.kt
> +        HypixelCommands.partyChat("pc Inquisitor dead!")
```suggestion
        HypixelCommands.partyChat("Inquisitor dead!")
```

2024-05-14 11:21 UTC, CalMWolfs approved these changes

2024-05-26 12:57 UTC, hannibal002 approved these changes

2024-05-26 12:57 UTC, merged