update SkilExpGainEvent
hannibal00212/SkyHanni pull request #1788
Opened 2024-05-13 14:34 UTC by superhize

## What
Update the SkillExpGainEvent to use SkilAPI data.

## Changelog Technical Details
+ SkillExpGainEvent now use SkillAPI data. - HiZe

2024-05-22 12:20 UTC, CalMWolfs requested changes

2024-05-22 12:20 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/api/SkillAPI.kt
> +        " (?<type>\\\\w+) (?<level>\\\\d+): §r§c§lMAX\$"
```suggestion
        " (?<type>\\w+) (?<level>\\d+): §r§c§lMAX"
```

2024-05-23 00:30 UTC, CalMWolfs approved these changes

2024-05-24 10:21 UTC, CalMWolfs requested changes

2024-05-24 10:21 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/api/SkillAPI.kt
> +                SkillExpGainEvent(skillType, matcher.group("gained").toDouble()).postAndCatch()
```suggestion
                SkillExpGainEvent(skillType, matcher.group("gained").formatDouble()).postAndCatch()
```

2024-05-29 02:22 UTC, CalMWolfs approved these changes

2024-05-30 23:35 UTC, hannibal002 approved these changes

2024-05-30 23:35 UTC, merged