Feature: reminder to open hoppity shop each year
hannibal00212/SkyHanni pull request #1843
Opened 2024-05-20 07:38 UTC by appable0

## What
Adds a chat reminder to open the Hoppity Shop each SkyBlock year (stored per-profile). Can be disabled by clicking, like other SkyHanni reminders.

_Note: untested; marking as draft until next Hoppity season_

<details>
<summary>Images</summary>
_will add images here once it's Hoppity_
</details>

## Changelog New Features
+ Chat reminder to check Hoppity Shop each year. - appable

2024-05-22 11:08 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityNpc.kt
> +        }
```suggestion
        get() = ChocolateFactoryAPI.profileStorage?.hoppityShopYearOpened ?: -1
        set(value) {
            ChocolateFactoryAPI.profileStorage?.hoppityShopYearOpened = value
        }
```

2024-05-24 07:53 UTC, CalMWolfs requested changes
didnt see this before but it appears it doesnt check if it is currently spring, so this reminder would send when the npc isnt available

2024-05-24 08:44 UTC, hannibal002 requested changes, later dismissed
reminder works fine for me (look at cals suggestion), the detecton to stop reminding me after opening the shop works fine.
generally, this pr reminded me to buy them from shop at all, so thanks for that

2024-05-24 08:44 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityNpc.kt
> +                ChatUtils.chat("§eReminders disabled.")
while not entirely necessary, please clarify what reminder is disabled.

2024-05-24 08:44 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityNpc.kt
> +            "New rabbits are available at §aHoppity's Shop§e! §c(Click to disable these reminders)",
maybe we should use singular form. there are not multiple different reminders that are about to get disabled, its just one reminder that repeats itself. (also this way its consistent with the wording of other reminders)

2024-05-24 08:44 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityNpc.kt
> +        hoppityYearOpened = SkyBlockTime.now().year
out of scope of this pr, but maybe we could add an annoying chat message that tells you how many years you have skipped/ the last year you have opened the shop before. that way we verbally punish non active users in a funny and non harmful way :)

2024-05-24 08:44 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
> +        public Integer hoppityShopYearOpened = -1;
integer = -1 feels rendundant. Either use int, or default to null.

2024-05-24 19:47 UTC, appable0 commented on src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityNpc.kt
> +        hoppityYearOpened = SkyBlockTime.now().year
I like this but I agree it's out of scope for now!

2024-05-24 19:50 UTC, appable0 commented on src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
> +        public Integer hoppityShopYearOpened = -1;
Changed to null, since coercing null to -1 was already handled by the getter/setter.

2024-05-26 01:59 UTC, CalMWolfs requested changes
just this one thing i think

2024-05-26 01:59 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityNpc.kt
> +        if (SkyblockSeason.getCurrentSeason() != SkyblockSeason.SPRING) return
```suggestion
        if (!ChocolateFactoryAPI.isHoppityEvent()) return
```

2024-05-26 07:11 UTC, CalMWolfs approved these changes

2024-05-29 07:42 UTC, merged