Feature: Custom Scoreboard Outside of SkyBlock
hannibal00212/SkyHanni pull request #1853
Opened 2024-05-21 08:53 UTC by j10a1n15

## What
This Pull Request adds the functionality to use the Custom Scoreboard outside of Hypixel, if it is added to the Dropdown. But there's a catch: You aren't able to use your own lines, it's just the normal outside lines + custom Title & Footer.
<details>
<summary>Images</summary>

![grafik](https://github.com/hannibal002/SkyHanni/assets/45315647/e3739ffa-611a-458b-be7e-2b92a06fa70d)
![grafik](https://github.com/hannibal002/SkyHanni/assets/45315647/0ac75207-adc8-4a78-b058-b0fec1226d62)

</details>

## Changelog New Features
+ Allow usage of Custom Scoreboard outside of SkyBlock. - j10a1n15

2024-05-21 13:26 UTC, martimavocado commented
nice skyblock title in bedwars

2024-05-21 13:32 UTC, ItsEmpa commented
if you use custom scoreboard title, it will show whatever you have as your custom scoreboard title

2024-05-21 13:32 UTC, j10a1n15 commented
> nice skyblock title in bedwars

Look they are able to change their title see same way they are able to do that in Skyblock, sooo

2024-05-21 13:55 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/CustomScoreboard.kt
> +            if (!LorenzUtils.inSkyBlock && OutsideSbFeature.CUSTOM_SCOREBOARD.isSelected()) dirty = true
```suggestion
            if (!LorenzUtils.inSkyBlock && !OutsideSbFeature.CUSTOM_SCOREBOARD.isSelected()) dirty = true
```

2024-05-22 10:54 UTC, CalMWolfs requested changes
Looked fine outside of skyblock apart for when removing it from the outside sb list, the scoreboard fully disapeared

2024-05-24 08:51 UTC, hannibal002 requested changes
not tested, not looked at code yet

i would prefer to have the custom title feature disabled while outside skyblock. Or maybe add a toggle to apply the custom title even outside skyblock.
otherwise users might think this is a bug.
Also look the wording of `Hypixel's Title Animation` toggle for this. this is reversed logic now. (no sb animation outside sb, still this toggle allows/activates the custom title outside sb)

2024-05-24 15:26 UTC, closed without merging