Fix: MobFilter Boss pattern
hannibal00212/SkyHanni pull request #1857
Opened 2024-05-21 16:17 UTC by Thunderblade73

## What
Fixes the boss patterm for the mob detection to work with thunder and magma boss correctly

## Changelog Technical Details
+ Fixed Boss Pattern from MobFilter. - Thunderblade73

2024-05-22 10:43 UTC, CalMWolfs approved these changes

2024-05-24 09:29 UTC, hannibal002 requested changes
The existing regex already catches `﴾ [Lv400] Thunder 29M/35M❤ ﴿` just fine. [regex101](https://regex101.com/?regex=%5E.+%28%3F%3A%5C%5BLv%28%3F%3Clevel%3E%5Cd%2B%29%5C%5D+%29%3F%28%3F%3Cname%3E%5B%5E%E1%9B%A4%0A%5D*%29%28%3F%3A+%E1%9B%A4%29%3F%28%3F%3A+%5B%5Cd%5C%2FBMk.%2C%E2%9D%A4%5D%2B%7C%E2%96%88%2B%29%3F+.%24&testString=%EF%B4%BE+Storm+%EF%B4%BF%0A%EF%B4%BE+%5BLv200%5D+aMage+Outlawa+70M%2F70M%E2%9D%A4+%EF%B4%BF%0A%EF%B4%BE+%5BLv500%5D+Magma+Boss+%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88+%EF%B4%BF%0A%EF%B4%BE+%5BLv200%5D+Bladesoul+50M%2F50M%E2%9D%A4+%EF%B4%BF%0A%EF%B4%BE+%5BLv300%5D+Arachne+20%2C000%2F20%2C000%E2%9D%A4+%EF%B4%BF%0A%EF%B4%BE+%5BLv500%5D+Arachne+100k%2F100k%E2%9D%A4+%EF%B4%BF%0A%EF%B4%BE+%5BLv200%5D+Barbarian+Duke+X+70M%2F70M%E2%9D%A4+%EF%B4%BF%0A%EF%B4%BE+%5BLv100%5D+Endstone+Protector+4.6M%2F5M%E2%9D%A4+%EF%B4%BF%0A%EF%B4%BE+%5BLv400%5D+Thunder+29M%2F35M%E2%9D%A4+%EF%B4%BF)

2024-05-24 09:33 UTC, CalMWolfs commented
> The existing regex already catches `﴾ [Lv400] Thunder 29M/35M❤ ﴿` just fine. [regex101](https://regex101.com/?regex=%5E.+%28%3F%3A%5C%5BLv%28%3F%3Clevel%3E%5Cd%2B%29%5C%5D+%29%3F%28%3F%3Cname%3E%5B%5E%E1%9B%A4%0A%5D*%29%28%3F%3A+%E1%9B%A4%29%3F%28%3F%3A+%5B%5Cd%5C%2FBMk.%2C%E2%9D%A4%5D%2B%7C%E2%96%88%2B%29%3F+.%24&testString=%EF%B4%BE+Storm+%EF%B4%BF%0A%EF%B4%BE+%5BLv200%5D+aMage+Outlawa+70M%2F70M%E2%9D%A4+%EF%B4%BF%0A%EF%B4%BE+%5BLv500%5D+Magma+Boss+%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88%E2%96%88+%EF%B4%BF%0A%EF%B4%BE+%5BLv200%5D+Bladesoul+50M%2F50M%E2%9D%A4+%EF%B4%BF%0A%EF%B4%BE+%5BLv300%5D+Arachne+20%2C000%2F20%2C000%E2%9D%A4+%EF%B4%BF%0A%EF%B4%BE+%5BLv500%5D+Arachne+100k%2F100k%E2%9D%A4+%EF%B4%BF%0A%EF%B4%BE+%5BLv200%5D+Barbarian+Duke+X+70M%2F70M%E2%9D%A4+%EF%B4%BF%0A%EF%B4%BE+%5BLv100%5D+Endstone+Protector+4.6M%2F5M%E2%9D%A4+%EF%B4%BF%0A%EF%B4%BE+%5BLv400%5D+Thunder+29M%2F35M%E2%9D%A4+%EF%B4%BF)
> 
> either the regex test is wrong, or there is another problem i dont see

old pattern (wrong)
![image](https://github.com/hannibal002/SkyHanni/assets/94038482/bf9c9d8c-1b19-4bb8-82f0-af084ddfd91e)

new pattern (correct)
![image](https://github.com/hannibal002/SkyHanni/assets/94038482/4cf01a05-cd18-4870-bddc-388acd71b027)

2024-05-24 09:39 UTC, Thunderblade73 commented
The problem is that it does not separate the name and the health which is bad.

2024-05-24 11:42 UTC, hannibal002 approved these changes
Is this a user-facing bug? If so, please use better wording without technical terms in the changelog, if it's not user facing, please change it to internal change.

2024-05-24 11:42 UTC, merged

2024-05-24 15:29 UTC, Thunderblade73 commented
It is not a user facing bug, since this is only the internal value to identify the mob.