Technical: Add dungeon phases
hannibal00212/SkyHanni pull request #1865
Opened 2024-05-22 20:08 UTC by martimavocado

## What
Adds dungeon phase detection

## Changelog Technical Details
+ Added dungeon phase detection. - martimavocado

2024-05-22 20:44 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonAPI.kt
> +    enum class DungeonPhase {
you can embed the patterns directly into the enum. Look at Skyblock Guide Highlight as an example of how (Not a good example but the first that came to mind)

2024-05-23 05:47 UTC, catgirlseraid commented
change phasePatternGroup to patternGroup 🥺

2024-05-23 18:07 UTC, martimavocado commented
> change phasePatternGroup to patternGroup 🥺

there's already a `patternGroup` though do i just make `phasePatternGroup` a subgroup inside `patternGroup`? or i could just add `boss.message` to every key in the new patterns i added and ditch `phasePatternGroup`

2024-06-16 09:10 UTC, hannibal002 requested changes
please add regex tests to all patterns

2024-06-16 20:14 UTC, martimavocado commented
> please add regex tests to all patterns

is there a point in doing this for most of these patterns? only one isn't checking for an exact string. i don't mind doing this, just curious as to why

2024-10-09 11:09 UTC, hannibal002 requested changes
Please move the code from DungeonAPI into a new class DungeonBossAPI or similar, and change the name of the event and the enum to indlicate that this is not the dungeon phase but the boss phase.

2024-10-11 17:54 UTC, hannibal002 requested changes
the phase doesnt reset to null after leaving dungeon

2024-10-11 19:04 UTC, hannibal002 approved these changes

2024-10-11 19:04 UTC, merged