Technical: Add a progress bar with multiple colors renderable
hannibal00212/SkyHanni pull request #1867
Opened 2024-05-23 02:34 UTC by martimavocado

## Dependencies
- pr_number_or_link_here

## What
Describe what this pull request does, including technical details, screenshots, links to discord, etc.

<details>
<summary>Images</summary>

</details>

## Changelog New Features
+ Cool new feature. - your_name_here
    * extra info

## Changelog Improvements
+ Improved cool feature. - your_name_here
    * Extra info.

## Changelog Fixes
+ Fixed cool feature. - your_name_here
    * Extra info.

## Changelog Technical Details
+ Something technical you changed in the backend. - your_name_here
    * Extra info.

## Changelog Removed Features
+ Removed cool feature. - your_name_here
    * Extra info.

2024-06-20 21:23 UTC, hannibal002 requested changes

2024-06-20 21:23 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
> +            override fun render(posX: Int, posY: Int) {
move this 90 lines class into utils, or extract into smaller functions

2024-06-20 21:23 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/renderables/Renderable.kt
> +        data class ColorRange(
We should move this class maybe

2025-07-12 23:09 UTC, CalMWolfs commented
@martimavocado are you planning on updating this pr or can I close it

2025-11-27 01:29 UTC, NopoTheGamer commented
reopen if you want to work on it again :)

2025-11-27 01:29 UTC, closed without merging