Feature: Pet Nametag
hannibal00212/SkyHanni pull request #1880
Opened 2024-05-24 15:41 UTC by j10a1n15

## Dependencies
- #1687 

## What
Adds options to modify the look of pet nametags, like removing the player name, or hiding the level of the pet.

<details>
<summary>Images</summary>

![image](https://github.com/hannibal002/SkyHanni/assets/42304516/7543dc49-6b96-4688-ac9b-be083eb97a11)

</details>

## Changelog New Features
+ Added option to Hide Pet Nametag Text. - Empa,  j10a1n15

2024-05-26 16:09 UTC, qtlunya commented
You aren't gonna guess what's on alpha right now...
![image](https://github.com/hannibal002/SkyHanni/assets/148620615/7e48062a-f908-46f2-ab35-83073e841fc8)

2024-06-05 04:03 UTC, CalMWolfs requested changes
Hiding the level worked for me, the hiding only maxed levels did not work, it only showed max leveled pets levels and hid all the other ones.

2024-06-05 04:03 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/misc/pets/PetNametag.kt
> +        "feature.pet.nametag",
feature feels weird as the start of the pattern key

2024-06-05 04:03 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/misc/pets/PetNametag.kt
> +        "(?<start>§8\\[§7Lv(?<lvl>\\d+)§8\\]) (?<rarity>§.)(?<pet>[\\w\\s]+)(?<skin>§. ✦)?"
not super important but 
Redundant character escape '\\]' in RegExp

2024-06-05 04:03 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/misc/pets/PetNametag.kt
> +    private val pattern by RepoPattern.pattern(
while there is only one pattern is probably better to name the variable something more than just pattern

2024-06-05 04:03 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/misc/pets/PetNametag.kt
> +    }
should check if in skyblock first, also im not sure if we need to be doing with(config) as we could do it the way its done everywhere else, but thats up to you

2024-06-05 04:03 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/data/EntityData.kt
> -    private fun postRenderNametag(entity: Entity, chatComponent: IChatComponent) = nametagCache.getOrPut(entity) {
not sure why this changed

2024-06-05 04:03 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinEntity.java
> -        EntityData.getDisplayName((Entity) (Object) this, ci);
not sure why this changed x2

2024-06-05 04:03 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/mixins/transformers/MixinEntityPlayer.java
> -        EntityData.getDisplayName((EntityPlayer) (Object) this, ci);
not sure why this changed x3

2024-06-05 04:03 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/features/misc/pets/PetNametagConfig.java
both of these should be next to the pet instead of above

2024-06-05 04:30 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/data/EntityData.kt
> -    private fun postRenderNametag(entity: Entity, chatComponent: IChatComponent) = nametagCache.getOrPut(entity) {
The old system only allowed to add onto the Entity Nametag, while this new one allows a full replacement.
Not sure why Empa didn't just change it in their original pr

2024-06-05 07:47 UTC, ThatGravyBoat requested changes

2024-06-05 07:47 UTC, ThatGravyBoat commented on src/main/java/at/hannibal2/skyhanni/data/EntityData.kt
> -    private fun postRenderNametag(entity: Entity, chatComponent: IChatComponent) = nametagCache.getOrPut(entity) {
it already allowed full replacement its just all the logic was in the hook, ie. EntityData you seemed to have moved this logic into the mixin, please revert the changes to this class and both mixins as it does the exact same thing.

2024-06-05 15:48 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/config/features/misc/pets/PetNametagConfig.java
I have no idea what this means

2024-06-06 04:40 UTC, CalMWolfs approved these changes

2024-09-11 11:56 UTC, merged