Add: Change lava color
hannibal00212/SkyHanni pull request #1885
Opened 2024-05-24 22:08 UTC by superhize

## What
Change lava color instead of using a ressourcepack.

<details>
<summary>Images</summary>

</details>

## Changelog New Features
+ Change lava color. - HiZe
    * Mainly used for lava fishing in the Crimson Isle, but can be used everywhere else if the option is enabled.

2024-06-01 05:40 UTC, CalMWolfs requested changes
Also idk what sbe does for this but does it also work with sbe as redirects can be incompatible

2024-06-01 05:40 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/features/fishing/LavaReplacementConfig.java
> +    public boolean onlyInCrimsonIsle = false;
i feel this should be default true

2024-06-01 10:51 UTC, superhize commented
> Also idk what sbe does for this but does it also work with sbe as redirects can be incompatible

It conflict with sbe, that's why I set a higher priority

2024-06-01 10:55 UTC, CalMWolfs commented
> > Also idk what sbe does for this but does it also work with sbe as redirects can be incompatible
> 
> It conflict with sbe, that's why I set a higher priority

resolved in my commit

2024-06-01 13:00 UTC, CalMWolfs approved these changes
worked for me (also https://github.com/NotEnoughUpdates/NotEnoughUpdates/pull/1194 fixes a small issue with it)

2024-09-07 18:12 UTC, hannibal002 requested changes

2024-09-07 18:12 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/fishing/LavaReplacementConfig.java
> +    public Runnable loadListeners = Minecraft.getMinecraft().renderGlobal::loadRenderers;
please use config reload event and properties when `enabled/only on crimson` values change so that this button becomes unnecessary

2024-10-08 03:11 UTC, CalMWolfs requested changes

2024-10-08 03:11 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/mixins/hooks/BlockFluidRendererHook.kt
All the code in this hook could be put straight into LavaReplacement.kt instead

2024-10-11 03:26 UTC, CalMWolfs approved these changes

2024-10-11 16:32 UTC, hannibal002 approved these changes

2024-10-11 16:33 UTC, merged