Fix: Scoreboard not showing player count in dungeons
hannibal00212/SkyHanni pull request #1894
Opened 2024-05-25 21:30 UTC by ThatGravyBoat

## What
Fixes that in dungeons the players title is replaced with a party title

## Changelog Fixes
+ Fixed scoreboard player count not showing in dungeons. - ThatGravyBoat

2024-05-25 21:32 UTC, qtlunya commented
In theory, couldn't this be wrong if some of the party members leave the dungeon during the run?

2024-05-25 21:43 UTC, ThatGravyBoat commented
> In theory, couldn't this be wrong if some of the party members leave the dungeon during the run?

it updates accordingly, when I tested someone disconnected so that should mean its the same for someone just doing /hub or something

2024-05-26 01:41 UTC, CalMWolfs approved these changes
worked

2024-05-26 11:26 UTC, hannibal002 requested changes
worked fine for me

2024-05-26 11:26 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
> +        private val dungeonPartyAmountPattern by patternGroup.pattern(
please add regex test

2024-05-26 12:08 UTC, hannibal002 approved these changes

2024-05-26 12:08 UTC, merged