Feature: Moveable and Scaleable Hotbar
hannibal00212/SkyHanni pull request #1903
Opened 2024-05-27 19:06 UTC by Thunderblade73

## What
Adds the hotbar to the gui editor. Will conflict with mods like Apec.
Has no fancy alignment, it is handle like every other gui element. I wouldn't rather add that option to all gui elements then specifically to that feature

<details>
<summary>Images</summary>

![image](https://github.com/hannibal002/SkyHanni/assets/85900443/16c17421-69c5-44f1-9edc-57be18f5bb9d)
![image](https://github.com/hannibal002/SkyHanni/assets/85900443/0dd62354-978e-4410-b333-95b4d37dfb93)
![image](https://github.com/hannibal002/SkyHanni/assets/85900443/de77b8bd-caab-48b8-9dbf-b5f6b4faa7ab)

</details>

## Changelog New Features
+ Editable Hotbar. - Thunderblade73
  * Allows for moving and scaling in the gui editor

2024-05-28 12:24 UTC, CalMWolfs requested changes
feature works fine, just a bit of code cleanup. 
Additionally, right now it defaults to the top left corner which I get why that is done but something that could be really cool is when turning on the feature for the first time (by checking if the position is set to the default position) it would calculate the current hotbar position and set its position to there, not necessary but would be cool

2024-05-28 12:24 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/features/gui/HotbarConfig.java
> +    @ConfigOption(name = "Show Outside Skyblock", desc = "Enables the hotbar to be edited even outside of skyblock.")
```suggestion
    @ConfigOption(name = "Show Outside Skyblock", desc = "Enables the hotbar to be edited even outside of SkyBlock.")
```

2024-05-28 12:24 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/gui/MovableHotBar.kt
> +    fun isEnabled(): Boolean = config.editable && (config.showOutsideSkyblock || LorenzUtils.inSkyBlock)
I feel generally in the codebase this isEnabled function is at the bottom of the file

2024-05-29 21:42 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/gui/MovableHotBar.kt
> +    fun isEnabled(): Boolean = config.editable && (config.showOutsideSkyblock || LorenzUtils.inSkyBlock)
ive fixed it

2024-05-29 21:42 UTC, hannibal002 approved these changes

2024-05-29 21:42 UTC, merged