Backend: Auto load annotation
hannibal00212/SkyHanni pull request #1904
Opened 2024-05-28 09:26 UTC by CalMWolfs

## What
Added annotation to automatically load modules

Add to any module that has a repo pattern or receives subscribe events

This is just the first part of this, I only load one module so that the changelog only contains stuff useful to this annotation, but I've tested with all files and it works fine.
This only works with Kotlin Objects, a later pr will convert all the feature classes to objects and add the annotation to them. This means all future features should be made in Kotlin Objects, not Classes.
There will also be a live plugin related to this annotation, but that will come once I start adding the annotation to more things.

I also made it crash when you load the same module twice (if you add the annotation and forget to remove it from load module)

## Changelog Technical Details
+ Added annotation to automatically load modules. - CalMWolfs
    * Just add the @SkyHanniModule annotation to an object to auto load it.

2024-05-29 02:02 UTC, ThatGravyBoat requested changes

2024-05-29 02:02 UTC, ThatGravyBoat commented on annotation-processors/src/main/kotlin/at/hannibal2/skyhanni/skyhannimodule/ModuleProcessor.kt
> +            logger.error("@LoadModule is only valid on class declarations", symbol)
```suggestion
            logger.error("@SkyHanniModule is only valid on class declarations", symbol)
```

2024-05-29 02:02 UTC, ThatGravyBoat commented on annotation-processors/src/main/kotlin/at/hannibal2/skyhanni/skyhannimodule/ModuleProcessor.kt
> +            logger.error("@LoadModule is only valid on kotlin objects", symbol)
```suggestion
            logger.error("@SkyHanniModule is only valid on kotlin objects", symbol)
```

2024-05-29 02:13 UTC, ThatGravyBoat approved these changes

2024-06-01 10:45 UTC, hannibal002 approved these changes
works for me

2024-06-01 10:47 UTC, merged