Improvement: Updated Contest Summary
hannibal00212/SkyHanni pull request #1924
Opened 2024-05-29 19:05 UTC by ILike2WatchMemes

## What
Updated "Contest Summary" to allow users to change
- when a BPS is good, okay or bad.
- which color a good, okay or bad BPS has.

## Changelog Improvements
+ Updated Contest Summary. - ILike2WatchMemes
    * Allows user to change when a BPS is good, okay or bad.
    * Allows user to choose which color a good, okay or bad BPS has.

2024-05-29 22:47 UTC, Obsidianninja11 commented on src/main/java/at/hannibal2/skyhanni/config/features/garden/ContestSummaryConfig.java
> +        name = "Ênabled",
```suggestion
        name = "Enabled",
```
This has an accented E

2024-05-29 22:51 UTC, Obsidianninja11 commented
I feel like this is sort of complicated for such an unnoticeable feature.
In [my pr](https://github.com/hannibal002/SkyHanni/pull/839), I just made the color statically red.

2024-05-29 23:46 UTC, ILike2WatchMemes commented
> I feel like this is sort of complicated for such an unnoticeable feature. In [my pr](https://github.com/hannibal002/SkyHanni/pull/839), I just made the color statically red.

although I do agree with the fact that this is an rather unnoticeable feature, I do feel like people always appreciate the access to customization

2024-06-05 01:00 UTC, CalMWolfs requested changes
missing a config fix event meaning if the user had jacobContestSummary disabled before it would re-enable now

2024-06-09 12:50 UTC, ILike2WatchMemes commented
> missing a config fix event meaning if the user had jacobContestSummary disabled before it would re-enable now

how does one do that, had a lot going on with school so sorry for late reply

2024-06-09 13:05 UTC, CalMWolfs commented
> > missing a config fix event meaning if the user had jacobContestSummary disabled before it would re-enable now
> 
> how does one do that, had a lot going on with school so sorry for late reply

You'd need to increase the config version by 1 in ConfigUpdaterMigrator

Then add a function like this 
```kt
    @SubscribeEvent
    fun onConfigFix(event: ConfigUpdaterMigrator.ConfigFixEvent) {
        event.move(newVersion, old config location, new config location)
    }
    ```
    
    If you need help determining the old and new paths or anything lmk

2024-06-27 17:23 UTC, ILike2WatchMemes commented
like this?

2025-07-12 23:14 UTC, CalMWolfs commented
@ILike2WatchMemes are you planning on updating this pr or can I close it

2025-07-20 17:13 UTC, ILike2WatchMemes commented
> @ILike2WatchMemes are you planning on updating this pr or can I close it

I'll close it, doesn't strike me as a priority feature

2025-07-20 17:13 UTC, closed without merging