Feature: Default amount for /gfs with no args
hannibal00212/SkyHanni pull request #1927
Opened 2024-05-29 19:44 UTC by saga-00

## What
Adds default amount for /gfs in case of no args. The default amount can be changed.
## Changelog New Features
+ Added Default GfS toggle and Default Amount GfS slider - saga
    * Works for Item ID, Item name and Item name with _

2024-05-29 19:57 UTC, Thunderblade73 requested changes
Not a bad approach. Needs some small fixing but than it should work. But it only works when the queued gfs is turned on. So I would advice to do a similar approach, of just adding the number if it doesn't find the number, but as it's own handler. Something like Line 127. (Btw. the number adding should happen before handleUnderlineReplace)

2024-05-29 19:57 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/api/GetFromSackAPI.kt
> +        val argsNull = args.last().toIntOrNull() == null
this could work for the calculate issue
```suggestion
        val argsNull = args.last().last().toString().toIntOrNull() == null
```

2024-05-29 19:57 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/api/GetFromSackAPI.kt
> +        var item = when {
this is still a val not a var

2024-05-29 19:57 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/api/GetFromSackAPI.kt
> +            SackAPI.sackListNames.contains(itemString) -> NEUInternalName.fromItemNameOrNull(itemString)
this call is a sub set of the next calling. TLDR: can be removed.

2024-05-29 19:58 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/api/GetFromSackAPI.kt
> +        val argsNull = args.last().toIntOrNull() == null
Actually idk if String supports .last() . Nevertheless it isn't that hard to implement

2024-05-29 20:18 UTC, Thunderblade73 requested changes

2024-05-29 20:18 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/api/GetFromSackAPI.kt
> +            arguments.add(config.defaultAmountGFS.toString())
Same thing, but without a mutable list
```suggestion
       val argsNull =  args.last().last().toString().toIntOrNull() == null
        val arguments = if(argsNull){
           if (!config.defaultGFS) return CommandResult.WRONG_ARGUMENT to null
           args + config.defaultAmountGFS.toString()
        } else {
          args
```

2024-05-29 20:21 UTC, Thunderblade73 requested changes

2024-05-29 20:21 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/api/GetFromSackAPI.kt
> +
this move isn't needed anymore. It can stay where it was

2024-05-29 20:21 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/GetFromSackConfig.java
> +    @ConfigOption(name = "Default GfS", desc = "If you don't provide an amount, a default one will be used instead.")
Please correct my bad writing, but add something like that.
```suggestion
    @ConfigOption(name = "Default GfS", desc = "If you don't provide an amount, a default one will be used instead. Queued Gfs needs to be turned on for this to work.")
```

2024-05-29 20:36 UTC, Thunderblade73 approved these changes

2024-08-26 10:09 UTC, merged

2024-08-27 09:28 UTC, hannibal002 commented
entirely rewrote the changelog