Feature: mark duplicate egg locations
hannibal00212/SkyHanni pull request #1929
Opened 2024-05-29 22:10 UTC by appable0

## What
Marks duplicate egg locations in red when located using the Egglocator, Shared Egg Waypoints, or the Show All Waypoints feature. There is also an option to always mark nearby duplicate egg locations (within 10 blocks) in red.

<details>
<summary>Images</summary>
![2024-05-29_15 04 06](https://github.com/hannibal002/SkyHanni/assets/16139460/a8707bf7-a65b-4b3c-8836-52b3bfe47c88)

</details>

## Changelog New Features
+ Mark duplicate egg locations in red for unlocking some of the new rabbits. - appable
    * Option to always mark nearby duplicate egg locations.

2024-05-29 23:13 UTC, CalMWolfs requested changes
Feature works completely fine, just a few things I noticed.

2024-05-29 23:13 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityUniqueEggLocations.kt
some unused imports in here

2024-05-29 23:13 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityUniqueEggLocations.kt
> +            """.trimIndent())
This should probably be an ErrorManager.skyHanniError so we get data about this

2024-05-29 23:13 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/features/event/HoppityEggsConfig.java
> +    @ConfigOption(name = "Highlight Duplicate Egg Locations in Red", desc = "Marks egg locations which you have already found in red.")
This config option name is too long, maybe just Highlight Duplicate Eggs.

2024-05-29 23:13 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/features/event/HoppityEggsConfig.java
> +    @ConfigOption(name = "Show Nearby Duplicate Egg Locations", desc = "Always show duplicate eggs when nearby.")
Same here, the name is too long

2024-05-30 04:00 UTC, appable0 commented on src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityUniqueEggLocations.kt
I'm positive I enabled optimize imports months ago! Fixed now, hopefully...

2024-05-30 06:56 UTC, hannibal002 approved these changes

2024-05-30 06:56 UTC, merged