Backend: Replace round and roundToDecimals with roundTo
hannibal00212/SkyHanni pull request #1931
Opened 2024-05-30 03:49 UTC by CalMWolfs

## What
Replace round and roundToDecimals with roundTo.

## Changelog Technical Details
+ Remove there being two different rounding functions. - CalMWolfs

2024-06-03 12:17 UTC, ThatGravyBoat approved these changes

2024-06-12 16:19 UTC, hannibal002 requested changes
<details>
<summary>Breaks on high rounding values</summary>


![image](https://github.com/hannibal002/SkyHanni/assets/24389977/456e5be6-3ae5-4b34-8243-ee5a0d135908)
![image](https://github.com/hannibal002/SkyHanni/assets/24389977/dd87243a-d9cd-458a-a83f-71d84a955d70)
![image](https://github.com/hannibal002/SkyHanni/assets/24389977/573461b4-74b1-4845-9699-92d7b3e65909)

https://play.kotlinlang.org/#eyJ2ZXJzaW9uIjoiMS45LjI0IiwicGxhdGZvcm0iOiJqYXZhIiwiYXJncyI6IiIsIm5vbmVNYXJrZXJzIjp0cnVlLCJ0aGVtZSI6ImlkZWEiLCJjb2RlIjoiLyoqXG4gKiBZb3UgY2FuIGVkaXQsIHJ1biwgYW5kIHNoYXJlIHRoaXMgY29kZS5cbiAqIHBsYXkua290bGlubGFuZy5vcmdcbiAqL1xuaW1wb3J0IGtvdGxpbi5tYXRoLnBvd1xuaW1wb3J0IGtvdGxpbi5tYXRoLnJvdW5kVG9JbnRcblxuICAgIGZ1biBEb3VibGUucm91bmRUbyhwcmVjaXNpb246IEludCk6IERvdWJsZSB7XG4gICAgICAgIHZhbCBzY2FsZSA9IDEwLjAucG93KHByZWNpc2lvbikudG9JbnQoKVxuICAgICAgICByZXR1cm4gKHRoaXMgKiBzY2FsZSkucm91bmRUb0ludCgpLnRvRG91YmxlKCkgLyBzY2FsZVxuICAgIH1cblxuZnVuIG1haW4oKSB7XG4gICAgdmFsIHJlc3VsdCA9IC0xMTUuMTIzNDU2Ny5yb3VuZFRvKDEwKVxuICAgIHByaW50KHJlc3VsdClcbn0ifQ==

</details>

2024-06-12 16:19 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/GardenYawAndPitch.kt
> +        val yawText = yaw.roundTo(config.yawPrecision).toBigDecimal().toPlainString()
the change breaks here

2024-06-12 16:19 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
> -        return if (a.length > b.length) this else result
removing this workaround breaks stuff

2024-09-16 02:57 UTC, CalMWolfs commented
> Breaks on high rounding values

fixed: https://pl.kotl.in/FBDmugW6X

2024-09-23 15:16 UTC, merged