Feature: Professor Robot Component Helper
hannibal00212/SkyHanni pull request #1933
Opened 2024-05-30 07:02 UTC by saga-00

## What
Gives you a shortcut for bazaar (or sack) when you are missing the component asked by Professor Robot. I can't properly test the Sack usage of this feature, sadly.
## Changelog New Features
+ Professor Robot Shortcut. - saga
    * Gives you a clickable message, which redirects you to Bazaar for the item missing.
    * You can make it so the clickable message gets the component from your Crystal Hollows Sack instead.

2024-05-30 07:13 UTC, Thunderblade73 requested changes

2024-05-30 07:13 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsProfessorRobot.kt
> +        ChatUtils.clickableChat("Click here to grab an §r§9$itemName!", onClick = {
Use the GetFromSack api here instead. GetFromSackAPI.getFromChatMessageSackItems

2024-05-30 07:13 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsProfessorRobot.kt
> +    private val robotParts = listOf(
make it a set instead of a list. Since contains perform on average better on sets than lists.

2024-05-30 07:13 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsProfessorRobot.kt
> +    private val pattern = "\\[NPC\\] Professor Robot: That's not one of the components I need! Bring me one of the missing components:".toRegex()
Use a RepoPattern instead. (The key only needs to be unique and somewhat give the direction on what it is)
```suggestion
    private val pattern = RepoPattern.pattern(
    "mining.robot.missing.gfs"
    "\\[NPC\\] Professor Robot: That's not one of the components I need! Bring me one of the missing components:".
    )
```

2024-05-30 07:13 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsProfessorRobot.kt
> +        val itemName = event.message.removeColor().removePrefix("  ")
```suggestion
        val itemName = event.message.removeColor().trimStart()
```

2024-05-30 07:13 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsProfessorRobot.kt
> +        if (event.message.removeColor().matches(pattern)) {
save the removeColor here. 
```suggestion
       val cleanMessage = event.message.removeColor()
        if (cleanMessage matches(pattern)) {
```

2024-05-30 07:13 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsProfessorRobot.kt
> +            else HypixelCommands.bazaar(itemName)
This will be handelt via the Gfs bazaar feature. So I don't really see why to use this.

2024-05-30 07:46 UTC, Thunderblade73 requested changes

2024-05-30 07:46 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsProfessorRobot.kt
> +    private var robotMessage = false
I don't see the need for this variable. Since you simply can return if not matches

2024-05-30 07:46 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/config/features/mining/ProfessorRobotConfig.java
> +    public boolean sack = false;
The config doesn't make any sense now.

2024-05-30 08:04 UTC, Thunderblade73 requested changes

2024-05-30 08:04 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsProfessorRobot.kt
> +        val itemName = event.message.removeColor().trimStart()
```suggestion
        val itemName = cleanMessage.trimStart()
```

2024-05-30 08:09 UTC, Thunderblade73 approved these changes

2024-06-05 01:06 UTC, CalMWolfs requested changes

2024-06-05 01:06 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsProfessorRobot.kt
> +    fun isEnabled() = IslandType.CRYSTAL_HOLLOWS.isInIsland() && SkyHanniMod.feature.mining.professorRobotHelper;
```suggestion
    fun isEnabled() = IslandType.CRYSTAL_HOLLOWS.isInIsland() && SkyHanniMod.feature.mining.professorRobotHelper
```

2024-06-05 01:06 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsProfessorRobot.kt
> +class CrystalHollowsProfessorRobot {
should be an object and have the @SkyHanniModule annotation and then the loadModule should be removed from SkyHanniMod

2024-10-21 09:15 UTC, jani270 commented
Closing as https://wiki.hypixel.net/Precursor_Apparatus exists now

2024-10-21 09:15 UTC, closed without merging