Feature: Golden Fish Timer
hannibal00212/SkyHanni pull request #1941
Opened 2024-05-30 13:51 UTC by ItsEmpa

## What
Adds a Golden Fish Timer, with info on how long it has been since the last rod, time until you can spawn one, etc.
Also adds options to, for example, show certain info as a nametag on top of the golden fish, highlight it when its ready and give a warning when you are close to the time limit of throwing rod.

<details>
<summary>Images</summary>

![image](https://github.com/hannibal002/SkyHanni/assets/42304516/bf301c48-aadd-4e12-9e28-4fe700ffb071)
![image](https://github.com/hannibal002/SkyHanni/assets/42304516/0b8600fe-558a-49e5-9352-1c47b57faff6)

</details>

## Changelog New Features
+ Added Golden Fish Timer. - Empa
    * Includes options like a warning for when to throw your rod, showing how weak the golden fish as a nametag, etc.

2024-05-30 22:59 UTC, CalMWolfs requested changes
code looks good just this one thing

2024-05-30 22:59 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/fishing/trophy/GoldenFishTimer.kt
> +    private val group = RepoPattern.group("fishing.goldenfish")
should probably be called patternGroup for consistency with the rest of the mods code

2024-05-31 12:37 UTC, CalMWolfs approved these changes

2024-08-26 13:22 UTC, hannibal002 commented
idk what i am doing wrong. either the 3 minutes delay are wrong. or you need to fish something, not throw the rod in. 
![image](https://github.com/user-attachments/assets/7c317bc0-199b-4b33-aa6f-f9a5ef7e1465)

2024-08-26 13:23 UTC, ItsEmpa commented
i think the most likely reason is that the detection for wheter or not something actually counts as throwing rod is really weird

2024-08-26 20:05 UTC, hannibal002 commented
oje
![image](https://github.com/user-attachments/assets/1cdecce0-c9cf-403b-a211-20dd45691cf0)

2024-09-04 09:14 UTC, hannibal002 requested changes
Does not work for me.

2024-09-10 21:23 UTC, hannibal002 approved these changes

2024-09-10 21:23 UTC, merged