Improvement: Barn Fishing Timer
hannibal00212/SkyHanni pull request #1960
Opened 2024-05-31 07:30 UTC by ItsEmpa

## What
Refactors Barn Fishing Timer to use MobDetection, adds a warning for when you reach a certain amount of sea creatures, and makes the time actually based on the time each mob has existed for instead of the time the timer has been active for.

## Changelog Improvements
+ Improved Barn Fishing Timer. - Empa
    * Also adds a warning when reaching a certain amount of sea creatures.

2024-07-10 13:58 UTC, ItsEmpa commented
the scope of this pr has changed to also implement the sea creature cap changes added by hypixel

2024-07-26 08:30 UTC, hannibal002 requested changes
i dont understand why we process magma slugs differently. also the custom handlinb of fishing mobs should maybe get moved into another api class, so that only the count and add logic remains in this class. (extract complexitiy that might be duplicated in future other features into abstract classes early)

2024-07-26 08:30 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/fishing/FishingTimer.kt
> +    private val mobMap = mutableMapOf<Mob, SimpleTimeMark>()
what does the value represent? please use a more descriptive name for the map

2024-07-26 08:30 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/fishing/FishingTimer.kt
> +    private fun handleBabySlugs() {
why do we need to handle baby slugs differently? can this get moved to mob detection?

2024-07-26 08:30 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/fishing/FishingTimer.kt
> +        val text = createDisplay()
Don't create the text each frame. rather only 10 times a second and cache the display string.

2024-07-26 08:30 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/fishing/FishingTimer.kt
> +        val countColor = if (config.fishingCapAlert && currentCount >= currentCap.getValue()) "§c" else "§e"
getValue() is deprecated

2024-07-26 11:02 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/fishing/FishingTimer.kt
> +    private fun handleBabySlugs() {
discussed on discord

2024-07-26 11:02 UTC, hannibal002 approved these changes

2024-07-26 11:02 UTC, merged