Feature: Snake Game Keybinds
hannibal00212/SkyHanni pull request #1968
Opened 2024-05-31 18:38 UTC by j10a1n15

## What
This Pull Request adds WASD Keybind support to the silly snake game.

## Changelog New Features
+ Added WASD Keybinds to the AbiPhone SnakeGame. - j10a1n15

2024-06-01 00:06 UTC, CalMWolfs requested changes
could we instead use the player's minecraft keybinds instead of hard coding wasd

2024-10-08 08:05 UTC, CalMWolfs approved these changes
couldnt test but code looks fine

2024-10-20 11:43 UTC, hannibal002 requested changes
Also maybe make the keys cache on inventory open, so that we dont need to create the map every tick time.
I just assume the user cant change their keybinds without leaving the inventory

2024-10-20 11:43 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
> +    @ConfigOption(name = "Snake Game Keybinds", desc = "Use WASD to move around in the AbiPhone snake game.")
Hypixels spelling is with a lowercal `p`

2024-10-20 11:43 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
> +    @ConfigOption(name = "Snake Game Keybinds", desc = "Use WASD to move around in the AbiPhone snake game.")
maybe use `WASD-keys`

2024-10-20 11:43 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/SnakeGame.kt
> +    private val pattern by RepoPattern.pattern("snake.name", "Snake")
better key

2024-10-20 11:43 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/SnakeGame.kt
> +    private val mcConfig
remove line break

2024-10-20 11:43 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/SnakeGame.kt
> +    private val keys
again remove line break

2024-10-20 11:43 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/SnakeGame.kt
> +            mcConfig.keyBindLeft.keyCode to 50,
if mcConfig is only used in here, use a local variable instead

2024-10-20 11:43 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/SnakeGame.kt
> +        if (!pattern.matches(InventoryUtils.openInventoryName())) return
check the inventory name on inventory open, not every tick. cache into a inInventory variable

2024-10-20 11:43 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/SnakeGame.kt
> +            if (key.isKeyHeld()) {
early return

2024-10-20 11:43 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/SnakeGame.kt
> +                Minecraft.getMinecraft().playerController.windowClick(
it starts getting time for a utils function for windowClick. maybe outside of this pr though

2024-10-20 17:13 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/SnakeGame.kt
> +    private val keys
intellij auto formatting keeps setting a line break here

2024-10-20 21:41 UTC, hannibal002 approved these changes

2024-10-20 21:41 UTC, merged