Feature: Arachne kill timer
hannibal00212/SkyHanni pull request #1993
Opened 2024-06-04 12:23 UTC by MTOnline69

## What
Shows how long it took to kill Arachne after the fight ends. Enabled by default.

This is an improved version of [DulkirMod's one](https://github.com/inglettronald/DulkirMod/blob/master/src/main/kotlin/dulkirmod/features/ArachneTimer.kt), which has the following issues:
- The message doesn't send at all if you have bits available.
- The message often sends massively incorrect times, e.g. when:
  - You switch servers.
  - You damage Arachne but aren't in the Sanctuary when it dies.
  - You go in and out of the Sanctuary.
- The timer ends slightly after Arachne dies.
- Ugly DulkirMod Prefix

Has a slight dependency on repoPatterns in [ArachneChatMessageHider.kt](https://github.com/hannibal002/SkyHanni/blob/beta/src/main/java/at/hannibal2/skyhanni/features/chat/ArachneChatMessageHider.kt)
<details>
<summary>Images</summary>

![image](https://github.com/hannibal002/SkyHanni/assets/97001154/935a9b85-c607-4a6a-9a8f-202902566e23)

</details>

## Changelog New Features
+ Added Arachne Kill Timer. - MTOnline
    * Shows how long it took to kill Arachne when the fight ends.

2024-06-04 12:32 UTC, CalMWolfs requested changes
just a few minor things I noticed

2024-06-04 12:32 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/chat/ArachneChatMessageHider.kt
This should be made into an object so other classes can access its methods

2024-06-04 12:32 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/combat/mobs/ArachneKillTimer.kt
> +class ArachneKillTimer {
This should also be an object, and should have the @SkyHanniModule annotation to auto load it (then you remove the load module from SkyHanniMod.kt)

2024-06-04 12:32 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/combat/mobs/ArachneKillTimer.kt
> +        IslandType.SPIDER_DEN.isInIsland() && config.showArachneKillTimer
```suggestion
    fun isEnabled() = IslandType.SPIDER_DEN.isInIsland() && config.showArachneKillTimer
```

2024-06-04 12:32 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/combat/mobs/ArachneKillTimer.kt
> +        }
you should just set it to farPast here regardless of the new island

2024-06-04 13:54 UTC, CalMWolfs approved these changes
worked fine, pushed a bit of code cleanup and made the text blue so that it is a bit easier to see

![image](https://github.com/hannibal002/SkyHanni/assets/94038482/47dac057-88ff-49bd-9692-2720bef14b06)

2024-09-07 18:24 UTC, hannibal002 requested changes
The feature works as expected. Please add regex tests for easier maintaining the class in the future.

2024-09-07 18:24 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/combat/mobs/ArachneKillTimer.kt
> +        "§f +§r§eYour Damage: §r§a[0-9,]+ §r§7\\(Position #[0-9,]+\\)"
please use regex tests everywhre, especially for this one here

2024-09-07 20:26 UTC, hannibal002 approved these changes
GitHub is perfect

![image](https://github.com/user-attachments/assets/b42d61e3-2284-4f3f-80d7-c8e3267dcc56)

2024-09-07 20:26 UTC, merged