Fix: Issues with /gfs on some items
hannibal00212/SkyHanni pull request #1998
Opened 2024-06-04 14:19 UTC by qtlunya

## PR Reviews

When your PR is marked as ready for review, some of our maintainers will look through your code to make sure everything is good to go. In order to do this, they may request some changes you will need to do, **or fix smaller stuff (like merge conflicts) for you**. If a maintainer has reviewed your PR, make sure to **pull any of their changes** into your local project before doing more work on your code. Having maintainers fix small stuff for you helps us speed up the process of merging your PR, so if some of your systems warrant further care, be sure to let us know (preferably with a code comment).

Make sure to only mark your PR as "Ready to review" when it is. If you still want to do major changes, you can keep a draft PR open until then.

## What
Fixed `/gfs` using the wrong item ID for Brown Mushroom and Hay Bale, as well as giving Sulphur instead of Gunpowder.

## Changelog Fixes
+ Fixed `/gfs` failing on Brown Mushroom and Hay Bale. - Luna
+ Fixed `/gfs` giving Sulphur instead of Gunpowder. - Luna

2024-06-04 14:20 UTC, CalMWolfs requested changes
maybe these fixes should be in the repo

2024-06-04 14:22 UTC, Thunderblade73 commented
Question why do we have getFromSackApi and a hypixel command for it?

2024-06-04 14:23 UTC, qtlunya commented
> maybe these fixes should be in the repo
Is there an existing way to do this, or should I just create a new file in the repo for it?

> Question why do we have getFromSackApi and a hypixel command for it?
Not sure, but GetFromSackAPI calls the HypixelCommand.

2024-06-04 14:24 UTC, CalMWolfs commented
> Is there an existing way to do this, or should I just create a new file in the repo for it?

id make a new file unless you see a fitting file

2024-06-04 14:25 UTC, Thunderblade73 commented
> Not sure, but GetFromSackAPI calls the HypixelCommand.
No, it doesn't. And the HypixelCommand way of calling also breaks the queening btw. So the fix should be written in there not in the HypixelCommand.

2024-06-04 14:28 UTC, Thunderblade73 commented
![image](https://github.com/hannibal002/SkyHanni/assets/85900443/4be0d649-f776-4dad-a4ea-1d060c396a5f)
Why, hannibal. This is wrong.
Oh and I'm sorry HypixelComannds is called in the gfs api (I didn't see that change)

2024-06-04 14:31 UTC, qtlunya commented
Yeah, the reason I did it in the HypixelCommand is to not have to duplicate the logic in both places where it's called. But maybe we should have it be a method in GetFromSacksAPI and call it before passing it on to the HypixelCommand?

2024-06-05 12:08 UTC, hannibal002 commented
> Why, hannibal. This is wrong.

Whats going on?

2024-06-06 23:34 UTC, qtlunya commented
Waiting on #1999.

2024-06-08 08:34 UTC, hannibal002 commented
The wait is over @qtlunya

2024-06-08 15:59 UTC, qtlunya commented
Yeah, I'll get back to this soon.

2024-12-20 02:44 UTC, CalMWolfs commented
Your pull request has been inactive for an extended period and appears to be either a draft or awaiting resolution of merge conflicts or requested changes. Therefore, I am closing it for now. Feel free to reopen it when it’s ready for review.

2024-12-20 02:44 UTC, closed without merging