Feature + Backend: Enchanted Book Drop Name + Edit Chat Message
hannibal00212/SkyHanni pull request #2000
Opened 2024-06-04 15:53 UTC by ItsEmpa

## What
Adds a feature to show the name of the enchantment in enchanted books dropped in the chat messages instead of just saying "Enchanted Book", and sends a custom message if you get a book without any chat message.

Also adds a way to be able to edit previously sent chat messages in chat without having to rely on message ids, and without the message being moved.

Still needs some more testing.

## Changelog New Features
+ Added Enchanted Book Drop Name. - Empa
    * Shows the name of the enchantment dropped in rare drop messages, and sends a custom one if none is sent by Hypixel.

## Changelog Technical Details
+ Added ChatUtils.editFirstMessage. - Empa

2024-06-05 10:30 UTC, ItsEmpa commented
seems like its working properly, set it as ready for review

2025-02-11 12:38 UTC, hannibal002 requested changes
code looks good. any way we can test this easily?

2025-02-11 12:38 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/chat/RareDropMessages.kt
> +        val anyRecent = ChatUtils.chatLines.none {
when using patcher, this will iterate over many many lines. maybe first use `take()` to not process everything but only the last 50ish messages? (i assume the messages are in order in the list)

2025-02-11 12:38 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/chat/RareDropMessages.kt
> +                message += " §a($luckString ✴ SkyHanni User Luck"
not sure i like this without opt out

2025-02-11 12:42 UTC, NopoTheGamer commented on src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
> +    /** Use when showing the item name to the user (in guis, chat message, etc.), not for comparing. */
why are we doing multi line comments for a single line?

2025-02-11 12:49 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
> +    /** Use when showing the item name to the user (in guis, chat message, etc.), not for comparing. */
Why are we using single line comments for multi lines? We never use multi-line comments inside functions, only as docs above a function.

2025-02-11 14:04 UTC, ItsEmpa commented on src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
> +    /** Use when showing the item name to the user (in guis, chat message, etc.), not for comparing. */
this is not multiline comment, its a documentation comment (javadoc in java, i think its called KDoc in kt but whatever)

difference is that with doc comments, when you hover over a function
![imagen](https://github.com/user-attachments/assets/b9b0dd90-bde7-43ce-82bf-5167d9dd3e90)
it actually shows those comments. and i think in these cases they should be shown, since they are talking about when not to use them.

2025-02-14 14:43 UTC, hannibal002 commented
Empa: 
id recommend just fishing with a totem of corruption
corruption 1 books would work

2025-02-14 15:07 UTC, hannibal002 approved these changes
Can not test this, hopefully beta users can test
![image](https://github.com/user-attachments/assets/86229164-5960-4b23-a560-512947b764dd)

2025-02-14 15:07 UTC, merged