Feature: Attribute Overlay
hannibal00212/SkyHanni pull request #2001
Opened 2024-06-04 15:53 UTC by ItsEmpa

## What
Adds an overlay for showing attributes of items and their levels, being able to customize which attributes to show, and being able to highlight godrolls in a different color.

<details>
<summary>TODO</summary>

- [ ] Get an actual godrolls list for each item
- [ ] Move godrolls list to repo

</details>

<details>
<summary>Images</summary>

![image](https://github.com/hannibal002/SkyHanni/assets/42304516/0780da13-a488-45f0-b73e-aaf5e1cce5a5)

</details>

## Changelog New Features
+ Added Attribute Overlay. - Empa
    * Options to highlight GodRolls in a different color, only show certain attributes, etc.

2024-10-09 09:18 UTC, CalMWolfs requested changes
would be good if these had some colour i think, looks a little bland
![image](https://github.com/user-attachments/assets/381bb3c6-4c10-42ec-a014-4a49480a5ddc)

Hide non Good Rolls does not work for me

2024-10-18 14:27 UTC, hannibal002 requested changes

2024-10-18 14:27 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/attribute/AttributeAPI.kt
> +    enum class AttributeType(val displayName: String, val internalName: String, val shortName: String) {
Please move the enum into the repo, and remove the "unknown" value.

2024-10-18 14:27 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/AttributeOverlayConfig.java
> +    public List<AttributeAPI.AttributeType> attributesList = new ArrayList<>(AttributeAPI.AttributeType.getEntries());
Please just save the string/id of the attribute here, and use as default a list of some expensive/god rolls here, not everything

2024-10-22 18:49 UTC, hannibal002 approved these changes

2024-10-22 18:49 UTC, merged