add/fix profile upgrades
hannibal00212/SkyHanni pull request #2007
Opened 2024-06-05 00:08 UTC by appable0

## What
Fix issue with the Account Upgrade Reminder feature when profile and account upgrades were active at the same time. Now stores account and profile upgrades separately. Also, generally refactored the module.

Resolves [issue on Discord here](https://discord.com/channels/997079228510117908/1247241068404277369/1247241068404277369).

## Changelog Fixes
+ Fix Account Upgrade Reminder feature with simultaneous account and profile upgrades. - appable

2024-06-05 12:22 UTC, hannibal002 requested changes
not tested in game.

2024-06-05 12:22 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/fame/UpgradeReminder.kt
> +        val name = playerStorage.currentAccountUpgrade ?: return
We should use the `config migration fix event` instead. Then, we can remove the values `currentAccountUpgrade` and `nextAccountUpgradeCompletionTime` entirely

2024-06-05 12:22 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/fame/UpgradeReminder.kt
> +                    else -> return null
return here can go

2024-06-05 12:22 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/fame/UpgradeReminder.kt
> +        "§8Duration: (?<duration>\\d{1,3})d"
is the format always in days? when not, will detection break? cant we use TimeUtils to dynamically parse the time unit?

2024-06-05 12:22 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/storage/PlayerSpecificStorage.java
> +    public UpgradeReminder.CommunityShopUpgrade communityShopUpgrade = null;
please include the word "account" to prevent confusion

2024-06-05 12:22 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
> +    public UpgradeReminder.CommunityShopUpgrade communityShopUpgrade = null;
please include the word "profile" to prevent confusion

2024-06-05 20:11 UTC, appable0 commented
Made some changes to address feedback. Two notes:
- The migration creates the CommunityShopUpgrade object with a null name if there was no active upgrade before. I added a workaround to not send reminders about upgrades with null names, but I'd love to know if there's a cleaner way to do this.
- It's always either days or the string "Instant!" currently. I switched to TimeUtils, but with an additional guard for "Instant!" so that instant upgrades remain ignored.

2024-06-08 08:07 UTC, hannibal002 approved these changes

2024-06-08 08:07 UTC, merged