Add: Special stray rabbit screen flashing
hannibal00212/SkyHanni pull request #2040
Opened 2024-06-08 21:07 UTC by superhize

## What
Color your screen with a cool breathing effect when a special stray rabbit appears.

## Changelog New Features
+ Flash your screen when a special stray rabbit appears. - HiZe
    * Option to also flash on normal stray rabbits.

2024-06-09 11:18 UTC, superhize commented
I broke something, fixing it

2024-06-09 17:49 UTC, superhize commented
It work

2024-06-13 21:12 UTC, hannibal002 requested changes
code looks fine, but cant test yet

2024-06-13 21:12 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryDataLoader.kt
> +    @SubscribeEvent
move this into a new separate class

2024-06-13 21:12 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryAPI.kt
> +    var flashScreen = false
dont keep it in api, as it is not used anywhere else

2024-06-13 21:12 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateFactoryRabbitWarningConfig.java
> +    public boolean flashScreen = false;
maybe also an option to show for non special rabbits, normal stray rabbits? (also this would be easier to test the flash haha)

2024-06-15 00:33 UTC, hannibal002 requested changes
sound doesnt get played as often as expected. not sure what the problem is.
the  flash works like a charm.

2024-06-15 00:33 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/chocolatefactory/ChocolateFactoryRabbitWarningConfig.java
> +        REGULAR("Regular"),
"regular only" is not needed. rather have the options be "only special", "all", "none". or something similar

2024-06-22 07:51 UTC, hannibal002 approved these changes

2024-06-22 07:51 UTC, merged