Feature: Draconic Sacrifice Tracker
hannibal00212/SkyHanni pull request #2077
Opened 2024-06-13 03:39 UTC by superhize

## What
Tracker for the Draconic Altar sactifices

## Changelog New Features
+ Draconic Sacrifice Tracker. - HiZe

2024-06-13 03:43 UTC, superhize commented on src/main/java/at/hannibal2/skyhanni/features/misc/DraconicSacrificeTracker.kt
> +        var bonusRewards: MutableMap<BonusReward, Long> = mutableMapOf();
i'm tired

2024-10-06 21:38 UTC, jani270 commented on src/main/java/at/hannibal2/skyhanni/config/features/misc/DraconicSacrificeTrackerConfig.java
> +    @ConfigEditorBoolean
Missing feature toggle

2024-10-06 21:38 UTC, jani270 commented on src/main/java/at/hannibal2/skyhanni/config/features/misc/DraconicSacrificeTrackerConfig.java
> +    @ConfigOption(name = "Enable", desc = "Enable the Draconic sacrifice tracker.")
```suggestion
    @ConfigOption(name = "Enabled", desc = "Enable the Draconic sacrifice tracker.")
```

2024-10-06 21:38 UTC, jani270 commented on src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
> +    public DraconicSacrificeTrackerConfig draconicSacrificeTracker = new DraconicSacrificeTrackerConfig();
Seems like a missing empty line here?

2024-10-08 02:14 UTC, CalMWolfs requested changes

2024-10-08 02:14 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/misc/DraconicSacrificeTracker.kt
> +    )
please include regex tests

2024-10-08 02:14 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/misc/DraconicSacrificeTracker.kt
> +            val essences = NumberUtil.format(item.totalAmount)
'format(Number, Boolean = ...): String' is deprecated. 
Probably use add separators instead

2024-10-08 02:14 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/misc/DraconicSacrificeTracker.kt
> +        var itemsSacrifice = 0L
should be itemsSacrificed

2024-10-08 02:14 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/misc/DraconicSacrificeTracker.kt
> +        var sacrifiedItemsMap: MutableMap<String, Long> = mutableMapOf()
should be sacrificedItemsMap

2024-10-11 19:29 UTC, ItsEmpa requested changes

2024-10-11 19:29 UTC, ItsEmpa commented on src/main/java/at/hannibal2/skyhanni/features/misc/DraconicSacrificeTracker.kt
> +                data.sacrificedItemsMap.map { (key, value) -> "$key: §b$value" },
if you already are giving names to key and value, probably better to just name them "item" and "amount"
```suggestion
                data.sacrificedItemsMap.map { (item, amount) -> "$item: §b$amount" },
```

2024-10-11 19:29 UTC, ItsEmpa commented on src/main/java/at/hannibal2/skyhanni/features/misc/DraconicSacrificeTracker.kt
> +            tracker.addItem("ESSENCE_DRAGON".asInternalName(), amount, command = false)
initialize essence_dragon as internal name in the class and not inside the function, so you dont have to initialize this every time

2024-10-11 19:29 UTC, ItsEmpa commented on src/main/java/at/hannibal2/skyhanni/features/misc/DraconicSacrificeTracker.kt
> +                "§b${data.itemsSacrificed.addSeparators()} §6Items Sacrified",
```suggestion
                "§b${data.itemsSacrificed.addSeparators()} §6Items Sacrificed",
```

2024-10-15 01:10 UTC, CalMWolfs approved these changes
worked for me

2024-10-15 01:10 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
> -    @Suppress("LongMethod")
not sure why this is getting removed, maybe a mistake when merging?

2024-10-15 01:10 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/commands/Commands.kt
> +        }
Now that command registration is event based you can just add this to DraconicSacrificeTracker instead

    @HandleEvent
    fun onCommandRegistration(event: CommandRegistrationEvent) {
        event.register("shresetdraconicsacrificetracker") {
            description = "Resets the Draconic Sacrifice Tracker."
            category = CommandCategory.USERS_RESET
            callback { tracker.resetCommand() }
        }
    }

2024-10-16 13:40 UTC, ItsEmpa approved these changes

2024-10-20 21:23 UTC, hannibal002 commented
updated the config a bit
![image](https://github.com/user-attachments/assets/f1ec4e17-3e6f-491a-b3f4-414a97ec8c41)

2024-10-20 21:27 UTC, merged