Improvement: Area Miniboss Mob Detection
hannibal00212/SkyHanni pull request #2095
Opened 2024-06-14 15:55 UTC by ItsEmpa

## What
Migrates Area Miniboss features to use mob detection instead, and fixes an issue with formatting Durations with milliseconds.

## Changelog Fixes
+ Fixed showing durations with milliseconds. - Empa

## Changelog Technical Details
+ Refactored Area Miniboss Features to use mob detection. - Empa

2024-06-14 21:53 UTC, hannibal002 requested changes
Now the time looks wrong for area mobs. I'm sure it was not like that
![image](https://github.com/hannibal002/SkyHanni/assets/24389977/eead42c6-1f70-4ccb-a556-56beb8879ec7)

Moreover, the new mob detection doesn't detect mobs when you first enter a region/"run into them". It only detects area mobs when they spawn around you. The old system detects them on first join as well.

2024-06-15 07:26 UTC, ItsEmpa commented
timer issue is fixed now.
and as i said in discord, the reason the minibosses arent detected outside is because we now check that you are in a slayer area. i can change this if really needed

2024-06-15 09:34 UTC, hannibal002 requested changes
beep boop

2024-06-15 09:34 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/combat/mobs/AreaMiniBossFeatures.kt
> +        if (!SlayerAPI.isInAnyArea) return
waiting for deletion (as discussed in discord)

2024-06-16 09:32 UTC, hannibal002 approved these changes
Works for me

2024-06-16 09:32 UTC, merged