Feature: Forge recipe Get from Sack
hannibal00212/SkyHanni pull request #2106
Opened 2024-06-15 23:15 UTC by minhperry

## What
Add a button in a forge recipe menu to try and get from sack all of its ingredients.

<details>
<summary>Images</summary>
![image](https://github.com/hannibal002/SkyHanni/assets/46137516/2f2df81d-1ccd-4a53-860e-2fd8d2d1345d)

</details>

## Changelog New Features
+ Add a Get from Sack button in forge recipe menu to take its ingredients. - minhperry
    * It will only try to get ingredients that actually have a sack entry. Executes /gfs under the hood.

2024-06-15 23:23 UTC, minhperry commented on src/main/java/at/hannibal2/skyhanni/features/mining/ForgeGfs.kt
> +        if (!confirmScreenPattern.matches(event.inventoryName)) return
this will probably me merged into a var

2024-06-16 00:27 UTC, CalMWolfs requested changes

2024-06-16 00:27 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/mining/ForgeGfs.kt
> +        // showFakeItem = config && confirmScreenPattern.matches(event.inventoryName)
These comments aren't needed

2024-06-16 13:14 UTC, minhperry commented
Probably need some wording changes before official merge

2024-08-26 11:05 UTC, merged