Fix: Unknown Lines Handler
hannibal00212/SkyHanni pull request #2119
Opened 2024-06-18 15:39 UTC by ItsEmpa

## What
Fixes the custom scoreboard unknown lines handler not working properly for some reason i still cant understand. wip

## Changelog Fixes
+ Fixed Custom Scoreboard Unknown lines. - Empa

2024-06-18 16:04 UTC, j10a1n15 requested changes

2024-06-18 16:04 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ScoreboardElements.kt
>  internal var unknownLinesSet = TimeLimitedSet<String>(2.seconds) { onRemoval(it) }
```suggestion
internal var unknownLinesSet = TimeLimitedSet<String>(1.seconds) { onRemoval(it) }
```

2024-06-18 19:37 UTC, j10a1n15 approved these changes

2024-06-20 21:19 UTC, hannibal002 approved these changes

2024-06-20 21:19 UTC, merged