Fix: Custom Wardrobe Price Error
hannibal00212/SkyHanni pull request #2123
Opened 2024-06-18 21:44 UTC by j10a1n15

## What
This Pull Request fixes the Custom Wardrobe NEUInternalName.NONE has no name Error, when it tries to generate a price of some weird items, like [here](https://discord.com/channels/997079228510117908/1252636281566007338/1252641503197659147).

<details>
<summary>Stacktrace</summary>

SkyHanni 0.26.Beta.10: DelayedRun task crashed while executing
 
Caused by java.lang.IllegalStateException: NEUInternalName.NONE has no name!
    at SH.utils.ItemUtils.grabItemName(ItemUtils.kt:374)
    at SH.utils.ItemUtils.getItemName(ItemUtils.kt:362)
    at SH.features.misc.items.EstimatedItemValueCalculator.addBaseItem(EstimatedItemValueCalculator.kt:539)
    at SH.features.misc.items.EstimatedItemValueCalculator.calculate(EstimatedItemValueCalculator.kt:101)
    at SH.features.misc.items.EstimatedItemValueCalculator.getTotalPrice(EstimatedItemValueCalculator.kt:98)
    at SH.features.inventory.wardrobe.WardrobeAPI.createPriceLore(WardrobeAPI.kt:98)
    at SH.features.inventory.wardrobe.CustomWardrobe.addSlotHoverableButtons(CustomWardrobe.kt:480)
    at SH.features.inventory.wardrobe.CustomWardrobe.createRenderables(CustomWardrobe.kt:324)
    at SH.features.inventory.wardrobe.CustomWardrobe.update(CustomWardrobe.kt:146)
    at SH.features.inventory.wardrobe.CustomWardrobe.access$update(CustomWardrobe.kt:44)
    at SH.features.inventory.wardrobe.CustomWardrobe$onInventoryUpdate$1.invoke(CustomWardrobe.kt:141)
    at SH.features.inventory.wardrobe.CustomWardrobe$onInventoryUpdate$1.invoke(CustomWardrobe.kt:140)
    at SH.utils.DelayedRun$checkRuns$1.invoke(DelayedRun.kt:29)
    at SH.utils.DelayedRun$checkRuns$1.invoke(DelayedRun.kt:25)
    at SH.utils.DelayedRun.checkRuns$lambda$0(DelayedRun.kt:25)
    at SH.utils.DelayedRun$$Lambda$1374/1822961453.test(Unknown Source)
    at java.util.ArrayList.removeIf(ArrayList.java:1405)
    at SH.utils.DelayedRun.checkRuns(DelayedRun.kt:25)
    at SH.data.MinecraftData.onTick(MinecraftData.kt:74)
    at FML.common.eventhandler.EventBus.post(EventBus.java:140)

</details>

## Changelog Fixes
+ Fixed Custom Wardrobe error when getting an item price. - j10a1n15, Empa

2024-06-19 07:39 UTC, ItsEmpa requested changes

2024-06-19 07:39 UTC, ItsEmpa commented on src/main/java/at/hannibal2/skyhanni/features/inventory/wardrobe/WardrobeAPI.kt
> +        for (stack in slot.armor.filter { it?.getInternalNameOrNull() != null }.filterNotNull()) {
```suggestion
        for (stack in slot.armor.filterNotNull().filter { it.getInternalNameOrNull() != null }) {
```

2024-06-19 11:33 UTC, ItsEmpa approved these changes

2024-06-22 06:42 UTC, hannibal002 approved these changes

2024-06-22 06:42 UTC, merged