Feature: Bridge formatter
hannibal00212/SkyHanni pull request #2134
Opened 2024-06-21 11:44 UTC by minhperry

## Not R2R / Draft

## What
Added a bridge bot formatter that reformat messages sent by bridge bots. Needs manual user input of: Bridge name, Output format and Separator.

<details>
<summary>Images</summary>

![image](https://github.com/hannibal002/SkyHanni/assets/46137516/862dd77f-ecf0-4d35-bc22-14a3fdf0e64b)
![image](https://github.com/hannibal002/SkyHanni/assets/46137516/901c34cc-a9d3-4fef-8d45-b425595f0dde)

</details>

## Changelog New Features
+ Added a bridge formatter. - minhperry

2024-06-23 17:41 UTC, hannibal002 requested changes
Just some first thoughts. Have not tested yet

2024-06-23 17:41 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/chat/BridgeFormatterConfig.java
> +    public String separator = ":";
Please make it clear that this is referring to the incoming format, not the outgoing format (maybe move it around or add additional comments, not sure)

2024-06-23 17:41 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/chat/BridgeFormatter.kt
> +        val format = config.bridgeFormat
You can inline this variable

2024-06-23 17:41 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/chat/BridgeFormatter.kt
> +        if (!config.enabled) return
Please move the check at the beginning of the function

2024-06-23 17:41 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/chat/BridgeFormatterConfig.java
> +        desc = "Reformat guild bridge messages."
Please be more descriptive (assuming someone doesn't know what a "bridge bot" is.)

2025-04-26 19:29 UTC, minhperry commented
I feel like this PR is no longer needed since:
- I haven't worked on this since long
- Other than the standard message format from the bridge bot, there are just too many other maybe guild-specific bot message format that this should take into consideration. This is probably better done with a ct module.

2025-04-26 19:29 UTC, closed without merging