Experimenation gui
hannibal00212/SkyHanni pull request #2167
Opened 2024-06-27 22:40 UTC by ILike2WatchMemes

## What
Added an experimentation GUI that display found and matched pairs, powerups, missing pairs and normals (items without their counterpart).

<details>
<summary>Images</summary>

[](https://cdn.discordapp.com/attachments/1159978973497925643/1256014853496246282/2024-06-28_00-30-30.mp4?ex=667f3a7c&is=667de8fc&hm=a54c596ba992fc179381b17c90068df9d1b2e303b2e961a2f5572cab4e5858be&)

</details>

## Changelog New Features
+ Added Experimentation GUI. - ILike2WatchMemes
    * Displays found and matched pairs, powerups, missing pairs/normals.

2024-06-27 22:40 UTC, ILike2WatchMemes commented
video didnt work so here's the link:

https://cdn.discordapp.com/attachments/1159978973497925643/1256014853496246282/2024-06-28_00-30-30.mp4?ex=667f3a7c&is=667de8fc&hm=a54c596ba992fc179381b17c90068df9d1b2e303b2e961a2f5572cab4e5858be&

2024-06-27 22:50 UTC, ILike2WatchMemes commented
oops renamed the branch didnt know it would do that

2024-06-28 00:20 UTC, ILike2WatchMemes commented
realised a lot of problems, needs fixing

2024-06-28 13:09 UTC, ILike2WatchMemes commented
https://streamable.com/9uci6e

2024-06-28 21:22 UTC, Thunderblade73 requested changes

2024-06-28 21:22 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/ExperimentationTableDisplay.kt
> +    fun onBackgroundDrawn(event: BackgroundDrawnEvent) {
Use ``GuiRenderEvent.ChestGuiOverlayRenderEvent`` instead of background drawnevent

2024-06-29 19:50 UTC, ILike2WatchMemes commented
[Moved into big pr](https://github.com/hannibal002/SkyHanni/pull/2171)

2024-06-29 19:50 UTC, closed without merging