Features & Improvements: Inventory - Experiments rework
hannibal00212/SkyHanni pull request #2171
Opened 2024-06-29 19:48 UTC by ILike2WatchMemes

## What
- Added new Category under Inventory, "Experimentation Table"
- Added a display that shows attempts and or xp since last ULTRA-RARE, also "reworked" like 5 lines in UltraRareBookAlert.
- Added an experimentation table display that shows found and matched pairs, powerups, missing pairs and normals (items without their counterpart).
- Added Experiments Profit Tracker (Coins/Enchanting XP)
- Added getCurrentExperiment in InventoryUtils
- Changed some small things in UltraRareBookAlert

## Changelog New Features
+ Added Experimentation Table Display. - ILike2WatchMemes 
    * Displays found and matched pairs, powerups, missing pairs/normals.
+ Added Experiments Dry-Streak Display. - ILike2WatchMemes 
    * Shows attempts and or xp since last ULTRA-RARE
+ Added Experiments Profit Tracker - ILike2WatchMemes
    * Profits in Coins and Enchanting XP

2024-07-05 17:55 UTC, ILike2WatchMemes commented
😭

2024-09-09 14:07 UTC, hannibal002 requested changes
Your restructuring in the config is looking good.
Also, the many options are cool to have!

I have not yet tested the feature in game.
This is just a first read, maybe there are more things to change after further testing.

Overall the pr looks good but needs more work.

2024-09-09 14:07 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/ExperimentationTableConfig.java
> +    public static class ExperimentsProfitTrackerConfig {
please move those classes into separate files. you can even create a new package in "inventory" for the experimentation tablle features

2024-09-09 14:07 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/ExperimentationTableConfig.java
> +    @ConfigOption(name = "Experiments Dry-Streak Display", desc = "")
name is probably too long. remove experiments?

2024-09-09 14:07 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/UltraRareBookAlert.kt
> +        config.ultraRareBookAlert && LorenzUtils.inSkyBlock && InventoryUtils.getCurrentExperiment() != null
please check first for skyblock, then access the config

2024-09-09 14:07 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/storage/ProfileSpecificStorage.java
> +    public ExperimentsDryStreakStorage dryStreakStorage = new ExperimentsDryStreakStorage();
please use a ExperimentaionStorage class and put all the new data in there

2024-09-09 14:07 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsDisplay.kt
> +    private var foundExperiences = mutableListOf<Pair<String, Int>>()
instead of those 5 maps, use only list/map that stores the type of what was found as enum

2024-09-09 14:07 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsDisplay.kt
> +        "Gained \\+\\d Clicks?|Instant Find|\\+\\S* XP",
please use regex-tests for all new repo patterns

2024-09-09 14:07 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsDisplay.kt
> +    private fun handleReward(index: Int, slot: Int, uncovered: Int, reward: String) {
parameter index is unused

2024-09-09 14:07 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsDisplay.kt
> +        lastSlotClicked.let {
unnecessary let. either unwrap or extract into a new function

2024-09-09 14:07 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsDisplay.kt
> +        val sideSpaces2 = listOf(16, 17, 18, 19, 25, 26, 27, 28, 34, 35, 36, 37)
those two lists should be defined outside the function

2024-09-09 14:07 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/ExperimentationTableConfig.java
> +    public enum Experiments {
enum is singular

2024-09-09 14:07 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/ExperimentationTableConfig.java
> +    public enum ExperimentMessages {
please move the enums into the kotlin class

2024-09-09 14:07 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/ExperimentationTableConfig.java
> +    public boolean experimentationTableDisplay = false;
unnecessary word here. just call it "display"

2024-09-09 14:07 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/ExperimentationTableConfig.java
> +    public Position informationDisplayPosition = new Position(-220, 70, false, true);
this name can also be reduced

2024-09-09 14:07 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/UltraRareBookAlert.kt
> +    val ultraRarePattern by patternGroup.pattern(
regexes like that should be moved into an ExperimentationTableAPI class

2024-09-09 14:07 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsDryStreakDisplay.kt
> +        if (InventoryUtils.getCurrentExperiment() != null) {
use early return

2024-09-09 14:07 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsDryStreakDisplay.kt
> +        storage?.let {
please use `val storage = storage ?: return` instead of unnesseary wrapping in `let`

2024-09-09 14:07 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsDryStreakDisplay.kt
> +            when {
could be replaced with `if`

2024-09-09 14:07 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsDryStreakDisplay.kt
> +        if (!config.attemptsSince && !config.xpSince) return@buildList
this feels like the wrong spot to check. can we move the "is feature active" checks into onChestGuiOverlayRendered and fully return, not even calling an empty list instead?

2024-09-12 21:16 UTC, ILike2WatchMemes commented
why is scala banned 😭

2024-09-17 08:26 UTC, hannibal002 requested changes
the superpair data display overlaps with the dry streak display. one of those two needs better default position.

the experimentation table profit tracker is visible after world switch. how about we only show it while not moving after opening the experimentation table and remove the current display duration?

2024-09-20 21:32 UTC, hannibal002 approved these changes

2024-09-20 21:32 UTC, merged