Feature: Thunder Bottle Charged Notification
hannibal00212/SkyHanni pull request #2234
Opened 2024-07-17 21:46 UTC by raaaaaven

## What
Added title notification for when thunder bottles charge. 
I just placed it below replace roman numerals, couldn't think of a better spot.

## Changelog New Features
+ Added title notification for when thunder bottles charge. - raven

2024-07-17 21:56 UTC, j10a1n15 requested changes

2024-07-17 21:56 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/features/misc/ThunderBottleNotification.kt
> +    fun isEnabled() = config.thunderBottleNotification
```suggestion
    fun isEnabled() = LorenzUtils.inSkyblock && config.thunderBottleNotification
```

2024-07-17 21:56 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/features/misc/ThunderBottleNotification.kt
> +        if (event.message.endsWith("§e> Your bottle of thunder has fully charged!")) {
use a repopattern pls

2024-07-17 21:56 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
> +    @ConfigOption(name = "Thunder Bottle", desc = "Show a notification when you charge a Thunder Bottle.")
your description is a bit missleading, not sure if mine is better though
the title could maybe also be more descriptive idk
```suggestion
    @ConfigOption(name = "Thunder Bottle", desc = "Show a notification when your Thunder Bottle is fully charged.")
```

2024-07-17 22:34 UTC, j10a1n15 approved these changes

2024-07-24 20:59 UTC, Thunderblade73 requested changes
Feature looks fine. I don't like it that it is in misc. But there is also not really a better place for it.
Only thing that needs to be done is to address the 2 small code changes.

2024-07-24 20:59 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/misc/ThunderBottleNotification.kt
> +    fun isEnabled() = LorenzUtils.inSkyBlock && config.thunderBottleNotification
make isEnabled private.

2024-07-24 20:59 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/misc/ThunderBottleNotification.kt
> +        "bottle.charged",
Better name, since that one is very likely to have a conflict in the future
```suggestion
        "thunderbottle.charged",
```

2024-07-24 21:28 UTC, raaaaaven commented on src/main/java/at/hannibal2/skyhanni/features/misc/ThunderBottleNotification.kt
> +    fun isEnabled() = LorenzUtils.inSkyBlock && config.thunderBottleNotification
👍

2024-07-24 21:30 UTC, Thunderblade73 approved these changes

2024-07-28 10:21 UTC, merged