Backend: Stats API
hannibal00212/SkyHanni pull request #2253
Opened 2024-07-24 15:24 UTC by Thunderblade73

## What
Grabs and saves stat information from where ever possible. It has 3 sources: Tablist, SbMenu and the "Your Equipment and Stats" menu.
Also expanded SkyblockStats to include all stats (it didn't have double hook, the crop specifc fortune and cold resitance).

## Changelog Technical Details
+ Added Stats Api. - Thunderblade73

2024-07-24 19:14 UTC, qtlunya requested changes

2024-07-24 19:14 UTC, qtlunya commented on src/main/java/at/hannibal2/skyhanni/data/model/SkyblockStat.kt
> +    COCOA_BEANS_FORTUNE("§7☘", "", " §7(?:§m)☘ Cocoa Beans Fortune (?<value>.*)"),
You forgot Sugar Cane Fortune 🥺

2024-07-24 19:14 UTC, qtlunya commented on src/main/java/at/hannibal2/skyhanni/data/model/SkyblockStat.kt
> +    var lastKnowValue: Double
```suggestion
    var lastKnownValue: Double
```
(also change it in other places where it's referenced)

2024-07-24 19:27 UTC, ItsEmpa commented
not needed here but we could probably also get health, defense and intel from action bar?

2024-07-24 19:48 UTC, Thunderblade73 commented
> not needed here but we could probably also get health, defense and intel from action bar?

We can also get speed from the player enttiy (same as sba did it),
But this should be done in a later PR. Will add an todo for that.

2024-07-24 19:53 UTC, qtlunya commented
> We can also get speed from the player enttiy (same as sba did it)

There's a little caveat here. Your actual uncapped Speed stat can be technically go up to at least 600, but your actual walk speed (without sprint buff) will never be over 500% of normal walk speed. The distinction may be relevant for some items such as the Warden Helmet (though I don't know how you'd get 600 speed cap without both Racing Helmet and Black Cat).

2024-07-26 20:32 UTC, NetheriteMiner commented
> > We can also get speed from the player enttiy (same as sba did it)
> 
> There's a little caveat here. Your actual Speed stat (post-cap) can technically go up to at least 600, but the actual walk speed reported to the client will never be over 500% of normal walk speed.
> 
> The distinction may be relevant for some items such as the Warden Helmet (though I don't know how you'd get 600 speed cap without using both Racing Helmet and Black Cat at the same time).

1. Rancher's boots
2. By accounting for it with the player entity, you don't need to account for the over 600 thing because it's always right, which is why...
3. SBA's algorithm is already correct, so we don't need to improve on it (in terms of speed cap accuracy, idk about anything else)
4. For getting stuff from the action bar, maybe you can use data.ActionBarStatsData?

2024-07-26 20:35 UTC, qtlunya commented
> 1. Rancher's boots

You're several months out of date, they patched that ages ago. Rancher's Boots no longer lets you exceed your normal speed cap of 400 if you aren't using it in combination with items that raise your speed cap actively equipped.

> 2. By accounting for it with the player entity, you don't need to account for the over 500 thing because it's always right, which is why...

It depends on what your goal is.
* Get the player's actual walk speed
** Yeah, just get it from the entity, that will be accurate in all cases.
* Get the value of the player's "Speed" SkyBlock stat
** The entity solution can technically return a wrong value in a few niche cases as explained before.

2024-08-18 21:17 UTC, ILike2WatchMemes requested changes

2024-08-18 21:17 UTC, ILike2WatchMemes commented on src/main/java/at/hannibal2/skyhanni/data/model/SkyblockStat.kt
> +    BONUS_PEST_CHANCE("§2ൠ", " Bonus Pest Chance: §r§2ൠ(?<value>.*)", " §2ൠ Bonus Pest Chance §f(?<value>.*)"),
```suggestion
    BONUS_PEST_CHANCE("§2ൠ", " (?:§r§7§m)?Bonus Pest Chance: (?:§r§2)?ൠ(?<value>.*)", " (?:§7§m|§2)ൠ Bonus Pest Chance (?:§f)?(?<value>.*)"),
```
account for disabled

2024-08-18 21:17 UTC, ILike2WatchMemes commented on src/main/java/at/hannibal2/skyhanni/data/model/SkyblockStat.kt
> +    FARMING_FORTUNE("§6☘", " §r§7(?:§m)?Farming Fortune: ☘(?<value>.*)", " §7(?:§m)☘ Farming Fortune (?<value>.*)"),
```suggestion
    FARMING_FORTUNE("§6☘", " (?:§r§7§m)?Farming Fortune: (?:§r§6)?☘(?<value>.*)", " (?:§7§m|§6)☘ Farming Fortune (?:§f)?(?<value>.*)"),
```
account for enabled

2024-10-09 11:59 UTC, CalMWolfs approved these changes
code lgtm

2024-10-09 12:21 UTC, merged