Improvement: Class highlight
hannibal00212/SkyHanni pull request #2256
Opened 2024-07-25 00:36 UTC by Triggered0

## What
Added class highlighting to Party Finder.

## Changelog Improvements
+ Added Class Highlighting. - Trîggered

2024-07-25 10:28 UTC, hannibal002 commented
Please expand the changelog wording. its unclear right now.

2024-07-25 10:34 UTC, j10a1n15 requested changes

2024-07-25 10:34 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/config/features/dungeon/PartyFinderConfig.java
> +        private final int legacyId;
You don't need the legacyId in newly created enum config options

2024-07-25 14:32 UTC, Triggered0 commented
> Please expand the changelog wording. its unclear right now.

is it ok rn?

2024-09-21 21:40 UTC, hannibal002 commented
I don't understand the feature. What is it for?
This feels redundant since we can already read and work with the currently selected role of the user.

2024-09-22 09:26 UTC, CalMWolfs commented
> I don't understand the feature. What is it for? This feels redundant since we can already read and work with the currently selected role of the user.

Agreed

2024-12-20 02:49 UTC, CalMWolfs commented
Closing this as you have not provided justification for this feature, feel free to reopen if you still want the feature

2024-12-20 02:49 UTC, closed without merging