Fix: Some Dungeon Features to support changed Master Mode text changes in Artist's Adobe update
hannibal00212/SkyHanni pull request #2316
Opened 2024-08-06 18:34 UTC by Fazfoxy

## What
fixes Master Mode Stack Size

## Changelog Fixes
+ Fixed MM Dungeon stack size in the party finder menu. - fazfoxy

2024-08-06 18:37 UTC, Thunderblade73 commented
Please Regex Tests.
Example:
```Kotlin
/** REGEX-TEST: Abcs
*/
Repopattern.pattern("...","Abcs")
```

2024-08-06 21:04 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonFinderFeatures.kt
> +    REGEX-TESTS:
The line REGEX-TESTS is not needed.

2024-08-06 21:05 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonFinderFeatures.kt
> +    * REGEX-TEST: MM Catacombs
This test can't match that better. So either the pattern is wrong or the test is wrong

2024-08-08 18:06 UTC, hannibal002 requested changes
The master star items still have no stack number.
![grafik](https://github.com/user-attachments/assets/8663b23a-477e-4b7f-9254-7286da9296ea)


or was this pr fixing somehting else?

2024-08-08 18:15 UTC, Fazfoxy commented
![image](https://github.com/user-attachments/assets/3d3983ec-6723-4394-8de5-3f9b5f727d67)
This isn't what I'm fixing but also, those stack sizes are working locally, this feature does sometimes fail to work though maybe re-check it?

2024-08-08 18:17 UTC, hannibal002 commented
what else are you fixing then?

2024-08-08 18:18 UTC, Thunderblade73 commented
@hannibal002 I think your "repo pattern force locale" is on the wrong value. If you are in dev enviroment the option must be off. At least that would be the obvious case why it wouldn't work.

2024-08-08 18:19 UTC, Fazfoxy commented
more specifically, this was to do with hypixel's changing of PF notes to be Master Mode The Catacombs unlike previously + dungeon clean end being updated for changed lines

2024-08-08 18:39 UTC, hannibal002 commented
ok i still dont know what the fix actually is about :/ @Fazfoxy

2024-08-08 20:05 UTC, Fazfoxy commented
> ok i still dont know what the fix actually is about :/ @Fazfoxy

ok so, it does fix the MM highlight apparently, but also it makes party stack sizes go back to the correct floor, before PR MM parties would stacksize as the non MM variant because of hypixel changing the description + should fix clean end because hypixel changed that line as well I believe

2024-08-08 20:06 UTC, Fazfoxy commented
![image](https://github.com/user-attachments/assets/3319e9bb-5b99-4ee8-bc04-d5a1eb805faf)
when using non changed it should show like this for MM floors

2024-08-09 06:44 UTC, hannibal002 commented
Now I see, thanks. I have changed the changelog wording accordingly.

2024-08-09 06:45 UTC, hannibal002 approved these changes

2024-08-09 06:45 UTC, merged