Fix: MayorAPI not working without Ministers
hannibal00212/SkyHanni pull request #2389
Opened 2024-08-21 13:53 UTC by j10a1n15

## What
Hypixel stated in the [Better Mayors Update](https://hypixel.net/threads/hypixel-skyblock-patch-notes-0-20-3-better-mayors.5692280/) that ministers wont exist when a special mayor is in Office: "A Minister Perk will not be featured when a Special Mayor is elected as they prefer not to share the spotlight with anyone else."
This Pull Request fixes the MayorAPI not working when this happens.

## Changelog Fixes
+ Fixed Mayor Detection failing when Special Mayors are in office. - j10a1n15

2024-08-21 14:13 UTC, lunaynx commented on src/main/java/at/hannibal2/skyhanni/data/MayorAPI.kt
> +                currentMinister = data.mayor.minister?.let { setAssumeMayorJson(it.name, listOf(data.mayor.minister.perk)) }
```suggestion
                currentMinister = data.mayor.minister?.let { setAssumeMayorJson(it.name, listOf(it.perk)) }
```

2024-08-21 14:13 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/data/MayorAPI.kt
> +                currentMinister = data.mayor.minister?.let { setAssumeMayorJson(it.name, listOf(data.mayor.minister.perk)) }
oops, ty

2024-08-21 14:15 UTC, qtlunya approved these changes

2024-08-21 16:07 UTC, hannibal002 requested changes

2024-08-21 16:07 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/data/jsonobjects/other/MayorJson.kt
> +    @Expose val minister: Minister?,
please add a comment that this is null for special mayors

2024-08-23 09:14 UTC, hannibal002 approved these changes

2024-08-23 09:14 UTC, merged