Feature: Essence Shop Helper
hannibal00212/SkyHanni pull request #2423
Opened 2024-08-27 18:09 UTC by DavidArthurCole

## What
Adds a helper to Essence Shops that tells you how much essence you need to max all upgrades in the shop.

<details>
<summary>Images</summary>

![image](https://github.com/user-attachments/assets/04c724fe-0ea3-4394-a8d6-e41a5b616581)

![image](https://github.com/user-attachments/assets/3fd39183-24f3-4a63-ba0d-de7305392f05)

![image](https://github.com/user-attachments/assets/1c4f3bf1-691e-4fa4-936e-bd49d9427682)

![image](https://github.com/user-attachments/assets/481e3e9b-142c-4884-9041-212acf832080)

</details>

## Changelog New Features
+ Added helper to Essence Shops to assist with maxing upgrades.

2024-08-27 18:23 UTC, j10a1n15 requested changes

2024-08-27 18:23 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/EssenceShopHelper.kt
> +            BazaarApi.searchForBazaarItem(currentEssenceItem!!, essenceNeeded)
you can do `val currentEssenceItem = currentEssenceItem  ?: return` here so you dont need to do the double bang

2024-08-27 18:23 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/EssenceShopHelper.kt
> +            ownedEssence = groupOrNull("count")?.replace(",", "")?.toInt() ?: 0
```suggestion
            ownedEssence = groupOrNull("count")?.formatInt() ?: 0
```

2024-08-27 18:23 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/EssenceShopHelper.kt
> +                    val isMaxed = it.value.getLore().any { loreLine -> Regex(".*§a§lUNLOCKED").containsMatchIn(loreLine) }
this should probably also be a repopattern

2024-08-27 18:23 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/EssenceShopHelper.kt
> +            ErrorManager.skyHanniError("Could not read current Essence Count from inventory §c§l${event.inventoryName}")
A `ErrorManager.logErrorWithData()` with fitting extra data is probably better

2024-09-02 23:16 UTC, DavidArthurCole commented
NEU data is fixed, all shops tested and looking good

![image](https://github.com/user-attachments/assets/921d65b4-28f8-46b8-b4a1-4161d90e12a2)

2024-09-03 08:55 UTC, CalMWolfs requested changes

2024-09-03 08:55 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/EssenceShopJson.kt
For consistancy his file should be in the neu folder of json objects and the class name should start with Neu

2024-09-26 19:55 UTC, DavidArthurCole commented
Adding support for Carnival Shops in this PR as well, since the code shards are almost nearly identical - apart from the fact that carnival tokens can't be bought/sold, making this one significantly easier.
![image](https://github.com/user-attachments/assets/cab855b5-dcdf-4ea5-9d9a-e7c6d21a4e34)

2024-10-21 22:00 UTC, hannibal002 requested changes
works perfectly fine!
two small things:
please remove the italic effect on the yellow command line. this is not matching hypixel or skyhannis design pattern.
please add the gray line "fron skyhanni" just like for every other custom menu item.
![image](https://github.com/user-attachments/assets/98c1a642-4746-4ad8-ba2e-428a43228dca)
![image](https://github.com/user-attachments/assets/3d8fd4cf-7aa9-43f5-9aa3-114ec8d62b62)

2024-10-22 18:57 UTC, hannibal002 approved these changes

2024-10-22 18:57 UTC, merged