Fix: Tungsten Detection on Alpha
hannibal00212/SkyHanni pull request #2437
Opened 2024-08-31 20:11 UTC by hannibal002

## What
Fix tungsten detection on alpha.
bug report: https://discord.com/channels/997079228510117908/1279527967739084972

## Changelog Fixes
+ Fixed Tungsten Ore detection after a change on the Alpha server.

2024-08-31 21:11 UTC, j10a1n15 requested changes

2024-08-31 21:11 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/features/mining/OreBlock.kt
> +        checkBlock = { it.block.let { it == Blocks.cobblestone || it == Blocks.monster_egg } },
You should also check for the monster egg block variant, since this just triggers on all monster egg blocks (stone, cobble, bricks,...)

2024-09-18 08:21 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/mining/OreBlock.kt
> +        checkBlock = { it.block.let { it == Blocks.cobblestone || it == Blocks.monster_egg } },
done

2024-09-18 08:24 UTC, ItsEmpa approved these changes

2024-09-18 08:35 UTC, merged