Improvement: Mention Background Template in Scoreboard Config
hannibal00212/SkyHanni pull request #2447
Opened 2024-09-02 09:19 UTC by j10a1n15

## What
Mentions the not-so-known template that is pinned in support, with a link directly to it. 

exclude_from_changelog

2024-09-04 09:10 UTC, hannibal002 requested changes
We can't link to the discord server this way. While we have discovery enabled, users still need to click on the link, join the server, then click on the link again. And only then they see the correct message.
We should upload the texture pack somwhere outside discord.

2025-01-27 11:20 UTC, j10a1n15 commented
Surely we can get this +8 -5 merged

2025-01-27 11:23 UTC, NopoTheGamer commented
its too complex

2025-01-27 11:25 UTC, CalMWolfs approved these changes

2025-01-27 11:26 UTC, merged