Feature: Spirit leap overlay
hannibal00212/SkyHanni pull request #2514
Opened 2024-09-15 08:53 UTC by Ovi-111

## What
Added a Spirit Leap overlay feature that highlights specific dungeon classes or dead teammates. The overlay displays player information, including their class and class level (toggleable), with a "(Dead)" label for dead teammates.

<details>
<summary>Images</summary>
![2024-09-15_14 31 46](https://github.com/user-attachments/assets/43cba003-7be3-469b-a301-2f78fa85e8e2)
![2024-09-15_14 29 31](https://github.com/user-attachments/assets/9befffff-745b-4b51-90ea-06700e32efd3)
![2024-09-15_13 38 49](https://github.com/user-attachments/assets/f61500e6-9296-4537-9b50-d5bc40254695)

</details>

## Changelog New Features
+ Added Spirit Leap Overlay - Ovi_1
    * Highlights specific dungeon classes with customizable colors.
    * Displays players dungeon class.
    * Shows class level (toggleable).
    * Adds "(Dead)" text for dead teammates with customizable colors.
    
## Changelog Technical Details
+ Added dungeon teammate info - Ovi_1
    * Displays player and teammate class, class level, and alive status can be viewd.

2024-09-15 08:54 UTC, NopoTheGamer commented
your images dont work btw

2024-09-15 09:14 UTC, Ovi-111 commented
> your images dont work btw

idk why but it works now

2024-09-18 03:19 UTC, CalMWolfs requested changes
some things i saw

2024-09-18 03:19 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/features/dungeon/SpiritLeapConfig.java
> +    };
These dont all match up to the defaults above

2024-09-18 03:19 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonAPI.kt
> +    )
This needs to be a repo pattern

2025-04-11 11:11 UTC, hannibal002 requested changes
When i click on a player, for half a second one of the 4 people in the inventory dissapear, i only see three. then the inventory closes and i tp to them

2025-04-11 11:11 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonApi.kt
> +    private val playerClassRegex by patternGroup.pattern(
please reuse this: https://github.com/hannibal002/SkyHanni/blob/a3934343116d8870b4f07a0332b5b320dad2f9fd/src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonRankTabListColor.kt#L27

maybe move it in dungeon api instead.


also what is this regex test here?
you wanna check single lines, not everything in one large string

2025-04-14 10:48 UTC, hannibal002 requested changes
the role of sabi_love43 does not show up

![image](https://github.com/user-attachments/assets/43788598-4c8c-4740-96ed-496b95fc44da)

![image](https://github.com/user-attachments/assets/5a0f6657-5f42-4af6-9475-bc91bd7944a0)
Header:

§r§bYou are playing on §r§e§lMC.HYPIXEL.NET§r
§r§r§r§r§s§r

Body:

'         §r§b§lParty §r§f(5)'
'§8[§r§6428§r§8] §r§bhannibal2 §r§7☢ §r§f(§r§dArcher XLVI§r§f)'
' Ultimate: §r§e§r§aReady'
' Revive Stones: §r§c0'
'§8[§r§e108§r§8] §r§bFuziorio §r§f(§r§dArcher VIII§r§f)'
' Ultimate: §r§e§r§aReady'
' Revive Stones: §r§c0'
'§8[§r§721§r§8] §r§7sabi_love43 §r§f(§r§dArcher 0§r§f)'
' Ultimate: §r§e§r§aReady'
' Revive Stones: §r§c0'
'§8[§r§f51§r§8] §r§aDundertrubbel §r§7♲ §r§f(§r§dHealer X§r§f)'
' Ultimate: §r§e§r§aReady'
' Revive Stones: §r§c1'
'§8[§r§722§r§8] §r§aNnemS §r§f(§r§dBerserk IV§r§f)'
' Ultimate: §r§e55s'
' Revive Stones: §r§c0'
'       §r§2§lPlayer Stats'
'§a§lDowned: §r§7NONE'
' Time: §r§eN/A'
' Revive: §r§cN/A'
'§a§lTeam Deaths: §r§f0'
' Team Damage Dealt: §r§c2M❤'
' Team Healing Done: §r§c2.4k❤'
' Your Milestone: §r§e☄❶'
' §r§7(22.1% to ❷)'
'§a§lDiscoveries: §r§f1'
' Secrets Found: §r§b1'
' Crypts: §r§60'
'       §r§3§lDungeon Stats'
'§b§lDungeon: §r§7Catacombs'
' Opened Rooms: §r§56'
' Completed Rooms: §r§d5'
' Secrets Found: §r§e3.3%'
' Time: §r§601m 13s'
'§b§lPuzzles: §r§f(2)'
' ???: §r§7[§r§6§l✦§r§7]'
' ???: §r§7[§r§6§l✦§r§7]'
'       §r§6§lAccount Info'
'§e§lProfile: §r§aZucchini'
' Pet Sitter: §r§bN/A'
' Bank: §r§61B/419M'
' Interest: §r§e3 Hours'
'§e§lSkills: §r§aCombat 60: §r§c§lMAX'
' Speed: §r§f✦235'
' Strength: §r§c❁3316'
' Crit Chance: §r§9☣302'
' Crit Damage: §r§9☠2603'
' Attack Speed: §r§e⚔49'
'§e§lEvent: §r§cSeason of Jerry'
' Starts In: §r§e27m'
'§e§lElection: §r§b32h'
' §r§dDiaz: §r§d||||||§r§f|||| §r§f(52%)'
' §r§bMarina: §r§b||||§r§f|||||| §r§f(31%)'
' §r§eCole: §r§e|§r§f||||||||| §r§f(9%)'

Footer:

§r
§r§r§a§lActive Effects§r
§r§r§7§r§7You have §r§e2 §r§7active effects. Use "§r§6/effects§r§7" to see them!§r
§r§r§eHaste III§r§r§r
§r§r§r§r§s§r
§r§r§d§lCookie Buff§r
§r§r§f3 years§r
§r§r§r§r§s§r
§r§r§6§lDungeon Buffs§r
§r§r§fBlessing of Wisdom X§r
§r§r§r§r§s§r
§r§r§aRanks, Boosters & MORE! §r§c§lSTORE.HYPIXEL.NET§r

Widgets:
AREA : 
§b§lDungeon: §r§7Catacombs

PROFILE : 
§e§lProfile: §r§aZucchini

BANK : 
 Bank: §r§61B/419M

INTEREST : 
 Interest: §r§e3 Hours
§e§lSkills: §r§aCombat 60: §r§c§lMAX
 Speed: §r§f✦235
 Strength: §r§c❁3316
 Crit Chance: §r§9☣302
 Crit Damage: §r§9☠2603
 Attack Speed: §r§e⚔49

ELECTION : 
§e§lElection: §r§b32h
 §r§dDiaz: §r§d||||||§r§f|||| §r§f(52%)
 §r§bMarina: §r§b||||§r§f|||||| §r§f(31%)
 §r§eCole: §r§e|§r§f||||||||| §r§f(9%)

EVENT : 
§e§lEvent: §r§cSeason of Jerry
 Starts In: §r§e27m

DUNGEON_STATS : 
 Opened Rooms: §r§56
 Completed Rooms: §r§d5
 Secrets Found: §r§e3.3%
 Time: §r§601m 13s

OLD_PET_SITTER : 
 Pet Sitter: §r§bN/A

DUNGEON_PUZZLE : 
§b§lPuzzles: §r§f(2)
 ???: §r§7[§r§6§l✦§r§7]
 ???: §r§7[§r§6§l✦§r§7]

DUNGEON_PARTY : 
         §r§b§lParty §r§f(5)
§8[§r§6428§r§8] §r§bhannibal2 §r§7☢ §r§f(§r§dArcher XLVI§r§f)
 Ultimate: §r§e§r§aReady
 Revive Stones: §r§c0
§8[§r§e108§r§8] §r§bFuziorio §r§f(§r§dArcher VIII§r§f)
 Ultimate: §r§e§r§aReady
 Revive Stones: §r§c0
§8[§r§721§r§8] §r§7sabi_love43 §r§f(§r§dArcher 0§r§f)
 Ultimate: §r§e§r§aReady
 Revive Stones: §r§c0
§8[§r§f51§r§8] §r§aDundertrubbel §r§7♲ §r§f(§r§dHealer X§r§f)
 Ultimate: §r§e§r§aReady
 Revive Stones: §r§c1
§8[§r§722§r§8] §r§aNnemS §r§f(§r§dBerserk IV§r§f)
 Ultimate: §r§e55s
 Revive Stones: §r§c0

DUNGEON_PLAYER_STATS : 
       §r§2§lPlayer Stats
§a§lDowned: §r§7NONE
 Time: §r§eN/A
 Revive: §r§cN/A
§a§lTeam Deaths: §r§f0
 Team Damage Dealt: §r§c2M❤
 Team Healing Done: §r§c2.4k❤
 Your Milestone: §r§e☄❶
 §r§7(22.1% to ❷)
§a§lDiscoveries: §r§f1
 Secrets Found: §r§b1
 Crypts: §r§60

DUNGEON_ACCOUNT_INFO_LINE : 
       §r§6§lAccount Info

DUNGEON_STATS_LINE : 
       §r§3§lDungeon Stats

2025-04-14 11:28 UTC, merged