Improvement: Secret chime
hannibal00212/SkyHanni pull request #2521
Opened 2024-09-15 18:33 UTC by Ovi-111

## What
The Secret Chime feature now functions with item pickups and bat kills.

## Changelog Improvements
+ Made the Secret Chime to work with item pickups and bat kills. - Ovi_1

2024-09-16 08:37 UTC, hannibal002 requested changes

2024-09-16 08:37 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonSecretChime.kt
> +    private val secretItems = listOf(
please put that into the repo

2024-09-16 09:44 UTC, Ovi-111 commented on src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonSecretChime.kt
> +    private val secretItems = listOf(
did you mean something like this.

2024-10-11 21:26 UTC, ItsEmpa requested changes

2024-10-11 21:26 UTC, ItsEmpa commented on src/main/java/at/hannibal2/skyhanni/features/dungeon/DungeonSecretChime.kt
> +    private var dungeonSecretItems = listOf<NEUInternalName>()
would be better if this was a set

2024-10-11 23:53 UTC, CalMWolfs approved these changes
worked for me

2024-10-13 09:58 UTC, hannibal002 requested changes
It worked.
But the ItemAdd event is not ideal for this scenario: when you use a dungeon sack event, the sound plays after the sack chat message happens, couple seconds delayed. maybe rather use the inventory add event and additionally check the item stack entity removal for secrets that are picked up (maybe even by other players)

2025-01-29 19:06 UTC, hannibal002 approved these changes

2025-01-29 19:06 UTC, merged