Improvement: Armor Stack Display
hannibal00212/SkyHanni pull request #2527
Opened 2024-09-16 16:44 UTC by Ovi-111

## What
Hides Crimson armor stacks from action bar when "Armor Stack Display" is enabled.
also separated stackSymbol for later use making detection of armor type easier.

## Changelog Improvements
+ Hides armor stacks from action bar  when "Armor Stack Display" is enabled. - Ovi_1

2024-09-17 06:56 UTC, hannibal002 requested changes

2024-09-17 06:56 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/combat/ArmorStackDisplay.kt
> +        stackCount = (stackPattern.findMatcher(actionBarText) { group("stack") } ?: "0").toInt()
you can merge those two findMatcher calls

2024-09-17 06:56 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/combat/ArmorStackDisplay.kt
> +        config.position.renderString("§6§l$stackCount$stackSymbol", posLabel = "Armor Stack Display")
please build the display in the action bar update, not in the render event.

2024-09-17 06:56 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/combat/ArmorStackDisplay.kt
> +        val updatedActionBarText = actionBarText.replace(Regex("\\$stackPattern?"), "").trim()
please cache the regex object

2024-09-18 07:59 UTC, closed without merging

2024-09-18 08:00 UTC, Ovi-111 commented
need to change regex so that armorstack detection works properly