Feature: Mute High Heat sound in the Magma Fields
hannibal00212/SkyHanni pull request #2573
Opened 2024-09-22 22:11 UTC by martimavocado

## What
adds a toggle to mute the high heat sound in the magma fields  when at or above 90 heat

[suggestion](https://canary.discord.com/channels/997079228510117908/1287530198094450729)

## Changelog New Features
+ Added a toggle to mute the high heat sound in the Magma Fields. - martimavocado

2024-09-22 22:12 UTC, Thunderblade73 requested changes
Please check the heat level. Since we don't want to silence something unintentional all the time.

2024-09-23 05:11 UTC, hannibal002 requested changes

2024-09-23 05:11 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/HighHeatSound.kt
> +    private fun isEnabled() = config.muteHighHeat && MiningAPI.inCrystalHollows() && MiningAPI.heat >= 90
please check first for the location, then access the config.

2024-09-23 05:11 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/HighHeatSound.kt
> +        if (isEnabled()) return
this feels wrong

2024-09-23 05:11 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/HighHeatSound.kt
> +    private fun isEnabled() = config.muteHighHeat && MiningAPI.inCrystalHollows() && MiningAPI.heat >= 90
The heat check should be part of `onSound()`, not `IsEnabled()` (low heat still means the feature is enabled)

2024-09-23 05:11 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/data/MiningAPI.kt
> +    val heatPattern by group.pattern(
please add regex tests

2024-10-16 09:55 UTC, ItsEmpa requested changes

2024-10-16 09:55 UTC, ItsEmpa commented on src/main/java/at/hannibal2/skyhanni/data/MiningAPI.kt
> +    var lastHeatUpdate = SimpleTimeMark.farPast()
these 2 should also have private setters

2024-10-18 02:45 UTC, CalMWolfs approved these changes
code lgtm

2024-10-26 11:45 UTC, ItsEmpa requested changes
just this one nitpick

2024-10-26 11:45 UTC, ItsEmpa commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/HighHeatSound.kt
> +        if (!(LocationUtils.playerLocation().y <= 65.0 && MiningAPI.heat >= 90)) return
```suggestion
        if (LocationUtils.playerLocation().y > 65.0 || MiningAPI.heat < 90) return
```

2025-06-09 14:47 UTC, hannibal002 commented
@martimavocado bump merge conflicts

2025-06-10 08:42 UTC, merged