Fix: Bottle counting for Experiments Profit Tracker
hannibal00212/SkyHanni pull request #2594
Opened 2024-09-25 17:56 UTC by ILike2WatchMemes

## What
Added bottle counting for the in-table inventory.

## Changelog Fixes
+ Fixed bottle counting for Experiments Profit Tracker. - ILike2WatchMemes
    * Now counts bottles applied inside the table.

2024-09-25 17:57 UTC, ILike2WatchMemes commented
no idea why it got put as draft, danke iBlali!

2024-09-28 19:52 UTC, hannibal002 requested changes

2024-09-28 19:52 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/experimentationtable/ExperimentsProfitTracker.kt
> +        experienceBottlePattern.matchMatcher(stack.displayName.removeColor()) {
use internal name, not display name

2024-09-29 08:03 UTC, hannibal002 approved these changes

2024-09-29 08:03 UTC, merged