Feature: Fann pet leveling costs Coins/XP and XP/Bits
hannibal00212/SkyHanni pull request #2604
Opened 2024-09-26 22:35 UTC by minhperry

## What
https://discord.com/channels/997079228510117908/1192656223741427804

<details>
<summary>Images</summary>

![image](https://github.com/user-attachments/assets/fd1fe9c4-d368-43e0-a9bd-c6a972cd1131)

![image](https://github.com/user-attachments/assets/20f0c84a-b092-49b3-ba41-5da276daf4c8)

</details>

## Changelog New Features
+ Added Fann leveling cost coins per XP and XP per bit - minhperry

2024-10-08 07:10 UTC, CalMWolfs requested changes

2024-10-08 07:10 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/FannCostConfig.java
> +    @ConfigOption(name = "Coins/XP", desc = "Shows coins per XP in Fann menu")
```suggestion
    @ConfigOption(name = "Coins/XP", desc = "Shows coins per XP in Fann menu.")
```

2024-10-08 07:10 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/FannCostConfig.java
> +    @ConfigOption(name = "XP/Bits", desc = "Shows XP per bit in Fann menu")
```suggestion
    @ConfigOption(name = "XP/Bits", desc = "Shows XP per bit in Fann menu.")
```

2024-10-08 07:10 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/inventory/FannCost.kt
> +    }
im sure a function that does this is already in RegexUtils

2024-10-08 07:10 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/inventory/FannCost.kt
> +        UNTIL_LEVEL
```suggestion
        UNTIL_LEVEL,
```

2024-10-08 07:10 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/inventory/FannCost.kt
> +    }
There should be stuff that does this in NumberUtil

2024-10-08 07:10 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/inventory/FannCost.kt
> +    }
RegexUtils has groupOrNull which then you can elvis operator to 0

2024-10-08 07:10 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/inventory/FannCost.kt
> +            val matcher = durationPattern.matcher(linePlain)
should use Pattern.firstMatcher(list)

2024-10-08 07:10 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/inventory/FannCost.kt
> +        val slot24 = event.inventoryItems[24]
instead of assigning a variable then checking if it is null, just check if slot 24 is null wiht an elvis operator to then return from the function

2024-10-08 07:10 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/inventory/FannCost.kt
> +    }
This seems like a cool function that could be used elsewhere in the mod, maybe move it to a utils class such as collection utils

2024-10-08 07:10 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/inventory/FannCost.kt
> +    )
all of these need regex tests, they also need named pattern groups and none of them should include triple quotes

2024-11-14 03:44 UTC, minhperry commented
I don't think I can continue this any time soon, feel free to continue

2024-11-19 19:04 UTC, hannibal002 requested changes

2024-11-19 19:04 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/FannCost.kt
> +        "Will take: (?<day>\\d+)d (?<hr>\\d{1,2})h (?<min>\\d{1,2})m (?<sec>\\d{1,2})s",
We do have time formatting functions already. Please just check against `Will Take: (?<time>.*)`

2024-11-19 19:04 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/FannCost.kt
> +    private fun <T> Pattern.read(lore: List<String>, func: (String) -> T): T? {
Please do not work with the group number of patterns, rather use the group name instead.

2024-11-19 19:04 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/FannCost.kt
> +                val days = matcher.groupOrNull("day")?.toInt() ?: 0
can all be replaced with `TimeUtils.getDuration()`

2024-12-08 20:19 UTC, minhperry commented
what...

2024-12-08 20:30 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/utils/CollectionUtils.kt
> +    fun MutableList<T>.insertLineAfter(pattern: Pattern, content: T) {
```suggestion
    fun <T> MutableList<T>.insertLineAfter(pattern: Pattern, content: T) {
```

2024-12-08 20:45 UTC, minhperry commented
this was not tested with bits yet because I don't have the Turbo option unlocked.

2025-04-26 18:53 UTC, minhperry commented
Finally coming back to this reviving it from the graveyard

2025-04-26 18:53 UTC, hannibal002 commented
Welcome back o/

2025-05-14 10:05 UTC, minhperry commented
Closing this because #3969 use a cached approach

2025-05-14 10:05 UTC, closed without merging