Feature: Show unique hoppity eggs in the warp menu
hannibal00212/SkyHanni pull request #2625
Opened 2024-09-30 19:46 UTC by martimavocado

## What
adds a way to quickly check every island for missing hoppity eggs

<details>
<summary>Images</summary>

![image](https://github.com/user-attachments/assets/e233bc42-129b-4397-b923-a44fb87780d0)

![image](https://github.com/user-attachments/assets/c8f53b4a-a775-402c-a441-60170a8a11cd)

</details>

## Changelog New Features
+ Added a way to check your missing unique hoppity eggs in the warp menu. - martimavocado

2024-09-30 19:55 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/features/event/hoppity/WarpMenuUniques.kt
> +            event.toolTip.add("§7Collected: ${if (collectedEggs == maxEggs) "§a" else ""}$collectedEggs/$maxEggs")
I feel like this could look better directly below the gray warp command, so I believe index 1

2024-09-30 20:09 UTC, hannibal002 commented
Please add the information what you collect here as well. Otherwise it's pretty hard to find what mod or what feature that is when someone just searches for "collected" in configs.

Also an option to hide when maxed would be nice

2024-09-30 20:26 UTC, martimavocado commented
> Also an option to hide when maxed would be nice

should a dropdown in the config, now that we would have multiple toggles for the same feature

2024-09-30 20:29 UTC, hannibal002 commented
> should a dropdown in the config, now that we would have multiple toggles for the same feature

Please avoid using drop downs for enable/disable options that way. They don't have a default "disable everything" state

2024-10-08 06:49 UTC, CalMWolfs approved these changes
workjed for me even though it wasnt Hoppity's

2024-10-08 21:45 UTC, hannibal002 requested changes
Idk what is going on for those two
![image](https://github.com/user-attachments/assets/5b25c442-0f37-4a84-93c4-13997dc20c52)
![image](https://github.com/user-attachments/assets/d6974588-b426-4b6c-aeac-d1b61a8140a7)

2024-10-08 21:45 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/event/hoppity/WarpMenuUniques.kt
> +        "^§[ab](?<name>[\\w ']+)(?:§7 - §b.*)?\$"
Please add a regex test

2024-10-08 21:45 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/event/hoppity/WarpMenuUniques.kt
> +    private val collectedEggStorage: MutableMap<IslandType, MutableSet<LorenzVec>>
please return null if it is null

2024-10-08 21:45 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/event/hoppity/WarpMenuUniques.kt
> +            val collectedEggs = collectedEggStorage[island]?.size ?: 0
please return here if the storage is null instead of using the data from it

2024-10-08 21:45 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/event/hoppity/WarpMenuUniques.kt
> +        if (!config.uniquesWarpMenu) return
Please check for "on skyblock" before accessing the config

2024-10-08 21:45 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/event/hoppity/HoppityEggsConfig.java
> +    @FeatureToggle
this is no standalone feature, doesnt need the feature toggle annotation

2024-10-08 21:47 UTC, hannibal002 commented
Also please edit the changelog so that it is clean what the feature does, now what you can do with it.

2024-10-09 08:26 UTC, merged