Feature: Stash Warning Compact
hannibal00212/SkyHanni pull request #2639
Opened 2024-10-02 01:25 UTC by DavidArthurCole

## What
Added a compactor for the stash warning messages.

## Changelog New Features
+ Added compact for "items in stash" warnings. - Daveed

2024-10-02 02:06 UTC, DavidArthurCole commented
Fire, this already got done in a similar way in #2013, which has had conflicts since June. So, I guess this is a continuation PR, now?

2024-10-02 07:55 UTC, hannibal002 commented
> Fire, this already got done in a similar way in #2013, which has had conflicts since June. So, I guess this is a continuation PR, now?

agreed. will close the other pr

2024-10-08 02:23 UTC, CalMWolfs requested changes
Some things I saw
would also be good to include an image of the option both on compact mode and the default hypixel message but these arent necessary

2024-10-08 02:23 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/chat/StashCompact.kt
> +    private fun isEnabled() = config.stashWarnings != ChatConfig.StashHandlerType.NONE
missing skyblock check

2024-10-08 02:23 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/features/chat/ChatConfig.java
> +        NONE("None (Show all)"),
Maybe could indicate somehow that this means showing the default hypixel stash message

2024-10-09 12:57 UTC, CalMWolfs approved these changes

2024-10-13 14:20 UTC, hannibal002 requested changes
The format doesn't look like SkyHanni to me. The colors are "off". Please use yellow/white/red ish colors
![image](https://github.com/user-attachments/assets/d1182575-dbc8-451f-b623-d08b76309af7)

2024-10-13 14:20 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/chat/StashCompact.kt
> +            groupOrNull("count")?.replace(",", "")?.toIntOrNull()?.let { count ->
`.replace(",", "")?.toIntOrNull()` can be replaced with `.formatIntOrNull()`

2024-10-13 14:20 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/chat/StashCompact.kt
> +            groupOrNull("count")?.replace(",", "")?.toIntOrNull()?.let { count ->
`.replace(",", "")?.toIntOrNull()` can be replaced with `.formatIntOrNull()`

2024-10-13 14:20 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/chat/StashCompact.kt
> +            prefix = false,
Users will have a hard time finding this feature when they want to disable it. It's default enabled and has no prefix. Maybe we should still show the prefix?

2024-10-13 19:29 UTC, hannibal002 approved these changes

2024-10-13 19:29 UTC, merged