Made it so you can shift click to disable features like it says
hannibal00212/SkyHanni pull request #2650
Opened 2024-10-03 12:50 UTC by NopoTheGamer

## What
Chat popups said "shift click or control click to disable" however shift clicking never worked
I do make this function always return false but I searched around on github and couldn't really find a mod that used this "Insertion" feature thingy that I'm disabling so I think its fine

<details>
<summary>Images</summary>

![image](https://github.com/user-attachments/assets/bddcb6af-81b6-44b5-bbf9-6f4c5a8a10b7)

</details>

## Changelog Fixes
+ Fixed not being able to shift click chat messages. - nopo
    * Extra info.

2024-10-03 20:57 UTC, CalMWolfs approved these changes

2024-10-05 08:08 UTC, hannibal002 requested changes
This breaks Skytils
![grafik](https://github.com/user-attachments/assets/c07495f1-91e6-4dd5-9f8e-ae583ebfc5c5)

2024-10-05 08:35 UTC, NopoTheGamer commented
> This breaks Skytils ![grafik](https://private-user-images.githubusercontent.com/24389977/373856622-c07495f1-91e6-4dd5-9f8e-ae583ebfc5c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMTc2MTUsIm5iZiI6MTcyODExNzMxNSwicGF0aCI6Ii8yNDM4OTk3Ny8zNzM4NTY2MjItYzA3NDk1ZjEtOTFlNi00ZGQ1LTlmOGUtYWU1ODNlYmZjNWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDA4MzUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNDk5MmZmMDZhNDEwYjAxOThiM2M2NmJkNTg5OTNiMDdjMDk3MThlODEwZjkxN2MxMDA3MDg2ZWVlMmRiOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wFbpCXX5B1PtpAnIzASwjmsu20R2u2wiLdHRN-2UFaU)

not true

2024-10-05 08:39 UTC, hannibal002 approved these changes
lieception

2024-10-05 08:39 UTC, merged