Fix: error punctuation
hannibal00212/SkyHanni pull request #2651
Opened 2024-10-03 13:12 UTC by NopoTheGamer

## What
very important

<details>
<summary>Images</summary>

![image](https://github.com/user-attachments/assets/794da1ad-a460-47e1-9ae2-93d2effd8250)

</details>

## Changelog New Features
+ Cool new feature. - your_name_here
    * extra info

## Changelog Improvements
+ Improved cool feature. - your_name_here
    * Extra info.

## Changelog Fixes
+ Fixed cool feature. - your_name_here
    * Extra info.

## Changelog Technical Details
+ Something technical you changed in the backend. - your_name_here
    * Extra info.

## Changelog Removed Features
+ Removed cool feature. - your_name_here
    * Extra info.

exclude_from_changelog

2024-10-03 20:58 UTC, CalMWolfs approved these changes

2024-10-05 07:02 UTC, hannibal002 requested changes

2024-10-05 07:02 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
> +    fun optionalAn(string: String): String {
This function will throw an error when given an empty string

2024-10-05 07:55 UTC, hannibal002 approved these changes

2024-10-05 07:55 UTC, merged