Add: Notify when a player join/leave your lobby
hannibal00212/SkyHanni pull request #2653
Opened 2024-10-03 14:30 UTC by superhize

## What
- #2213 

## Changelog New Features
+ Cool new feature. - your_name_here
    * extra info

## Changelog Improvements
+ Improved cool feature. - your_name_here
    * Extra info.

## Changelog Fixes
+ Fixed cool feature. - your_name_here
    * Extra info.

## Changelog Technical Details
+ Something technical you changed in the backend. - your_name_here
    * Extra info.

## Changelog Removed Features
+ Removed cool feature. - your_name_here
    * Extra info.

2024-10-03 14:36 UTC, martimavocado reviewed
you had some small typos

2024-10-03 14:36 UTC, martimavocado commented on src/main/java/at/hannibal2/skyhanni/config/features/markedplayer/MarkedPlayerConfig.java
> +        @ConfigOption(name = "Join Message", desc = "Configure the message when someone join.\n&& is replaced with the minecraft color code §.\n%s is replaced with the player name.")
```suggestion
        @ConfigOption(name = "Join Message", desc = "Configure the message when someone joins.\n&& is replaced with the minecraft color code §.\n%s is replaced with the player name.")
```

2024-10-03 14:36 UTC, martimavocado commented on src/main/java/at/hannibal2/skyhanni/config/features/markedplayer/MarkedPlayerConfig.java
> +        @ConfigOption(name = "Players List", desc = "Players list you want to be notified for.\n§cCase sensitive, separated by comma.")
```suggestion
        @ConfigOption(name = "Players List", desc = "The list of players you want to be notified for.\n§cCase sensitive, separated by commas.")
```

2024-10-03 14:36 UTC, martimavocado commented on src/main/java/at/hannibal2/skyhanni/config/features/markedplayer/MarkedPlayerConfig.java
> +        @ConfigOption(name = "Left Message", desc = "Configure the message when someone leave.\n&& is replaced with the minecraft color code §.\n%s is replaced with the player name.")
```suggestion
        @ConfigOption(name = "Left Message", desc = "Configure the message when someone leaves.\n&& is replaced with the minecraft color code §.\n%s is replaced with the player name.")
```

2024-10-08 03:23 UTC, CalMWolfs requested changes

2024-10-08 03:23 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/features/markedplayer/MarkedPlayerConfig.java
> +        @ConfigOption(name = "Use Prefix", desc = "Should the [SkyHanni] prefix should be in the join/leave message ?")
The formatting around the question mark is incorret

2025-07-11 04:15 UTC, CalMWolfs approved these changes

2025-07-11 04:15 UTC, merged