Feature: Hoppity Purse Blocker
hannibal00212/SkyHanni pull request #2664
Opened 2024-10-04 20:03 UTC by DavidArthurCole

## What
Adds a blocker to prevent opening Hoppity's shop without coins.

## Changelog New Features
+ Added a feature to block opening Hoppity's trade menu from Abiphone calls if you do not have coins in your purse. - Daveed

2024-10-04 20:51 UTC, Thunderblade73 reviewed
I don't see any problem in code (but I also don't understand why this exist or the description of the config is bad)

2024-10-04 20:51 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCallWarning.kt
> +            actionName = "open bank menu",
```suggestion
            actionName = "Open bank menu",
```

2024-10-04 21:02 UTC, DavidArthurCole commented on src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCallWarning.kt
> +            actionName = "open bank menu",
![image](https://github.com/user-attachments/assets/5b991daf-ea6f-4b77-9dd3-bcd001a6e75f)

2024-10-04 21:02 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCallWarning.kt
> +            actionName = "open bank menu",
ok

2024-10-04 21:03 UTC, DavidArthurCole commented
> I don't see any problem in code (but I also don't understand why this exist or the description of the config is bad)

Once you open the hoppity call (i.e., click Yes), if you don't have coins, you lose out on the offer - so, block opening the call if you don't have coins. Not sure if the config needs updating.

2024-10-04 21:04 UTC, Thunderblade73 commented
Yeah, that makes sense. But that isn't what the config reads to me. Since I thought it was about the normal hoppity shop, which didn't make sense.

2024-10-04 21:20 UTC, Thunderblade73 approved these changes

2024-10-08 02:50 UTC, CalMWolfs requested changes

2024-10-08 02:50 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityCallWarning.kt
> +    fun onCommandSend(event: MessageSendToServerEvent) {
should have some sort of skyblock check

2024-10-08 22:27 UTC, CalMWolfs approved these changes

2024-10-16 10:42 UTC, merged