Feature: Inventory Focus Mode
hannibal00212/SkyHanni pull request #2694
Opened 2024-10-08 09:01 UTC by Thunderblade73

## What
Only show the name of the item when in focus mode.

## Discord
https://discord.com/channels/997079228510117908/1292289101340344453

## Changelog New Features
+ Inventory Focus Mode. - Thunderblade73

2024-10-08 09:05 UTC, jani270 commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
> +    @ConfigOption(name = "Focus Mode",desc="")
🤓 
```suggestion
    @ConfigOption(name = "Focus Mode", desc="")
```

2024-10-08 09:06 UTC, CalMWolfs requested changes

2024-10-08 09:06 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/FocusModeConfig.java
> +    public boolean enable = false;
Both of these should be enabled not enable

2024-10-08 09:06 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
> +    @ConfigOption(name = "Focus Mode",desc="")
```suggestion
    @ConfigOption(name = "Focus Mode", desc="")
```

2024-10-08 09:12 UTC, jani270 commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
> +    @ConfigOption(name = "Focus Mode",desc="")
late

2024-10-08 09:13 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/InventoryConfig.java
> +    @ConfigOption(name = "Focus Mode",desc="")
> late

😭

2024-10-09 08:45 UTC, CalMWolfs approved these changes
i was very focussed while using this

2024-10-09 11:28 UTC, merged