Feature: Rabbit the Fish GUI Close Blocker
hannibal00212/SkyHanni pull request #2712
Opened 2024-10-10 23:58 UTC by DavidArthurCole

## What
Adds a config option for blocking closure of the Meal Egg UI if Rabbit the Fish is present.
Also moved the Warp Menu stuff into its own accordion since there was more than one slider for the same feature-set.

## Changelog New Features
+ Added ability to block closing Meal Eggs that have Rabbit the Fish inside. - Daveed

## Changelog Technical Details
+ Moved Hoppity Warp Menu config to `HoppityWarpMenuConfig`. - Daveed

2024-10-15 02:52 UTC, CalMWolfs requested changes

2024-10-15 02:52 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityRabbitTheFishChecker.kt
> +     *
this seems to be missing

2024-10-15 03:07 UTC, CalMWolfs approved these changes
code lgtm

2024-10-16 10:56 UTC, hannibal002 requested changes
could not test in game, but code looks good

2024-10-16 10:56 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/mixins/transformers/gui/MixinGuiContainer.java
> +            HoppityRabbitTheFishChecker.warn();
move the warn function into the shouldContinueWithKeypress function

2024-10-16 10:56 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityRabbitTheFishChecker.kt
> +    fun onInventoryUpdate(event: InventoryUpdatedEvent) {
is there a reason we use inventory update over inventory fully opdated event here?

2024-10-16 17:47 UTC, hannibal002 approved these changes

2024-10-16 17:47 UTC, merged