Feature: Chocolate Factory Booster Cookie Blocker
hannibal00212/SkyHanni pull request #2713
Opened 2024-10-11 00:17 UTC by DavidArthurCole

## What
https://discord.com/channels/997079228510117908/1293985352754794556
Adds config option for blocking `/cf` when no Booster Cookie is active.

## Changelog New Features
+ Added ability to block opening Chocolate Factory when Booster Cookie is inactive. - Daveed

2024-10-11 10:27 UTC, CalMWolfs approved these changes
Worked for me

2024-10-13 13:58 UTC, hannibal002 requested changes
Maybe look at this
https://github.com/hannibal002/SkyHanni/blob/0864f1e1de572b955f356053ad9cb73be24d5683/src/main/java/at/hannibal2/skyhanni/features/event/carnival/CarnivalReminder.kt#L97

2024-10-13 13:58 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/chocolatefactory/ChocolateFactoryBlockOpen.kt
> +                    action = { HypixelCommands.bazaar("Booster Cookie") },
i dont think this will work without a  booster cookie. how about warping to hub and starting a lovely pathfind to the bazaar npc?

2024-10-13 18:53 UTC, hannibal002 approved these changes

2024-10-13 18:53 UTC, merged