Feature: Block Strength
hannibal00212/SkyHanni pull request #2778
Opened 2024-10-20 17:19 UTC by Thunderblade73

## Dependencies
- https://github.com/hannibal002/SkyHanni-REPO/pull/270

## What
Shows how many ticks you need to break any block with your mining speed.

It opens the skyblock menu to collect up to date stats.

<details>
<summary>Images</summary>

![image](https://github.com/user-attachments/assets/17801e2c-86fc-4538-a321-bb64cf17c1b4)

</details>

## Changelog New Features
+ Added /shblockstrength. - Thunderblade73
    * Shows how many ticks you need to break any block with your mining speed.

## Changelog Technical Details
+ Added Renderable.renderAndScale. - Thunderblade73
+ Added the title of the Inventory to InventoryCloseEvent. - Thunderblade73

2024-10-20 18:54 UTC, qtlunya commented
One small issue, this won't be fully accurate with HOTM perks and tools that give extra Mining Speed only for specific types of blocks. This could probably be read from HotmAPI and the held tool's lore.

2024-10-21 10:14 UTC, Thunderblade73 commented
> One small issue, this won't be fully accurate with HOTM perks and tools/pets that give extra Mining Speed only for specific types of blocks. This could probably be read from HotmAPI and then hardcode known cases for tools/pets (or try to read it out from their lore).

I added a way to account for them now. I only implemented HOTM perks since I don't know other sources of specific speed.

2024-10-21 10:43 UTC, Thunderblade73 commented
> > One small issue, this won't be fully accurate with HOTM perks and tools/pets that give extra Mining Speed only for specific types of blocks. This could probably be read from HotmAPI and then hardcode known cases for tools/pets (or try to read it out from their lore).
> 
> I added a way to account for them now. I only implemented HOTM perks since I don't know other sources of specific speed.

Empa gave me a full list. It does now account for lapidary, Gemstone drills as well. And I also added a todo with the remaining sources.

2025-02-11 10:33 UTC, hannibal002 requested changes

2025-02-11 10:33 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/InventoryUtils.kt
> +    fun Gui.getTitle() = when (this) {
please avoid using `!!`. rather use ` ?: error("bla bla")` or use the magic file somewehre to mark those fields as non null globally

2025-04-10 09:13 UTC, hannibal002 requested changes
i cant test this feature yet.

whatever gui i try to open, this shows up. (i press e, or i click with the sb menu in my inventory
![image](https://github.com/user-attachments/assets/47964a26-c3aa-48dd-9112-8115ec697c5a)

to reproduce: 
1. make sure the repo is updated
2. run /shblockstrength
3. open any gui

2025-04-10 09:13 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/mining/BlockStrengthGuide.kt
> +                    Renderable.string(name.allLettersFirstUppercase()),
add  more info to that hover text. e.g. what does the numbers mean (the seconds, the ticks, etc)

2025-04-10 09:16 UTC, hannibal002 commented
I assume this is bc lastAssignment is far past, therefore the check sbMenuOpened is always true?

2025-04-10 09:17 UTC, hannibal002 requested changes

2025-04-10 09:17 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/mining/BlockStrengthGuide.kt
> +        if (!sbMenuOpened) return
maybe the issue is this?

2025-04-10 12:33 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/mining/BlockStrengthGuide.kt
> +        if (!sbMenuOpened) return
The issue is that the stat api is somehow broke. And the feature waits for the response of the stat api which doesn't get send, as it somehow broke

2025-04-10 13:13 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/mining/BlockStrengthGuide.kt
> +                    Renderable.string(name.allLettersFirstUppercase()),
You reference probably the old, as the screenshot above is quiet old now. Since all digits (except Block strength) are mining speed. And I think it is easily readable.
![image](https://github.com/user-attachments/assets/e262b265-7ebd-49fc-a2a7-674a66497641)

2025-04-10 13:15 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/mining/BlockStrengthGuide.kt
> +                    Renderable.string(name.allLettersFirstUppercase()),
oh wow, yeah this looks way better!
(missing addSeparators() :P)

2025-04-11 06:58 UTC, merged