Fix: Great Spook mob cooldown and timer
hannibal00212/SkyHanni pull request #2804
Opened 2024-10-23 18:41 UTC by martimavocado

## Dependencies
- https://github.com/hannibal002/SkyHanni-REPO/pull/273

## What
redoes the great spook detection via defined timestamps from the repo, also moves some stuff to renderables

## Changelog Fixes
+ Fixed the Greak Spook features. - martimavocado

2024-10-23 19:35 UTC, hannibal002 requested changes
What is broken in the existing feature?
at a glance this looks like a backend change
if this is actually a fix, please change the changelog wording to make clear what is going on here

2024-10-23 19:35 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/data/jsonobjects/repo/EventsJson.kt
> +    @Expose @SerializedName("great_spook") val greatSpook: Map<String, Long>,
instead of long use simple time mark

2024-10-23 19:35 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/event/spook/TheGreatSpook.kt
> +            if (config.get() == true) {
replace with if (contig.get()) {

2024-10-23 19:35 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/event/spook/TheGreatSpook.kt
> +            add("isGreatSpookActive: $isGreatSpookActive")
remove the "great spook" from the lines below

2024-10-23 19:48 UTC, martimavocado commented
> What is broken in the existing feature?

the previous great spook detection wasn't working, so i guess making a new one is a backend change. but the user facing fix is that the features now work

2024-10-23 19:48 UTC, nea89o commented on src/main/java/at/hannibal2/skyhanni/features/event/spook/TheGreatSpook.kt
> +            ChatUtils.userError("Fear stat not found! Please enable the Stats widget and enable the Fear stat for the best results.")
I feel like this message might be better if it only shows when the player has spawned a fear mob

2024-10-26 18:08 UTC, hannibal002 commented
Changed the format from
![image](https://github.com/user-attachments/assets/2649c545-1f22-4829-9a6f-46fc51606791)
to
![image](https://github.com/user-attachments/assets/6205167f-e5b3-4813-8d8d-4ab786b300be)

2024-10-26 18:14 UTC, merged