Improvement: Better Enchant Detection and Error Logging
hannibal00212/SkyHanni pull request #2816
Opened 2024-10-25 20:57 UTC by VixidDev

## What
Adds a regex pattern to check that a line contains only enchants (and anything else expected in a legitimate enchant line) so miscellaneous strings from elsewhere in the mod or from other mods are not messed with incorrectly. Also fixes and improves the error logging in enchant parser for some still unexplained errors.

## Changelog Improvements
+ Better enchant detection. - Vixid

2024-10-25 22:23 UTC, CalMWolfs approved these changes

2024-10-26 00:51 UTC, hannibal002 requested changes
Also please rephrase the changelog file to make clear what has changed for users. If there is nothing changed for users, change the changelog type from improvement to internal change please

2024-10-26 00:51 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/misc/items/enchants/EnchantParser.kt
> +    val enchantmentExclusivePattern by patternGroup.pattern(
add regex test

2024-10-27 20:40 UTC, hannibal002 approved these changes

2024-10-27 21:30 UTC, jani270 commented
Closing and reopening to fix auto merge not working 
![grafik](https://github.com/user-attachments/assets/2a380659-07d4-4ecd-a166-c96d76ce740d)

2024-10-27 21:56 UTC, merged