Backend: Kotlin Position
hannibal00212/SkyHanni pull request #2855
Opened 2024-10-28 15:31 UTC by ItsEmpa

## What
This PR translates the Position class into kotlin, and changes it to use more kotlin getters/setters, and cleaner code overall.
Also makes use of overloaded constructors to reduce the amount of them that have to be declared in code

## Changelog Technical Details
+ Translated Position Class to Kotlin. - Empa

2024-11-22 11:37 UTC, CalMWolfs requested changes
just a few things i saw,
also changing the center value to just be whatever the centerX value is set to is fine imo, but 4 options will no longer be centered because the old config will not migrate to the new constructor on its own (CF: customReminder, fishingHookDisplay and 2 blaze slayer options). These should probably be adressed

2024-11-22 11:37 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/core/config/Position.kt
> +    y: Int,
```suggestion
    x: Int = 0,
    y: Int = 0,
```

in the java one these were also defaulted to 0

2024-11-22 11:37 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/core/config/PositionList.kt
> +        this.addAll(List(size) { Position(0, 0) })
```suggestion
        this.addAll(List(size) { Position() })
```

2024-11-22 11:37 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/gui/TabWidgetDisplay.kt
> +                config.displayPositions.addAll(List(sizeDiff) { Position(0, 0) })
```suggestion
                config.displayPositions.addAll(List(sizeDiff) { Position() })
```

2024-11-22 11:37 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/core/config/Position.kt
> +    centerY: Boolean = false,
while this isnt used currently, it was default true before so we should probably keep consistancy, same can be said for this value in the constructor below

2024-11-22 16:16 UTC, CalMWolfs approved these changes
worked for me

2025-01-24 11:28 UTC, hannibal002 requested changes
When moving GUIs in position editor, some jump to the left corner of the screen and cant get moved away, but not all.

![image](https://github.com/user-attachments/assets/6e073c3e-b25c-444b-9f37-b526ff51365e)


my guess is this is realted to the centerX value?

2025-01-29 02:26 UTC, hannibal002 commented
Can confirm, its still this PR that causes it (after testing with latest beta branch where the bug was not there)

2025-01-29 02:39 UTC, Thunderblade73 requested changes

2025-01-29 02:39 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/config/core/config/Position.kt
> +    }
This function does not match up with the moveX/moveY functions. The wasPositive check and differentiation is lost here and the bounds edge case is also not here.
Those missing things probably account for the edge case that hannibal encounters.

2025-01-29 18:39 UTC, hannibal002 approved these changes
works for me now

2025-01-29 18:40 UTC, merged