Feature: Hoppity Alpha Features
hannibal00212/SkyHanni pull request #2940
Opened 2024-11-17 05:17 UTC by DavidArthurCole

## Dependencies
- https://github.com/hannibal002/SkyHanni/pull/2925

## What
**As with the above PR, this shouldn't get merged until the update is out.**

Because this heavily relies on the back-end that I developed while doing the fixes, the HEAD for this is based on the above PR. The actual diff for this PR can be viewed [here](https://github.com/DavidArthurCole/SkyHanni/compare/HoppityCfAlpha_FIXES...DavidArthurCole:SkyHanni:HoppityCfAlpha_FEATURES).
Adds a bunch of new features relating to the new stuff from Hoppity/CF update.

More to come on this in the coming days.

<details>
<summary>Images</summary>

</details>

## Changelog New Features
+ Added a 30s stray timer to Chocolate Factory after a meal egg is opened. - Daveed
+ Added Hoppity Event Stat text for Hitman Rabbits. - Daveed
+ Added Hoppity Collection highlighting for Resident and Hotspot rabbits. - Daveed
   * Will highlight Resident/Hotspot rabbits on your current island.
+ Added Resident Rabbit overview option to Hoppity Collection stats. - Daveed
+ Added Hitman slot tracking to see the most recent rabbits you obtained. - Daveed
   * Will show on slots with an active cooldown

2024-11-18 18:56 UTC, DavidArthurCole commented
Update tomorrow, this is ready (assuming detekt passes 😔)

2024-11-23 23:06 UTC, hannibal002 commented
![image](https://github.com/user-attachments/assets/e8136184-0e76-49f2-82c4-ec950659c8ba)

2024-11-24 00:10 UTC, hannibal002 requested changes
cant test the active hoppity stuff but looks fine overall

2024-11-24 00:10 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/event/hoppity/HoppityEventSummary.kt
> +    private val disallowListHoppityIslands by lazy {
cant we use a list of allowd islands instead, and load that from the repo via the egg location data? or is this check different here?

2024-11-24 20:34 UTC, merged