Code cleanup
hannibal00212/SkyHanni pull request #295
Opened 2023-07-05 09:35 UTC by CalMWolfs

cleaning up code and splitting it into roundLocationToBlock and getBlockBelowPlayer

2023-07-05 15:22 UTC, hannibal002 requested changes
Merge conflicts

2023-07-19 22:50 UTC, CalMWolfs commented
draft as i actually need to merge this not on google

2023-07-29 08:33 UTC, CalMWolfs commented
Finally had a chance to test this and it seems to work

2023-07-29 08:54 UTC, hannibal002 approved these changes

2023-07-29 08:55 UTC, merged