Fix: Garden Keybinds Crash
hannibal00212/SkyHanni pull request #2969
Opened 2024-11-21 08:18 UTC by ItsEmpa

## What
This PR fixes a crash related to custom garden keybinds.

## Changelog Fixes
+ Fixed Custom Garden Keybinds crash. - Empa

2024-11-21 08:21 UTC, ItsEmpa commented
also made it properly detect duplicate keybinds again

2024-11-21 16:13 UTC, DavidArthurCole requested changes
As I noted in Discord (see https://discord.com/channels/997079228510117908/1094190239532208228/1309186201235755131), this fix seems to have inadvertently enabled chat-walking while holding farming tools.

2024-11-21 16:56 UTC, DavidArthurCole approved these changes

2024-11-23 12:18 UTC, hannibal002 approved these changes
cant reproduce the crash, but can confirm this works for me still

2024-11-23 12:18 UTC, merged