Improvement: Optimal Settings
hannibal00212/SkyHanni pull request #2977
Opened 2024-11-24 00:59 UTC by ILike2WatchMemes

## What
Reworked a bit of the config, functionality and other things for the optimal settings (in the past optimal speed, now includes yaw and pitch aswell)

## Changelog Improvements
+ Improved Optimal Speed. - ILike2WatchMemes
    * Now called Optimal Settings.
    * Now includes Yaw/Pitch.

2024-11-24 11:11 UTC, hannibal002 commented
interesting idea. but please call it "garden settings" or "farming settings" in the changelog and in the config editor

2024-12-06 09:59 UTC, CalMWolfs requested changes

2024-12-06 09:59 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
> +    }
I know the othger method is in here but nothing new should be added to LorenzUtils. Would also be good if a new home was found for the other method

2025-01-07 18:33 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
> +    }
SignUtils. also please look at the current impl of rancher sign:
![image](https://github.com/user-attachments/assets/2a1bd696-4244-467d-a4bd-9cdb28f84276)

2025-01-07 19:55 UTC, rueblimaster commented on src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
> +    }
`
val signText = (this as AccessorGuiEditSign).titleSign.signText.map { it.unformattedText.removeColor() }
return tileSign.signText[1 == "Set Yaw Above!" && tileSign.signText[2] == "Set Pitch Below!"
`
is the solution

2025-05-19 08:23 UTC, rueblimaster requested changes
some small changes are for sure still needed, also as disclaimer I didn't look into the logic all to deep.
Another point I haven't mentioned yet, is that if you feel like it, the addition of the custom keybindings to this would be a welcome addition

2025-05-19 08:23 UTC, rueblimaster commented on src/main/java/at/hannibal2/skyhanni/config/features/garden/farmingsettings/CustomFarmingSettingsConfig.java
why not make 1 class CropConfig, which you then pass the strings as arguments for the suggested values?

2025-05-19 08:23 UTC, rueblimaster commented on src/main/java/at/hannibal2/skyhanni/config/features/garden/farmingsettings/FarmingSettingsConfig.java
> +        WHEN_USING("§eWhen using §5Rancher's Boots§e/§6Squeaky Mousemat"),
WHEN_USING is a bit misleading in the context of the rancher boots, my guess for what you mean is when setting the rancher boots or using the squeaky mousemat, imo WHEN_USING can stay, but the description has to be changed

2025-05-19 08:23 UTC, rueblimaster commented on src/main/java/at/hannibal2/skyhanni/features/garden/farmingsettings/FarmingSettingsAPI.kt
I'm not fine with the name of this file, as for what I can see, this isn't anything like an internal API or something like that, idk why it's like this, you can probably merge it with FarmingSettings

2025-05-19 08:23 UTC, rueblimaster commented on src/main/java/at/hannibal2/skyhanni/config/features/garden/GardenConfig.java
> +    @Category(name = "Farming Settings", desc = "Optimal Speed/Yaw/Pitch Settings")
the category name is somewhat to broad I think, maybe there would be a better name

2025-05-21 11:01 UTC, ILike2WatchMemes commented on src/main/java/at/hannibal2/skyhanni/config/features/garden/GardenConfig.java
> +    @Category(name = "Farming Settings", desc = "Optimal Speed/Yaw/Pitch Settings")
I chose Farming Settings after hannibal's suggestion, do you have any ideas of any better names? I personally think it's okay when paired with that description

2025-05-21 11:01 UTC, ILike2WatchMemes commented on src/main/java/at/hannibal2/skyhanni/features/garden/farmingsettings/FarmingSettingsAPI.kt
I agree, but I don't think merging the two files is the right decision here since having such a big file would decrease readability and maintainability

2025-05-21 11:01 UTC, ILike2WatchMemes commented on src/main/java/at/hannibal2/skyhanni/config/features/garden/farmingsettings/FarmingSettingsConfig.java
> +        WHEN_USING("§eWhen using §5Rancher's Boots§e/§6Squeaky Mousemat"),
Maybe WHEN_HOLDING?

2025-05-21 11:01 UTC, ILike2WatchMemes commented on src/main/java/at/hannibal2/skyhanni/config/features/garden/farmingsettings/CustomFarmingSettingsConfig.java
I don't understand, wdym?

2025-05-21 11:13 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/garden/farmingsettings/CustomFarmingSettingsConfig.java
all the new clases here are almost identical. the idea is to create only one class. this class is then generic and its name for the labels is depending on a para. but idk if this even works since we never tried it

2025-05-21 19:23 UTC, rueblimaster commented on src/main/java/at/hannibal2/skyhanni/config/features/garden/GardenConfig.java
> +    @Category(name = "Farming Settings", desc = "Optimal Speed/Yaw/Pitch Settings")
ye, I just thought about it when I'm scrolling through the list, if I saw "farming settings" in the garden, I'd think: huh? the other stuff isn't about farming?
maybe something to emphasize crop specific?

2025-05-21 19:24 UTC, rueblimaster commented on src/main/java/at/hannibal2/skyhanni/config/features/garden/farmingsettings/FarmingSettingsConfig.java
> +        WHEN_USING("§eWhen using §5Rancher's Boots§e/§6Squeaky Mousemat"),
using mousemat is fine, but I don't like the idea of it warning me all the time because I "use" the boots all the time

2025-05-21 19:25 UTC, rueblimaster commented on src/main/java/at/hannibal2/skyhanni/config/features/garden/farmingsettings/CustomFarmingSettingsConfig.java
I believe it works, I've tried it once before, but you should test it still for sure

2025-05-21 19:27 UTC, rueblimaster commented on src/main/java/at/hannibal2/skyhanni/config/features/garden/farmingsettings/FarmingSettingsConfig.java
> +        WHEN_USING("§eWhen using §5Rancher's Boots§e/§6Squeaky Mousemat"),
the WHEN_USING part can stay, you have to change the description tho

2025-05-21 19:33 UTC, rueblimaster requested changes

2025-05-21 19:33 UTC, rueblimaster commented on src/main/java/at/hannibal2/skyhanni/features/garden/farmingsettings/FarmingSettings.kt
> +            posLabel = "Optimal Settings Overlay",
add farming into the label

2025-05-21 19:33 UTC, rueblimaster commented on src/main/java/at/hannibal2/skyhanni/features/garden/farmingsettings/FarmingSettingsAPI.kt
if you put the config fix at the bottom of the file, and the 3 render functions towards the top, I believe it would be best.
I'd argument, that if I have to switch files all to ofter it can also be not readable?
Or an other alternative is to split this whole thing up even further, I for one would say, everythin that is rendering / display related goes into the same file

2025-07-12 23:15 UTC, CalMWolfs commented
@ILike2WatchMemes are you planning on updating this pr or can I close it

2025-07-20 17:14 UTC, ILike2WatchMemes commented
> @ILike2WatchMemes are you planning on updating this pr or can I close it

with #2999 being merged imma close it for now and maybe rebrand it as a improvement of that in the feature

2025-07-20 17:14 UTC, closed without merging