add notification when pest cooldown is over
hannibal00212/SkyHanni pull request #2981
Opened 2024-11-24 10:16 UTC by Not-a-cowfr

## What
Adds notification when pest cooldown is about to expire
(also removed fine flour as it cant be sprayed anymore)

## Changelog New Features
+ Added warning when pest cooldown is over - not_a_cow

2024-11-24 10:29 UTC, Obsidianninja11 commented on src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestWarning.kt
> +                currentMinister?.activePerks?.any { it.perkName == "Pest Eradicator" } == true)
Maybe seperate these into like 3 different vals?

2024-11-24 10:39 UTC, j10a1n15 requested changes

2024-11-24 10:39 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestWarning.kt
> +        val isFinneganMayor = currentMayor?.mayorName == "Finnegan"
dont do mayor name comparisons, do Candidate.FINNEGAN in listOf(currentMayor, currentMinister) or smth

2024-11-24 10:54 UTC, Obsidianninja11 commented on src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestWarning.kt
> +        if (LorenzUtils.inSkyBlock && Cooldown != null && !warningShown && config.pestSpawnWarning) {
Shouldn't this use isEnabled()?
Maybe also change it to `if (!...) return`

2024-11-24 16:32 UTC, j10a1n15 requested changes

2024-11-24 16:32 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestWarning.kt
> +    private var Cooldown: Double? = null
these should start lowercase

2024-11-24 16:32 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestWarning.kt
> +    val storage get() = GardenAPI.storage
since you alr put the equipment private, this might aswell be private too

2024-12-20 01:29 UTC, hannibal002 requested changes

2024-12-20 01:29 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestWarning.kt
> +                        Thread.sleep(config.sound.repeatDuration * 50L)
please use tick events instead of new threads this way

2024-12-20 02:22 UTC, hannibal002 requested changes

2024-12-20 02:22 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestWarning.kt
> +    fun onInventoryClose(event: InventoryCloseEvent) {
Missing `@SubscribeEvent`

2024-12-20 02:45 UTC, Not-a-cowfr commented
going to fix pest repell not being counted for in a bit

2024-12-22 04:30 UTC, Not-a-cowfr commented
also it always thinks its sprayed, but thats an issue with plotapi and idk why its doing that 🙏

2024-12-28 08:56 UTC, Not-a-cowfr commented
oops didn't realize `WidgetUpdateEvent` was a thing, lmk if i should be using that, ill put it off for now

2024-12-28 08:57 UTC, hannibal002 commented
> oops didn't realize `WidgetUpdateEvent` was a thing, lmk if i should be using that, ill put it off for now

Since the pr is not going to get added for another week or so, you have time to implement the widget event

2025-01-18 21:00 UTC, hannibal002 requested changes
I have also changed the chagnelog formatting. please edit it if youre not happy with my changes

2025-01-18 21:00 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestWarning.kt
> +        cooldown = BASE_PEST_COOLDOWN * (sprayMultiplier * (1 - equipmentPestCooldown.div(100.0)) * repellentMultiplier)
why do we update the cooldown every second?

2025-01-18 21:00 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestWarning.kt
> +            "§cPest spawn cooldown has expired",
the message doesnt say much whats happening/what is going on/what the user should do next/why they get this message.

2025-01-31 05:37 UTC, Not-a-cowfr commented
https://github.com/hannibal002/SkyHanni/pull/3333

https://github.com/hannibal002/SkyHanni/pull/3343

2025-01-31 05:37 UTC, closed without merging