Improvement: `/shedittracker` with Bucketed Item Tracker(s)
hannibal00212/SkyHanni pull request #2987
Opened 2024-11-25 01:31 UTC by DavidArthurCole

## What
An actually functional version following up from https://github.com/hannibal002/SkyHanni/pull/2582
This came up again today as I'm gonna start looking into making the Pest Tracker bucketed as well. For now this only affects the corpse tracker.

## Changelog Improvements
+ Mineshaft Corpse Tracker now supports `/shedittracker`. - Daveed

2025-01-30 17:31 UTC, hannibal002 requested changes
maybe the migration failed, but after iterating through all variants, the text went blank.
![image](https://github.com/user-attachments/assets/ee63123f-b9f8-4337-8ae4-780c8ab9328f)

2025-01-30 17:49 UTC, DavidArthurCole commented
![image](https://github.com/user-attachments/assets/d487391f-f633-45a9-a367-1e4db38112b9)

Yeah, I can replicate. I'll have to look into my logic.

2025-01-30 17:51 UTC, hannibal002 requested changes

2025-01-30 17:51 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestType.kt
> +    UNKNOWN(
can we use nullable instead?

2025-01-30 17:51 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/tracker/SkyHanniBucketedItemTracker.kt
> +    private fun getSelectedBucket(): E? {
unused?

2025-01-30 18:04 UTC, DavidArthurCole commented on src/main/java/at/hannibal2/skyhanni/features/garden/pests/PestType.kt
> +    UNKNOWN(
We can't use null, no - null is the BucketTracker way of saying that data is coming from all buckets, and the maps it defines are around Enum<E>, which shouldn't be nullable type keys

2025-01-31 16:06 UTC, hannibal002 approved these changes

2025-01-31 16:06 UTC, merged