Improvement: Coop Support for Spray Timer
hannibal00212/SkyHanni pull request #3017
Opened 2024-12-03 19:33 UTC by Chissl

## Dependencies
- https://github.com/hannibal002/SkyHanni-REPO/pull/299

## What
Adds detection for when someone else in your coop sprays or clears garden plots by pulling spray status from tablist

## Changelog Improvements
+ Add coop support for spray timer. - Chissl

2025-04-11 12:50 UTC, CalMWolfs requested changes

2025-04-11 12:50 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/garden/GardenPlotApi.kt
> +            plotSprayedTablistPattern.matchMatcher(line.trim()) {
Should either use `plotSprayedTablistPattern.firstMatcher(event.lines.map { it.trim() }) {` or `plotSprayedTablistPattern.matchAll(event.lines.map { it.trim() }) {` depending on if you need to match multiple lines in the tablist at the same time (I have no idea if there are multiple lines or not), you could also remove this trimming and mapping if you just allow the extra space to be in the pattern (which is what id recommend but isnt necessary)

2025-04-11 13:03 UTC, hannibal002 requested changes
Cal's comment

2025-04-16 22:04 UTC, hannibal002 commented
@Chissl bump. please fix the merge conflicts

2025-07-22 03:56 UTC, CalMWolfs approved these changes
i think it worked ( i deleted some stuff from my config file then a message sent in chat and nopo said it was maybe a new message so thats cool)

2025-07-22 03:56 UTC, merged