Fix: Custom Scoreboard Player Count Including Offline Players
hannibal00212/SkyHanni pull request #3026
Opened 2024-12-06 23:27 UTC by Chissl

## What
Fixed custom scoreboard's player count display on private islands/garden including players that were offline or on other islands. Also changed max player count on private islands from guest limit to online island owners + guest limit. Added an "Island" widget type to pull player names on solo islands and when guesting. 

## Changelog Fixes
+ Fixed custom scoreboard's player count including offline players on coops and when guesting. - Chissl

## Changelog Technical Details
+ Added "Island" widget type. - Chissl

2024-12-06 23:51 UTC, j10a1n15 requested changes

2024-12-06 23:51 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
> +    private fun isPlayerIsland(): Boolean {
you can use `inAnyIsland(IslandType.Garden,...)`

2024-12-07 02:34 UTC, CalMWolfs requested changes, later dismissed

2024-12-07 02:34 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/data/HypixelData.kt
> +        "^§.\\[[§\\w]{6,11}] §r.*",
changing this pattern from using a capture group to not using a capture group will cause NPEs for people on old versions, please change the pattern key

2024-12-08 19:08 UTC, hannibal002 requested changes
I cant reproduce the bug
![image](https://github.com/user-attachments/assets/1c70c746-af6a-4ff9-9954-29c423295449)

2024-12-08 19:27 UTC, j10a1n15 commented
> I cant reproduce the bug 

![image](https://github.com/user-attachments/assets/4b1a5c50-ff85-4396-9a05-9cb2a81a7ffa)
you need to be on your own island while in a coop

2024-12-08 19:34 UTC, hannibal002 commented
>  you need to be on your own island while in a coop

ive tried on private island as well

2024-12-08 19:35 UTC, j10a1n15 approved these changes
![image](https://github.com/user-attachments/assets/945bdacb-8171-4333-a0ba-5e9f1542155b)
works for me

2024-12-08 19:38 UTC, Chissl commented
> works for me
It's a bug documented since scoreboard release too https://discord.com/channels/997079228510117908/1222605332648296468/1222605332648296468

Should work when visiting people too since it always adds 1 to amount if it's a solo island. Maybe regex broke or something?

2024-12-08 19:40 UTC, hannibal002 commented
now it breaks on private island in production. in dev env was it working fine. hmm

2024-12-08 19:41 UTC, hannibal002 commented
on other players islands it doesnt break, neither in dev env nor prod
![image](https://github.com/user-attachments/assets/4a314735-3fa4-4c4a-a2a0-6618c0e854ed)

2024-12-08 19:43 UTC, j10a1n15 commented
> on other players islands it doesnt break, neither in dev env nor prod 

 the old code just sums up the numbers. so it takes the 4 from "Coop (4)" even though only 1 person is only rn
![image](https://github.com/user-attachments/assets/a12840af-0c12-4de5-8013-0e84ab935651)
![image](https://github.com/user-attachments/assets/ca8b3b85-5eb6-413e-a18b-ad37a697de7c)

it doesnt break when visiting coop profiles because the tablist doesnt use the "Coop (4)" line here

2024-12-08 19:44 UTC, Chissl commented
> on other players islands it doesnt break, neither in dev env nor prod 

It doesn't detect coops at all when guesting, it assumes every guest island is solo 
![image](https://github.com/user-attachments/assets/27852056-cb2b-483c-b2d4-6bea742eb768)

2024-12-08 19:49 UTC, Chissl commented
> it doesnt break when visiting coop profiles because the tablist doesnt use the "Coop (4)" line here

Yeah visiting people's islands and solo islands triggers this code instead
![image](https://github.com/user-attachments/assets/66431c20-98e3-4647-a96d-89abf444cd08)
based on this regex 
![image](https://github.com/user-attachments/assets/b7ead13e-f003-427a-8573-52812384b302)
which is this 
![image](https://github.com/user-attachments/assets/aca1c2ae-f13b-407c-aaa6-d6c36698fc31)

Not sure why it's coded like there will only be one instance of it in tab list

I replaced this with with a widget that contains every island owner name

2024-12-08 19:53 UTC, Chissl commented
> on other players islands it doesnt break, neither in dev env nor prod ![image](https://private-user-
It is breaking here, there are 6 people on island but shows 7 in scoreboard

2024-12-13 09:45 UTC, hannibal002 approved these changes

2024-12-13 09:45 UTC, merged