Backend: Sulphur Skitter performance updates
hannibal00212/SkyHanni pull request #3038
Opened 2024-12-08 18:15 UTC by hannibal002

## What
optimizing Sulphur skitter box

## Changelog Technical Details
+ Optimizing sulphur skitter performance by caching `AxisAlignedBB` calclulation and using more `LorenzVec`. - hannibal2

2024-12-09 12:38 UTC, CalMWolfs requested changes

2024-12-09 12:38 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/nether/SulphurSkitterBox.kt
> +        val to = location.add(20, 20, 20).toBlockPos()
if 2 lines down we check if its within 15 blocks why is it 20 blocks up here?
by changing these all to 15, we can check 39000 less blocks each time this function is ran (which is only 43% of the original blocks checked)

2024-12-09 12:40 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/nether/SulphurSkitterBox.kt
> +        val to = location.add(20, 20, 20).toBlockPos()
Those numbers aren't from me.
I assume the reason is so blocks in a 15 block radius will get instantly detected and not only every second

2024-12-09 12:42 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/nether/SulphurSkitterBox.kt
> +        val to = location.add(20, 20, 20).toBlockPos()
> Those numbers aren't from me. I assume the reason is so blocks in a 15 block radius will get instantly detected and not only every second

Those numbers may not be from you but this is a performance improvement pr and i have given performance improvement suggestion

2024-12-09 13:02 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/nether/SulphurSkitterBox.kt
> +        val to = location.add(20, 20, 20).toBlockPos()
I agree with the math though, we can set both to 15

2024-12-13 08:36 UTC, CalMWolfs approved these changes

2024-12-13 10:25 UTC, merged