Feature: ping display
hannibal00212/SkyHanni pull request #3044
Opened 2024-12-11 02:56 UTC by Not-a-cowfr

## What
adds ping display and `/shping` command just like tps display and `/shtps`

## Changelog New Features
+ Added ping display and command. - not_a_cow

2024-12-11 03:07 UTC, CalMWolfs requested changes

2024-12-11 03:07 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/misc/PingDisplay.kt
> +        if (lastPingAt > 0) {
should early return here

2024-12-11 03:07 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/misc/PingDisplay.kt
> +
double empty line x1

2024-12-11 03:07 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/misc/PingDisplay.kt
> +
double empty line x2

2024-12-11 03:07 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/misc/PingDisplay.kt
> +
double empty line x3

2024-12-11 03:07 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/misc/PingDisplay.kt
> +
double empty line x4

2024-12-11 03:07 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/misc/PingDisplay.kt
> +    }
should use second passed event

2024-12-11 03:07 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/misc/PingDisplay.kt
> +    private val mc: Minecraft = Minecraft.getMinecraft()
we dont really do this much elsewhere and even if we did, you only use this once in this file so there is no point in it

2024-12-11 03:07 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/misc/PingDisplay.kt
> +
double empty line x5

2024-12-11 03:07 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/features/gui/GUIConfig.java
> +    @ConfigOption(name = "Ping Display", desc = "Show your current ping, like in Skytils.")
I dont think this needs to say like skytils, as skytils does not show your ping on the screen

2025-01-30 06:31 UTC, jani270 commented
Why are we duping a skytils feature

2025-01-30 16:46 UTC, hannibal002 requested changes
We might keep the backend of the calculation for /shdebug, but jani's right, we dont need to copy Skytils features.

2025-01-30 18:06 UTC, jani270 commented
> We might keep the backend of the calculation for /shdebug, but jani's right, we dont need to copy Skytils features.

![grafik](https://github.com/user-attachments/assets/97408e1e-4acc-4a90-9944-76391413cbc9)

[huh](https://github.com/hannibal002/SkyHanni/pull/3044#discussion_r1879260074)

2025-01-30 18:11 UTC, martimavocado commented
kinda late for this but why not use modapi's ping packet instead

2025-02-06 13:04 UTC, hannibal002 commented
> kinda late for this but why not use modapi's ping packet instead

can you elaborate a bit please?
and the pr is a draft, so its not too late :)

2025-02-06 13:26 UTC, martimavocado commented
> can you elaborate a bit please?

the hypixel modapi has a specific packet for checking your ping, i feel like it's a bit silly asking the server for your statistics instead of using the packet specifically built for this

other than that i'm not super sure on what measurable difference this would make, or if hypixel/watchdog cares about this

2025-02-06 13:32 UTC, ItsEmpa commented
mod api doesnt have a packet for getting your ping, its just sends you a packet with the text "pong"

2025-02-06 13:36 UTC, lunaynx commented
> mod api doesnt have a packet for getting your ping, its just sends you a packet with the text "pong"

I mean sending a random packet like statistics does the same? You can measure the the time it took to receive a response.

2025-04-09 04:30 UTC, closed without merging