Feature: Enchanted Clock Reminders
hannibal00212/SkyHanni pull request #3051
Opened 2024-12-12 18:48 UTC by DavidArthurCole

## What
https://discord.com/channels/997079228510117908/1316578743095005224
Adds optional reminder(s) when enchanted clock boosts become available.

## Changelog New Features
+ Added reminders for Enchanted Clock boosts. - Daveed

2024-12-17 22:15 UTC, DavidArthurCole commented
I could've sworn I suppressed that during the merge... whatever, yap away, bot

2024-12-22 20:36 UTC, DavidArthurCole commented
Kinda forgot I had developed this, as it doesn't appear to be working atm. The baseline setup for loading the clock stuff should be good, but the reminders might be bugged.

2024-12-22 20:37 UTC, DavidArthurCole commented
![image](https://github.com/user-attachments/assets/43abfb17-22d3-4db1-872b-6ab8228262a9)

2025-01-04 19:09 UTC, hannibal002 requested changes
I dont see how the value in `storage.clockBoosts` gets updated after the first time usage

2025-01-08 19:01 UTC, hannibal002 requested changes
after opening the clock or after enabling one boost, the `availableAt` value in the config is still `null` for every element. This cant work
```
Search config for SkyHanni 1.2.0
configSearchTerm: 'enchantedclockboosts'
classSearchTerm: <all>

Found 1 config elements:
profileSpecific.enchantedClockBoosts java.util.LinkedHashMap = {§bMinions=Status(state=§eProblem, availableAt=null, warned=false), §6Chocolate Factory=Status(state=§aReady, availableAt=null, warned=false), §dPet Training=Status(state=§eProblem, availableAt=null, warned=false), §bPet Sitter=Status(state=§eProblem, availableAt=null, warned=false), §eAging Items=Status(state=§aReady, availableAt=null, warned=false), §6Forge=Status(state=§eProblem, availableAt=null, warned=false)}
```

2025-01-08 22:28 UTC, DavidArthurCole commented
> after opening the clock or after enabling one boost, the `availableAt` value in the config is still `null` for every element. This cant work

That would be because in your cleanup commits, you edited core functionality of the lookups between the simple and repo-loaded enum classes, and they would, post that, never succeed, so no values would be updated.

```
Search config for SkyHanni 1.2.0
configSearchTerm: 'enchantedclockboosts'
classSearchTerm: <all>

Found 1 config elements:
profileSpecific.enchantedClockBoosts java.util.EnumMap = {§bMinions=Status(state=§cCharging, availableAt=2025-01-10T21:28:20.158Z, warned=false), §6Chocolate Factory=Status(state=§cCharging, availableAt=2025-01-09T12:28:17.030Z, warned=false), §dPet Training=Status(state=§eProblem, availableAt=null, warned=false), §bPet Sitter=Status(state=§eProblem, availableAt=null, warned=false), §eAging Items=Status(state=§aReady, availableAt=null, warned=false), §6Forge=Status(state=§cCharging, availableAt=2025-01-09T13:28:17.030Z, warned=false)}
```

2025-01-08 23:04 UTC, hannibal002 commented
sorry for breakin things :(

2025-01-09 00:11 UTC, hannibal002 approved these changes
![grafik](https://github.com/user-attachments/assets/96192c4b-fa95-40c6-a49f-ab0d8a7a26b9)

2025-01-09 00:14 UTC, hannibal002 commented
@jani270 i hope you are happy with this fix

2025-01-09 00:19 UTC, merged

2025-01-09 09:19 UTC, jani270 commented
crazy