Fix: Item Value Estimation Coloring
hannibal00212/SkyHanni pull request #3061
Opened 2024-12-14 05:56 UTC by DavidArthurCole

## What
Fixes an issue with items not showing their correct colors, both due to varying name, and recombobulation not being accounted for. If this was intentional let me know and I'll make it a config option.

<details>
<summary>Images</summary>

Before
![image](https://github.com/user-attachments/assets/b5c1e09a-68de-4364-8f2c-9f667d5c12fe)

After
![image](https://github.com/user-attachments/assets/d42fcf34-b51f-4317-8197-200db16a6505)

</details>

## Changelog Fixes
+ Fixed incorrect display colors in Item Value Estimation. - Daveed

2024-12-14 10:34 UTC, NopoTheGamer commented
in the tooltip i dont think the "base item" should reflects recomb

2024-12-14 11:23 UTC, hannibal002 commented
either add reforge name to the item name, then we can simply use the real item name again, or dont show recomb. but showing recomb but not reforge feels unintuitive

2024-12-14 11:26 UTC, hannibal002 commented
unrelated: the data in the repo pr is used to move existing logic outside of live code. this is fine. but this has noting to do with this pr's title or description

2024-12-15 13:04 UTC, hannibal002 requested changes
Im not very happy with this design change. I agree, before it was missing the recomb color entirely, and this was confusing as well, but at least the design was clear.
![image](https://github.com/user-attachments/assets/5d668c92-05ef-43f1-a24e-468dea0a33ed)


how about we add the display name of the item at the first line, then a empty line, then the base item + everything else? just for the estimated chest value, not touching the actual estiamted item value logic here.


additionallly, the changelog wording is not precise. this affects only the estimated chest value, not the estimated item value.

2024-12-15 13:04 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
> +    val ItemStack.itemNameFullyRarityAware: String
what is the difference between this and the display name?

2024-12-15 13:05 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
> +    val ItemStack.itemNameFullyRarityAware: String
if the purpose is to remove the reforge name, maybe its better to have the function be called `nameWithoutReforge` instead?

2024-12-15 13:14 UTC, hannibal002 requested changes
please also mention the "item calculation stuff moved to repo" part in the changelog/pr desc, as this is arguabily the bigger part of the pr

2024-12-15 13:14 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValueCalculator.kt
> +        val name = stack.itemNameBaseRarityAware
we dont want to show the recomb color here, and since the reforge name is also not part of the clean item name, i dont see why this line change is necessary

2024-12-15 13:14 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/misc/items/EstimatedItemValue.kt
> +    lateinit var itemValueCalculationData: ItemValueCalculationDataJson
this should be null, not lateinit. starting with a outdated repo will cause ugly errors instead of clean repo errors

2024-12-15 13:52 UTC, closed without merging