Backend: Allow Parameterless Handling of SkyHanniEvent(s)
hannibal00212/SkyHanni pull request #3064
Opened 2024-12-14 08:13 UTC by DavidArthurCole

## What
For the cases where `@HandleEvent` is needed solely as the starter for a code snippet, where the normal `event: ...` function construction would warn about an unused param.
Probably the most divisive PR I've opened :D

<details>
<summary>Images</summary>

![Screenshot 2024-12-14 030819](https://github.com/user-attachments/assets/19712749-99a0-4a72-903d-c2a6b4a7bf97)

![Screenshot 2024-12-14 030346](https://github.com/user-attachments/assets/b8b9dda4-44f8-47eb-a96e-32021da3e0be)

</details>

## Changelog Technical Details
+ `SkyHanniEvent`s can now be `@Handle`-d without an `event:` parameter.
    * `@HandleEvent(eventType = [ClassThatExtendsSkyHanniEvent]::class)`.

2025-02-06 19:59 UTC, j10a1n15 commented
Could this maybe also support multiple event types? It doesnt have a lot of use cases but a few rare snippets can be simplified a tiny bit, e.g.:
![image](https://github.com/user-attachments/assets/100134df-00e2-460f-8cf8-3a1811e32eb9)
so we could instead use somehting along the lines of:
```kt
@HandleEvent(eventTypes = [InventoryCloseEvent::class, WorldChangeEvent::class])
fun onEvent() {
    resetItems()
}
```
Very minor but could be neat too

2025-02-10 22:23 UTC, DavidArthurCole commented
> Could this maybe also support multiple event types? ...

Done (I think).

2025-02-10 22:46 UTC, j10a1n15 requested changes
![image](https://github.com/user-attachments/assets/e046a948-53eb-464f-bf46-e61a0d0e2aa3)
the plugin doesnt support this yet

2025-02-10 23:25 UTC, DavidArthurCole commented
> the plugin doesnt support this yet

![image](https://github.com/user-attachments/assets/b2a22936-231c-4adf-bd8b-4cd79a0f16a6)

should be good now?

2025-02-10 23:31 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/api/event/EventListeners.kt
> +            "Method ${method.name} has no parameters but no eventType was provided in the annotation."
```
Description: Initializing game

java.lang.IllegalArgumentException: Method onReset has no parameters but no eventType was provided in the annotation.
	at at.hannibal2.skyhanni.api.event.EventListeners.createZeroParameterConsumer(EventListeners.kt:51)
	at at.hannibal2.skyhanni.api.event.EventListeners.createEventConsumer(EventListeners.kt:42)
WARNING: coremods are present:

	at at.hannibal2.skyhanni.api.event.EventListeners.addListener(EventListeners.kt:22)
	at at.hannibal2.skyhanni.api.event.SkyHanniEvents.registerSingleEventType(SkyHanniEvents.kt:49)
	at at.hannibal2.skyhanni.api.event.SkyHanniEvents.registerMethod(SkyHanniEvents.kt:40)
```

2025-02-10 23:36 UTC, DavidArthurCole commented on src/main/java/at/hannibal2/skyhanni/api/event/EventListeners.kt
> +            "Method ${method.name} has no parameters but no eventType was provided in the annotation."
One more try, this time it'll work for sure 100%.

2025-02-11 00:02 UTC, j10a1n15 approved these changes
works, cool stuff :)

2025-04-04 23:36 UTC, merged

2025-04-04 23:40 UTC, DavidArthurCole commented
This is huge