Feature + Backend: Gift Profit Tracker
hannibal00212/SkyHanni pull request #3072
Opened 2024-12-16 03:41 UTC by DavidArthurCole

## What
https://discord.com/channels/997079228510117908/1140705792937443448
Adds a profit tracker for opened gifts.

Technically has support for Party Gifts, but given the absurd price of those, and my lack of billions of coins to burn on getting chat patterns, this will solely track white/green/red gifts for now (unless the patterns are the same, I guess).

There are likely some items that are going to fail to map from the messages to the tracker. I had to add edge-case detection for Ice Runes, probably gonna be more... god bless beta testers.

<details>
<summary>Images</summary>

![image](https://github.com/user-attachments/assets/4865c8fa-0882-4dbd-bb71-aa47c77bc72b)

![image](https://github.com/user-attachments/assets/3fdbeff3-0d0a-4612-930d-676d00ed6e34)

![image](https://github.com/user-attachments/assets/d88fb3f0-494b-4b12-96df-f42f5e4fdd3d)

![image](https://github.com/user-attachments/assets/903339a1-3b30-4084-8e57-b96e85c16ac5)

![image](https://github.com/user-attachments/assets/37b4ad05-d46b-4960-9c9a-5fc117ba624b)

![image](https://github.com/user-attachments/assets/fdc81dde-d8f1-4d73-b5df-f1fdef0bc7ee)

</details>

## Changelog New Features
+ Added gift profit tracker. - Daveed
    * Does NOT auto track used gifts - see `/shaddusedgifts`.

## Changelog Technical Details
+ Moved a couple existing gift-related resources to a new `gifting` package. - Daveed

2024-12-16 03:49 UTC, lunaynx commented
Party gifts have a PARTY tier according to the official wiki, could add that next to SANTA, though I can't test either.

2024-12-16 03:51 UTC, DavidArthurCole commented
> Party gifts have a PARTY tier according to the official wiki, could add that next to SANTA, though I can't test either.

Next time beta is open I'll make a concerted effort to open a couple and see if I can easily add them to this

2025-02-11 12:00 UTC, hannibal002 requested changes
works well!
i dont like the non auto detection of gifts used. maybe we can later (outside this pr) add an option to track when the gift item moves in the air and read related from/to armor stands then?

2025-02-11 12:00 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/gifting/UniqueGiftingOpportunitiesFeatures.kt
> +    fun isHoldingGift() = holdingGift
this check will only work for gift profit tracker when giftingOpportunities is also enabled. rather move the "is holding gift" logic into a GiftAPI class instead

2025-02-12 09:11 UTC, ItsEmpa requested changes

2025-02-12 09:11 UTC, ItsEmpa commented on src/main/java/at/hannibal2/skyhanni/config/features/event/gifting/GiftingConfig.java
> +public class GiftingConfig {
shouldnt this config file be made in kotlin?

2025-02-12 09:11 UTC, ItsEmpa commented on src/main/java/at/hannibal2/skyhanni/config/features/event/gifting/GiftingConfig.java
> +    @ConfigOption(name = "Unique Gift Counter", desc = "Keep track of how many unique players you have given gifts to.")
order the annotations here the same way and put `@Accordion` after ConfigOption

2025-02-12 09:11 UTC, ItsEmpa commented on src/main/java/at/hannibal2/skyhanni/features/gifting/GiftApi.kt
> +    fun isHoldingGift() = LorenzUtils.inSkyBlock && holdingGift
is there any reason why you are adding an inSkyBlock check here?

2025-02-12 09:11 UTC, ItsEmpa commented on src/main/java/at/hannibal2/skyhanni/config/features/event/gifting/GiftTrackerConfig.kt
> +    var note: String = ""
dont use `@Expose` on config options annotated by `@ConfigEditorInfoText`

2025-02-12 15:25 UTC, DavidArthurCole commented on src/main/java/at/hannibal2/skyhanni/features/gifting/GiftApi.kt
> +    fun isHoldingGift() = LorenzUtils.inSkyBlock && holdingGift
came from the replaced function;

```kotlin
    @HandleEvent
    fun onTick(event: SkyHanniTickEvent) {
        holdingGift = false

        @Suppress("InSkyBlockEarlyReturn")
        if (!LorenzUtils.inSkyBlock) return
```

2025-02-12 20:40 UTC, ItsEmpa commented on src/main/java/at/hannibal2/skyhanni/features/gifting/GiftApi.kt
> +    fun isHoldingGift() = LorenzUtils.inSkyBlock && holdingGift
i feel like you could just not use the inSkyblock check here

in fact you can probably just make the holdinGift var have a public getter, and use that instead

2025-02-14 14:36 UTC, hannibal002 commented
should this not be included?
![image](https://github.com/user-attachments/assets/f2848f26-9d5f-43c7-8a65-05c56e91c193)
"§f§lCOMMON! §r§6+5,000 Coins §r§egift with §r§a[VIP] KralingenBoys§r§f§r§e!"

2025-02-14 14:39 UTC, hannibal002 requested changes
The coin rewards are not showing (I think it was showing couple days ago?)
![image](https://github.com/user-attachments/assets/8b249a2c-5f86-45f3-863b-223496942a5b)


also maybe sort this by xp 
![image](https://github.com/user-attachments/assets/79ff565d-e4ba-4a47-8d29-607871829baa)

2025-02-14 17:29 UTC, DavidArthurCole commented
> should this not be included?

![image](https://github.com/user-attachments/assets/2e6a92cd-973c-4eb9-b605-7c5ebe8555ec)

Either Hypixel randomly decided to capitalize a C, or the pattern was never correct 🤷

2025-02-17 12:56 UTC, merged