Fix: shtrackcollection not counting Youngite and Obsolite when tracking timite
hannibal00212/SkyHanni pull request #3082
Opened 2024-12-18 22:38 UTC by martimavocado

## What
Describe what this pull request does, including technical details, screenshots, links to discord, etc.

## Changelog Fixes
+ Fixed /shtrackcollection not correctly tracking Youngite and Obsolite. - martimavocado

2024-12-18 22:51 UTC, CalMWolfs requested changes
Seeing that this is the second special case for the collection tracker, maybe it could move this special logic to the repo
Something like:

"Cactus": [
"Cactus_green"
],
"Timite": [
"Youngite",
"Other ite"
]

2024-12-18 23:42 UTC, Thunderblade73 commented
This can/should be a temporary fix. Since I'm currently completely replacing the logic with https://github.com/hannibal002/SkyHanni/pull/2621. (Which I hope I complete before the end of the year)

2024-12-18 23:56 UTC, hannibal002 commented
I agree with Thunderblade here, using repo here now will cause bigger merge conflicts. with the later pr /rewrite we also will move this into the repo with the format suggested by Cal.

2024-12-19 22:22 UTC, hannibal002 approved these changes

2024-12-19 22:22 UTC, merged