Snakes
hannibal00212/SkyHanni pull request #321
Opened 2023-07-17 08:31 UTC by hannibal002

snakes

2025-01-27 16:59 UTC, Thunderblade73 requested changes
Gave the Pr just a quick look and found some stuff that should be changed. Did not read the  full code. I focused on the render part first and foremost.

2025-01-27 16:59 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +    private var snakes = Mutex(mutableListOf<Snake>())
Kotlin has a native implementation for mutex behaviour. ```synchronized```
https://kotlinlang.org/api/core/kotlin-stdlib/kotlin/synchronized.html
https://medium.com/@appdevinsights/how-do-you-handle-concurrency-in-kotlin-using-synchronized-blocks-3e209251d47d

2025-01-27 16:59 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +                }
Pls use a line drawer here to save redundante calls.

2025-01-27 16:59 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/utils/LocationUtils.kt
> +
This code looks a lot like the ```AxisAlignedBB.expand()``` code.

2025-01-27 18:16 UTC, nea89o commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +    private var snakes = Mutex(mutableListOf<Snake>())
While synchronizing on an object is technically possible, it is recommended against by kotlin itself. Additionaly the mutex type makes it impossible to access something without acknowleding the lock, by wrapping the object in type level knowledge of the associated lock.

2025-01-27 18:19 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +    private var snakes = Mutex(mutableListOf<Snake>())
> While synchronizing on an object is technically possible, it is recommended against by kotlin itself. Additionally the mutex type makes it impossible to access something without acknowleding the lock, by wrapping the object in type level knowledge of the associated lock.

I just don't think that a custom class is the recommended way to to do it. And I just remembered that you used synchronized block in the RepoPattern, so I just assumed that is the preferred way to do it in kotlin. When you are fine with then I also fine with it.

2025-01-27 18:43 UTC, nea89o commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +    private var snakes = Mutex(mutableListOf<Snake>())
The custom class here is maybe not neccessarily the best way of doing it, (especially with seperate read and write locks, or with threads that wait on each other using condvars), but i specifically wanted something that encodes the need to synchronize on the object in the type system, and this is what i found. Custom lock implementations also allow for more things (such as a checked access method using `isHeldByCurrentThread`).

2025-01-27 19:08 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +    private var snakes = Mutex(mutableListOf<Snake>())
I just looked at the code more closely and noticed that a mutex is here the wrong approach to begin with. Since all 3 lists are simply queue where one side fills it and the other drains it. So a ```ConcurrentLinkedQueue``` would work better here imo.

2025-01-27 19:13 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +    private var snakes = Mutex(mutableListOf<Snake>())
Using a ConcurrentLinkedQueue feels wrong for me (assuming I understand it correctly) since we have three separate actions, fill, read, drain. And without merging read and drain in one locked state, the fill action could maybe happen during read. That would leave unprocessed data to be drained.

2025-01-27 19:15 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +    private var snakes = Mutex(mutableListOf<Snake>())
If we could iterate and drain at the same time this would be ideal. But I don't want to create three helper lists every tick

2025-01-27 19:17 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/LocationUtils.kt
> +
Yeah thought about that while writing it. sadly I didn't found s neat way of parsing a location to a axis aligned aabb object so I used a different, more primitive solution. But I think the math should be put into s utils again

2025-01-27 19:18 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +    private var snakes = Mutex(mutableListOf<Snake>())
Either way I'm currently porting the code to the ConcurrentLinkedQueue.

> If we could iterate and drain at the same time this would be ideal. But I don't want to create three helper lists every tick

```CollectionUtils.drainForEach``` exists

> Using a ConcurrentLinkedQueue feels wrong for me (assuming I understand it correctly) since we have three separate actions, fill, read, drain. And without merging read and drain in one locked state, the fill action could maybe happen during read. That would leave unprocessed data to be drained.

Drain and fill work at the same time
Read and fill work at the same time
Just read and drain could have strange behaviour

2025-01-27 19:18 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +                }
What does the line drawer save? The GL state changes between each line?

2025-01-27 19:20 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +                }
Does (expect the draws.invoke)
![image](https://github.com/user-attachments/assets/bc976fea-3b44-4cc7-aea0-1e9a343ee9db)

2025-01-27 19:28 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +    private var snakes = Mutex(mutableListOf<Snake>())
But this is exactly what we do here? First we fill in async block packet event, then we read and drain in tick event. So this doesn't help us then?

2025-01-27 19:29 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +    private var snakes = Mutex(mutableListOf<Snake>())
In tick we just drain. Drain is a destructive read so you don't have to read again since you already did read it during the drain.

2025-01-27 19:29 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +                }
At a glance this doesn't look like it supports our see behind blocks parameter, will test out later

2025-01-27 19:33 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +    private var snakes = Mutex(mutableListOf<Snake>())
So we could read and drain at the same time? I'm confused, you just said
Just read and drain could have strange behaviour

2025-01-27 19:34 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +    private var snakes = Mutex(mutableListOf<Snake>())
Also can you explain to me the difference between this concurrent list approach and the mutex approach? The internal value still needs to be copied over or the write process be halted, so how is this better

2025-01-27 19:34 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +    private var snakes = Mutex(mutableListOf<Snake>())
> So we could read and drain at the same time? I'm confused, you just said Just read and drain could have strange behaviour

Yes, if you read in on thread but at the same time drain it in another. But that does not happen in your code.

2025-01-27 19:39 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +    private var snakes = Mutex(mutableListOf<Snake>())
> Also can you explain to me the difference between this concurrent list approach and the mutex approach? The internal value still needs to be copied over or the write process be halted, so how is this better

No. Mutex does need to stop. The ConcurrentLinkedQueue is designed so it can work continuously.
Sure there might some small artifacts in the render but I would argue those are better than frame hiccups.

2025-02-04 14:11 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/LocationUtils.kt
> +
I looked again into this, and while `location.boundingToOffset(1.0, 1.0, 1.0).expand(0.0001, 0.0001, 0.0001)` exists, i dont find a way to render this `AxisAlignedBB` by only drawing the corner lines. @Thunderblade73

2025-02-04 14:25 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/utils/LocationUtils.kt
> +
yeah, I know that is not implemented. Simply use the point of the Corners of the AxisAlignedBB as you used your points. Otherwise feel free to implement such an method, since it will be needed in the future anyway.

2025-02-06 10:26 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/LocationUtils.kt
> +
done

2025-02-06 10:41 UTC, ItsEmpa requested changes
some things i noticed

2025-02-06 10:41 UTC, ItsEmpa commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +    private val directions = setOf(
this could probably be moved to the companion object of lorenzvec

2025-02-06 10:41 UTC, ItsEmpa commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +    ).map { it.toInternalName() }
```suggestion
    ).toInternalNames()
```

2025-02-06 10:41 UTC, ItsEmpa commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +            "FROZEN_WATER_PUNGI".toInternalName() -> Role.CALM
make this a property in the class to not call .toInternalName constantly

2025-02-06 10:41 UTC, ItsEmpa commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +            if (InventoryUtils.itemInHandId == "FROZEN_WATER_PUNGI".toInternalName())
same with this internal name

2025-02-06 10:41 UTC, ItsEmpa commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +    private class Snake(
make this a data class

2025-02-06 10:41 UTC, ItsEmpa commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +    private fun isEnabled() = RiftApi.inRift() && (RiftApi.inLivingCave() || RiftApi.inLivingStillness()) && config.highlight
remove the rift check from isEnabled and add rift island check in the handle event annotations

2025-02-06 10:41 UTC, ItsEmpa commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +        fun SkyHanniRenderWorldEvent.renderBlock(location: LorenzVec) {
can be private

2025-02-06 10:41 UTC, ItsEmpa commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +            val isSelected = this@Snake == selectedSnake
a function for isSelectedSnake() could be useful seeing how you are checking this in a couple of places

2025-02-06 10:53 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +            "FROZEN_WATER_PUNGI".toInternalName() -> Role.CALM
done

2025-02-06 10:53 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +    ).map { it.toInternalName() }
will do

2025-02-06 10:53 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +            if (InventoryUtils.itemInHandId == "FROZEN_WATER_PUNGI".toInternalName())
alr done

2025-02-06 10:54 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +    private class Snake(
what for? do we use compare/tostring?

2025-02-06 10:55 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +    private fun isEnabled() = RiftApi.inRift() && (RiftApi.inLivingCave() || RiftApi.inLivingStillness()) && config.highlight
done

2025-02-06 10:55 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +        fun SkyHanniRenderWorldEvent.renderBlock(location: LorenzVec) {
done

2025-02-06 10:55 UTC, ItsEmpa commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +    private class Snake(
![imagen](https://github.com/user-attachments/assets/27d86b21-f8aa-4aa1-b6d8-bf75fbe6f770)

2025-02-06 10:57 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +            val isSelected = this@Snake == selectedSnake
done

2025-02-06 10:59 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +    private val directions = setOf(
done

2025-02-06 11:01 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +    private class Snake(
For a data class, the generated `equals` method compares property values, so two different instances with identical properties are considered equal. For a non-data class (without an overridden `equals`), the default implementation checks reference equality, meaning only the same instance is equal to itself.

we dont want to compare the properties, just the reference. so this is not needed here

2025-02-06 11:02 UTC, ItsEmpa commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +    private class Snake(
fair enough

2025-02-07 17:59 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveSnakeFeatures.kt
> +                }
we now use line drawer

2025-02-07 18:58 UTC, Thunderblade73 requested changes
Just some cleanup is needed. Nothing major.

2025-02-07 18:58 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveLivingMetalHelper.kt
> +        if (animationStartTime.passedSince() > 4.seconds) return
Is this intended to be reduced from 5 to 4 seconds?

2025-02-07 18:58 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
> +        }
Add this to the LineDrawer, so that multiple of those can be drawn, You can keep the wrapper but it should be possible to draw 2+ of those things inside on LineDrawer so the "logic" part should be moved to a methode inside LineDrawer.

2025-02-07 18:58 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
> +        }
Same as above

2025-02-07 18:58 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
> +    }
Move that to locationUtils or LorencVec. Since that is not really a render method just a helper for AxisAlignedBB.

2025-02-07 18:58 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/snake/LivingCaveSnake.kt
> +    fun invalidSize(): Boolean = blocks.isEmpty() || blocks.zipWithNext().any { (a, b) ->
It checks invalide in general not dependent on the size. So a better name would be preferred.

2025-02-07 18:58 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/snake/LivingCaveSnake.kt
> +        }
Line Drawer! The Line Drawer should wrap around the for.

2025-02-07 20:10 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/LivingCaveLivingMetalHelper.kt
> +        if (animationStartTime.passedSince() > 4.seconds) return
yes.
while testing snake, i accidentally clicked the ore block that activated the metal helper, and it took forever for the highlight to dissapear. 
while actively farming those blocks you dont need that long of a highlight imo.

2025-02-07 20:11 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
> +        }
wdym? this is alr in line drawer

2025-02-07 20:12 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
> +    }
i dont see a need for the calculate edges logic outside of a render context.

2025-02-07 20:13 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/snake/LivingCaveSnake.kt
> +    fun invalidSize(): Boolean = blocks.isEmpty() || blocks.zipWithNext().any { (a, b) ->
invalidSizeOrInvalidDistanceBetweenBlocks? that better?

2025-02-07 20:13 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
> +        }
> wdym? this is alr in line drawer

It uses a LineDrawer but it the method is not inside a LineDrawer.

2025-02-07 20:13 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/snake/LivingCaveSnake.kt
> +    fun invalidSize(): Boolean = blocks.isEmpty() || blocks.zipWithNext().any { (a, b) ->
invalidShape or something smaller than invalidSizeOrInvalidDistanceBetweenBlocks

2025-02-07 20:14 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/snake/LivingCaveSnake.kt
> +        }
thougth about this, but idk.
this would require us to move the internal line draw logic outside the utils, and idk if i like this

2025-02-07 20:16 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
> +    }
> i dont see a need for the calculate edges logic outside of a render context.

This could be used for collision detection or whatever. (Not a realistic use but possible). I just don't want as much as possible outside of RenderUtils that does not need to be there. Since that file is way to big.

2025-02-07 20:18 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/rift/area/livingcave/snake/LivingCaveSnake.kt
> +        }
> thougth about this, but idk. this would require us to move the internal line draw logic outside the utils, and idk if i like this

This is no problem if you apply the other change I suggested.

2025-02-07 20:19 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
> +        }
Something like that:
```kotlin
LineDrawer.drawEdges(....)
```
(But probably not as an extension, just make it a normal method)

2025-02-07 20:44 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
> +        }
the function draw3DLine we call inside the loop is inside line drawer. idk what you mean
![image](https://github.com/user-attachments/assets/8a8d801e-f76c-421c-9714-0a0791ca271f)

2025-02-07 20:46 UTC, Thunderblade73 requested changes

2025-02-07 20:46 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
> +        }
Yes but not the whole functions. Eg: The loop

2025-02-07 20:49 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
> +        }
now i get it. will test if my impl works

2025-02-07 20:56 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/RenderUtils.kt
> +    }
fair

2025-02-07 21:08 UTC, Thunderblade73 approved these changes

2025-02-07 21:09 UTC, merged