Farming fortune display
hannibal00212/SkyHanni pull request #34
Opened 2023-04-08 07:02 UTC by appable0

<img width="254" alt="Screenshot 2023-04-07 at 11 53 38 PM" src="https://user-images.githubusercontent.com/16139460/230707877-ac603241-36db-4498-a38a-25b0c52ef05e.png">

This adds a simple farming fortune display that takes crop-specific farming fortune into account (specifically: dedication, turbo-crop, tool counter, tool passive ability, and crop upgrades).
- Added farming fortune display
- Added crop upgrade data manager and update event
- Some various utility methods in CropType, SkyBlockItemModifierUtils, etc

2023-04-09 21:25 UTC, appable0 commented
<img width="415" alt="Screenshot 2023-04-09 at 2 25 27 PM" src="https://user-images.githubusercontent.com/16139460/230797213-8f577517-6943-44aa-a320-220acc9f56af.png">

Not sure how to format this nicely.

2023-04-10 01:30 UTC, appable0 commented
- Moved tooltip tweaks to new class
- Added config for tool tooltip tweaks
- Added all farming fortune sources to fortune breakdown
- Added compact farming tool tooltip option

Farming fortune breakdown:
<img width="346" alt="Screenshot 2023-04-09 at 6 11 50 PM" src="https://user-images.githubusercontent.com/16139460/230806366-e1048eff-74f5-4eee-904a-8db3e76c3104.png">

Compact farming tool tooltip:
<img width="416" alt="Screenshot 2023-04-09 at 6 20 23 PM" src="https://user-images.githubusercontent.com/16139460/230806977-dcffaed5-ac38-4f31-a287-4e3b4a77fcdd.png">

2023-04-10 18:37 UTC, hannibal002 requested changes
See discord

2023-04-10 21:17 UTC, appable0 commented
<img width="204" alt="Screenshot 2023-04-10 at 2 16 03 PM" src="https://user-images.githubusercontent.com/16139460/231000444-f4d3904c-4010-4aad-bc42-3e853631e385.png">

Now displays this for ~1 second following a GardenToolChangeEvent to wait for tab list update.

2023-04-11 00:44 UTC, merged