Watchdog hider improvement
hannibal00212/SkyHanni pull request #342
Opened 2023-07-28 06:05 UTC by appable0

Attempts to hide watchdog messages by matching the watchdog message to a multi-line template including the empty lines around it. 

This is intended to resolve the issue where the Watchdog hider leaves two extra blank lines in chat. The empty line hider is a current work-around, but messes with other chat elements.

I am not sure why it doesn't properly hide the empty lines currently, as they seem to be properly filtered in logs.

2023-07-28 20:56 UTC, appable0 commented
This actually worked, I just had a ChatTriggers prototype that didn't work and was re-adding the blank lines. Oops!

2023-07-29 09:01 UTC, hannibal002 commented
I am not sure that I understand the logic of the changed code properly.
It looks to me like it only blocks the same messages as before?

2023-07-29 22:03 UTC, appable0 commented
The Watchdog message looks like this:

<img width="597" alt="Screenshot 2023-07-29 at 2 44 44 PM" src="https://github.com/hannibal002/SkyHanni/assets/16139460/f3e86295-de8b-44f4-9c81-c794dcb5a945">

The current Watchdog hider correctly filters the Watchdog lines, leaving behind two empty lines.
<img width="653" alt="Screenshot 2023-07-29 at 2 48 22 PM" src="https://github.com/hannibal002/SkyHanni/assets/16139460/13138284-d676-4033-9fbd-676402b761e7">

The best current solution is to use the empty lines hider, but that solution takes away many other empty lines in other contexts.

<img width="536" alt="Screenshot 2023-07-29 at 2 51 47 PM" src="https://github.com/hannibal002/SkyHanni/assets/16139460/d49cd7dc-4ccd-4271-b3b7-96996be95f13">

<img width="649" alt="Screenshot 2023-
07-29 at 2 50 28 PM" src="https://github.com/hannibal002/SkyHanni/assets/16139460/61ae4102-3015-4610-a073-229264591c2e">

Ideally, the Watchdog hider should hide the complete Watchdog message, including the empty lines. This is difficult because it's not possible to tell whether the first empty line received will be associated with Watchdog.

PatternHider solves this by immediately hiding lines and storing a buffer of hidden lines. If it encounters a line that doesn't match the multi-line pattern it expected, it can simply revert using its buffer (this happens either if a chat message doesn't match or if it times out in two client ticks).

2023-08-02 12:06 UTC, hannibal002 requested changes
All other changes are looking good to me.

2023-08-02 12:06 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/chat/PatternHiderManager.kt
> +            Regex("§fWatchdog has banned §r§c§l(.*)§r§f players in the last 7 days."),
The brackets for `.*`in this  regex can be removed

2023-08-02 12:06 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/chat/PatternHiderManager.kt
> +        val watchdogHider = PatternHider(this, "watchdog", watchdogPattern) {
We could make pattern Hider a data class and keep the logic methods and the forge events in the manager class

2023-08-02 12:06 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/chat/ChatFilter.kt
>          profileJoin(message) && config.profileJoin -> "profile_join"
The empty lines you removed here were intentional, to mark the legacy `config.others` code that should be moved into separate config options anyway

2023-08-04 02:34 UTC, closed without merging