CrystalHollows location sharing and Kuudra Chest Waypoints
hannibal00212/SkyHanni pull request #412
Opened 2023-08-26 23:41 UTC by dragon99z

+added skyBlockServerId to LorenzUtils
+added Kuudra Chest Waypoints
+added CrystalHollows location sharing system

2023-09-17 17:05 UTC, romangraef requested changes

2023-09-17 17:05 UTC, lineargraph commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsSharedLocations.kt
> +    private var apiKey = "379f3118-wlgt-0649-ni38-9fa5477e1b05"
Please dont hardcode API keys or server addresses. While i wholly object this, on the basis of this server not being very transparent, i additionally would request this to be either a config option or a repo option, so that if the server goes down, we can just switch to another one.

2023-09-17 17:05 UTC, lineargraph commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsSharedLocations.kt
> +            }"""
Please use a JSON library for serializing JSON. Even tho this is a simple thing, i would really prefer if we just never did string operations on json data as a matter of principle.

2023-09-17 17:05 UTC, lineargraph commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsSharedLocations.kt
> +        }
There is no need to switch context for something as simple as urlencoding a string which is like 20 characters long. This context switch is probably more expensive than the actual url encoding

2023-09-17 17:05 UTC, lineargraph commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsSharedLocations.kt
> +                    }
Please use GSONs object mapping instead of manual json parsing.

2023-09-17 17:05 UTC, lineargraph commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsSharedLocations.kt
> +                    }
Please bunch all of your edit actions into one, instead of performing an editCopy for each individual location.

2023-09-17 17:05 UTC, lineargraph commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsSharedLocations.kt
> +                "Error while fetching ch waypoints from api.dragon99z.de"
Again: we don't want to rely on external servers, so please use the "baseUrl" placeholder here

2023-09-17 17:05 UTC, lineargraph commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsSharedLocations.kt
> +            val success = result["success"].asBoolean
Again, dont parse json manually.

2023-09-17 17:05 UTC, lineargraph commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsSharedLocations.kt
> +                "Error while trying to add the user for ch waypoints to api.dragon99z.de"
And again, use a placeholder here

2023-09-17 17:05 UTC, lineargraph commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsSharedLocations.kt
> +        }
Again there is no need for an IO dispatcher here

2023-09-17 17:05 UTC, lineargraph commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsSharedLocations.kt
> +        if (!event.isMod(40)) return
Running an update every 2 seconds really does not seem to be the play here. Consider being reactive instead (using websockets, for example)

2023-09-17 17:05 UTC, romangraef commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsSharedLocations.kt
> +        update(LorenzUtils.skyBlockArea, LocationUtils.playerLocation())
Please either add an option to configure those locations, or, generate a popup that asks players if they want to share. Implicitly sharing locations isn't great, especially if some locations like the dragons lair or mines of divan, might be a thing that players sometimes dont want to share.

2023-09-17 17:05 UTC, romangraef commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsSharedLocations.kt
> +                            update("Mines of Divan", entity.getLorenzVec().add(33, 18, 3))
This offset should be different depending on the keeper.

2023-10-03 07:21 UTC, hannibal002 commented
I will mark this PR as draft for now (see nea's comment)

2023-11-05 11:16 UTC, hannibal002 commented
Closing for inactivity

2023-11-05 11:16 UTC, closed without merging