Feature: Player symbols in chat
hannibal00212/SkyHanni pull request #467
Opened 2023-09-11 09:09 UTC by CalMWolfs

Adds chat symbols such as ironman/bingo/nether faction like SBA had/has
- Having an emblem doesn't break detection of these symbols
- Ability to change where it displays (left of name, right of name, hide altogether)
- Works without having sb levels in chat (Hypixel's emblems don't)
- Also remove ClientChatReceivedEvent from everywhere that didn't need it
- And most importantly doesn't break chat components from Hypixel or other mods

2023-09-14 21:54 UTC, romangraef requested changes

2023-09-14 21:54 UTC, romangraef commented on src/main/java/at/hannibal2/skyhanni/data/ChatManager.kt
> +        val chatEvent = LorenzChatEvent(message, original, event.type)
Not needed at all. Check line 79:
```kt
if (event.type.toInt() == 2) return
```

2023-09-14 21:54 UTC, romangraef commented on src/main/java/at/hannibal2/skyhanni/features/misc/PlayerChatSymbols.kt
> +                    if (component is ChatComponentText && component.text.contains(username)) {
Use `getUnformattedTextForChat()` instead of `text`. Also avoids having to cast to ChatComponentText

2023-09-14 21:54 UTC, romangraef commented on src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
> +                component.text = component.text.replace(toReplace, replacement)
Use `getUnformattedTextForChat()` here too

2023-09-14 21:54 UTC, romangraef commented on src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
> +                false
You can remove the if and instead directly use a `return@modifyFirstChatComponent /* your if condition here 
*/`

2023-09-26 12:27 UTC, romangraef commented on src/main/java/at/hannibal2/skyhanni/utils/StringUtils.kt
> +    fun <T> subMapWithKeysThatAreSuffixes(prefix: String, map: NavigableMap<String?, T>): Map<String?, T>? {
Any reason for this change? NavigableMap is an interface that provides additional functionality and guarantees over Map, so this feels like a bit of a waste.

2023-10-12 12:09 UTC, hannibal002 approved these changes

2023-10-12 12:09 UTC, merged