Added toggle for 12hr/24hr in real time hud
hannibal00212/SkyHanni pull request #507
Opened 2023-09-26 16:25 UTC by Thunderblade73

2023-09-27 06:40 UTC, hannibal002 requested changes
Thanks for the changes!
Can you please add the missing empty lines in many places? If you use IntelliJ, you can use ⌘⌥L (macOS), or Ctrl+Alt+L (Windows/Linux)
See https://www.jetbrains.com/idea/guide/tips/reformat-file/

2023-09-27 07:00 UTC, CalMWolfs requested changes
looks good apart from the formatting, also please try to merge a separate branch in instead of from beta

2023-09-27 07:00 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/features/GUIConfig.java
> +    @ConfigOption(name = "Real Time 12h format", desc = "Display the current computer time in 12hr format rather than 24h format.")
Format should be capitalised

2023-09-27 07:00 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/dungeon/CroesusUnopenedChestTracker.kt
> +import at.hannibal2.skyhanni.utils.LorenzDebug
Unused import

2023-09-27 17:04 UTC, Thunderblade73 commented
Now it should be fine or did I miss something?

Also @CalMWolfs could you elarborate further on that:
> also please try to merge a separate branch in instead of from beta 

I didn't really understand this

2023-09-27 17:13 UTC, RayDeeUx commented
> Now it should be fine or did I miss something?
> 
> Also @CalMWolfs could you elarborate further on that:
> 
> > also please try to merge a separate branch in instead of from beta
> 
> I didn't really understand this

hello yes, fellow contributor here who also learned of this the hard way

when you're faced with adding multiple features to skyhanni (or anything in general) it's better for everyone if you separated the additions by branches for a number of reasons.

for example, say i want to add an easter egg that sends people a smiley face whenever they earn an S+ score in M7, and also wanted to add an actual feature to prevent right clicking items with item abilities on private islands.

it would make more sense to have a pull request specifically for the easter egg and a second pull request for the item ability prevention feature, that way any changes on one pull request wouldn't directly affect changes from the other pull request.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches in case you want the official lingo on pull requests

(@CalMWolfs is currently in bed at the moment as i type this, i hope this response is useful to some extent)

2023-09-27 18:01 UTC, Thunderblade73 commented
Ok, so everything that I implement should have it's own branch at my side and than an Pull Request to the main branch([hannibal002:beta](https://github.com/hannibal002/SkyHanni/tree/beta)). Did I understand this correctly?

2023-09-27 18:13 UTC, hannibal002 commented
> Ok, so everything that I implement should have it's own branch at my side and than an Pull Request to the main branch([hannibal002:beta](https://github.com/hannibal002/SkyHanni/tree/beta?rgh-link-date=2023-09-27T18%3A01%3A15Z)). Did I understand this correctly?


Yes, exactly like this!

2023-09-28 06:27 UTC, hannibal002 approved these changes

2023-09-28 06:29 UTC, merged