Feature: Make normal clicks to shift clicks in equipment inventory
hannibal00212/SkyHanni pull request #519
Opened 2023-09-29 18:21 UTC by Thunderblade73

2023-10-06 19:31 UTC, hannibal002 requested changes
Even though the actual new code is just 3 lines, please move it inside a new class. The `HideNotClickableItems` class is already 500+ lines big and needs heavier reworks, and adding new stuff that has nothing to do with it just makes this process more confusing later.
The logic itself works perfectly for me.


Also, I don't know if we really should have it default enabled. While it's only useful for everyone and I don't see any downsides at all, it could be a bit problematic when someone argues "we change packets per default" so technically it's a bit more nuanced. In the end, your call if you want to keep it default enabled, I'm fine with it.

2023-10-06 19:31 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/InventoryConfig.java
> +    @ConfigOption(name = "Shift Click For Equipment", desc = "Makes normal clicks to shift clicks in equipment inventory")
Please remove the word "for" in the option name, the text gets too small :/ 
![image](https://github.com/hannibal002/SkyHanni/assets/24389977/e368dc3a-dbff-4f9d-a71a-13c31e34aa32)

2023-10-06 20:00 UTC, Thunderblade73 commented
Made it a self contained Feature and the default is now false (better safe than sorry)

2023-10-11 09:16 UTC, hannibal002 approved these changes

2023-10-11 09:18 UTC, merged