Tweaker for outdated or missing neu version
hannibal00212/SkyHanni pull request #53
Opened 2023-04-20 21:11 UTC by hannibal002

Since Forge's default mod incompatibility screen is too complicated

2023-04-21 00:13 UTC, AfkUserMC requested changes

2023-04-21 00:13 UTC, AfkUserMC commented on src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
> +            neuWarning("The NotEnoughUpdates was not found.\n" +
"The NotEnoughUpdates" 🗿

2023-04-21 00:13 UTC, AfkUserMC commented on src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
> +            neuWarning("The NotEnoughUpdates is outdated!\n" +
"The NotEnoughUpdates"

2023-04-24 09:58 UTC, hannibal002 commented
Got implemented a bit different already

2023-04-24 09:58 UTC, closed without merging