Feature: Show alerts when the player catches a legendary sea creature
hannibal00212/SkyHanni pull request #530
Opened 2023-10-03 19:04 UTC by brandonwamboldt

See repo update: https://github.com/hannibal002/SkyHanni-REPO/pull/40/files

2023-10-05 03:56 UTC, CalMWolfs requested changes
Also see my coment on the repo pr. Looks good though
One other thing you could consider is making the repo file into one of the json classes (see the jsonobjects folder) - I have explained this horribly so if you have a question just ask in contributor chat as hanni or I can prob explain better there but this also isn't necessary for you to change

2023-10-05 03:56 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/fishing/SeaCreatureFeatures.kt
> +            if (config.playSound) SoundUtils.createSound("random.orb", 1.0f).playSound()
this should be `SoundUtils.playBeepSound()`

2023-10-06 17:11 UTC, hannibal002 requested changes, later dismissed
Thank you for adding the rarity of sea creatures to the repo and using this data in SkyHanni.
Some problems I have encountered, though:
It looks to me like you disregarded the custom rare tag we were using in the repo prior.
Before your pr: All sea creatures have the chat color of their type and are additionally bold if they are "rare".
Now with this pr: Nothing is bold anymore, their "type of origin" is totally ignored in chat messages, and it only uses their rarity color. This change is definitely not intended or wanted.

A feature that "highlights/Warns legendary sea creatures" should not trigger on the real rarity of the sea creature, but if the sea creature, itself is special/rare. For example currently, mobs like Thunder, Lord Jawbus, Carrot King and Deep Sea Protectors aren't legendary and yet are marked as rare. (I know that the current logic would still catch the mythic Lord Jawbus, but for that case the feature name "highlight legendary sea creatures" is not a correct match either.

Therefore, I suggest you still keep using the existing "rare" option instead of checking the rarity. We can still store the rarity in the field, but we should not use it for this feature toggle (we might decide to change the highlight color depending on the real rarity of a sea creature, making Lord Jawbus pink and Thunder purple, instead of all yellow/orange.

This was all about design, now some technical stuff:
The variable `toString` in the class `SeaCreature` uses the chat color variable, only to override it with the result of the rarity method. This is unlogical to me.
You could store the `LorenzRarity` data type directly in the field instead of parsing the string to the rarity on each access.
(Also maybe changing the loading of the sea creature repo file via java objects entirely (most likely out of scope for this pr)

2023-10-06 17:34 UTC, brandonwamboldt commented
Looks like i misunderstood some of the existing functionality, I'll get those things fixed right up

2023-10-06 19:23 UTC, brandonwamboldt commented
@hannibal002 I believe i have addressed all of your feedback

2023-10-15 13:31 UTC, hannibal002 approved these changes

2023-10-15 13:33 UTC, merged