Internal: Ban imports
hannibal00212/SkyHanni pull request #595
Opened 2023-10-17 10:24 UTC by nea89o

By royal decree of Sir Hannibal the second, it is now forbidden to import some packages from others. The provided config is just an example, but should be easy enough to understand and adapt.

2023-10-28 19:20 UTC, hannibal002 requested changes
the check failed again (even after merging beta into banimports)

2023-10-28 21:56 UTC, nea89o commented
Yes, the check is currently failing because of an example import ban that i put in. obviously we wouldnt want to keep that one, it is purely for demonstration.

2024-01-11 23:25 UTC, CalMWolfs approved these changes

2024-01-13 19:45 UTC, hannibal002 approved these changes

2024-01-13 19:45 UTC, merged