added a banner to warn the player if the worm cap is full
hannibal00212/SkyHanni pull request #608
Opened 2023-10-19 18:17 UTC by Vahvl

i hope this works fine lmao, seemed to be okay during testing, the only thing i forgor to test was how 7.2 size worked

2023-10-19 18:23 UTC, j10a1n15 commented
![image](https://github.com/hannibal002/SkyHanni/assets/45315647/f937161b-7b98-4bb0-9a3e-d5a102e99d3a) :)

2023-10-19 18:26 UTC, Vahvl commented
i have been informed that the size of the banner might go off screen so time to test

2023-10-19 18:36 UTC, Vahvl commented
nonono why did the testing one get pushed here

2023-10-19 18:37 UTC, Vahvl commented
github moment

2023-10-19 18:51 UTC, Vahvl commented
the size is very much fine
![image](https://github.com/hannibal002/SkyHanni/assets/74665243/692c3de9-73d2-40fc-b694-896e9e74feaf)

2023-10-19 21:40 UTC, CalMWolfs requested changes
Everything looks fine apart from this

2023-10-19 21:40 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/fishing/FishingTimer.kt
> +            TitleManager.sendTitle("§cWORM CAP FULL!!!", 2.seconds, 7.2)
Please change this to LorenzUtils.sendTitle()
if you want you can also change the other two instances of TitleManager.sendTitle() in the codebase to the LorenzUtils one

2023-10-22 16:47 UTC, Vahvl commented
i think that works, cal tell me if anything is wrong

2023-10-23 01:24 UTC, CalMWolfs approved these changes

2023-10-30 20:12 UTC, hannibal002 commented
![image](https://github.com/hannibal002/SkyHanni/assets/24389977/42435348-ca14-49f9-87be-04e83c77eea5)
please create a new branch for your next pr

2023-10-30 20:13 UTC, hannibal002 approved these changes

2023-10-30 20:14 UTC, Vahvl commented
alright. but why is creating a new branch important?

2023-10-30 20:14 UTC, merged