Feature: Extra Harp Features
hannibal00212/SkyHanni pull request #741
Opened 2023-11-29 23:02 UTC by Thunderblade73

Addes 2 small features and a small Fix (maybe should have split it but is only small things)
Addes an auto Scale feature which sets the GUI size to "AUTO".
Addes a quick Restart feature which lets you start the last played Song by pressing the close button shortly after opening the Harp.
Also limits the stacksize tooltip to 3 characters because keys like "Space" are to long

2023-12-07 21:40 UTC, Thunderblade73 commented
https://github.com/hannibal002/SkyHanni/pull/746 needs to be merged first

2024-01-14 20:14 UTC, CalMWolfs requested changes
Did not get a chance to test the code but the rest of it looks good apart from these small changes needed for the config file

2024-01-14 20:14 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/helper/HelperConfig.java
> +        public boolean quickRestart = false;
These don't need a feature toggle
Also missing the empty lines between the options in this file

2024-01-14 20:30 UTC, CalMWolfs approved these changes

2024-01-20 18:39 UTC, hannibal002 requested changes
The Melody inventory is sometimes small, sometimes big when I click and open and close the inventory in rapid succession.
![image](https://github.com/hannibal002/SkyHanni/assets/24389977/6493f5fc-9a76-45cd-acdc-f640ad6e9fab)
![image](https://github.com/hannibal002/SkyHanni/assets/24389977/fce826c0-165e-44fe-a960-4f81bba06b6d)

2024-01-20 18:39 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/helper/HelperConfig.java
> +        @ConfigOption(name = "GUI Scale", desc = "Automatically sets the GUI scale to \"AUTO\" when entering the Harp")
Please add a dot at the end of the sentences of description.

2024-01-20 18:39 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/helper/HelperConfig.java
> +        @ConfigOption(name = "Quick Restart", desc = "When pressing the close Button in the Harp Menu shortly after opening the Harp the selected song will be started")
This description feels overly worded to me, can you please add a comma somewhere to make it easier to read?

2024-01-20 18:39 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/HarpFeatures.kt
> +    fun onInventoryFullyOpenedEvent(event: InventoryFullyOpenedEvent) {
Please rename the function to onInventoryOpen for consistency

2024-01-20 18:39 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/HarpFeatures.kt
> +    private val menuTitlePattern by RepoPattern.pattern("harp.menu", "^Melody.*")
You can remove the `^` character in the pattern since you only use the matches() function.

2024-01-20 18:39 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/HarpFeatures.kt
> +    fun updateScale() {
You can make the function private

2024-01-20 18:39 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/HarpFeatures.kt
> +        event.container.inventory.indexOfFirst { it.getLore().contains("§aSong is selected!") }.takeIf { it != -1 }?.let {
Maybe move this song is selected line into a repo pattern to make it future-proof

2024-01-20 18:39 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/HarpFeatures.kt
> +        if (event.slot?.slotNumber != 40) return
What is at line 40? Please add a comment. Otherwise, it's not intuitive to me.

2024-01-20 18:39 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/HarpFeatures.kt
> +    private fun setGUI() {
Maybe add the word "scale" to those two functios

2024-01-20 23:35 UTC, Thunderblade73 commented
Fixed.

2024-01-21 08:58 UTC, hannibal002 approved these changes

2024-01-21 08:58 UTC, merged