Backend: DelayedRun sync
hannibal00212/SkyHanni pull request #746
Opened 2023-11-30 16:10 UTC by Thunderblade73

Found a better sync bug fix.

2023-11-30 22:02 UTC, nea89o requested changes

2023-11-30 22:02 UTC, nea89o commented on src/main/java/at/hannibal2/skyhanni/utils/DelayedRun.kt
> +    private val inMap = LinkedBlockingQueue<Pair<() -> Any, SimpleTimeMark>>()
You should not be using a `LinkedBlockingQueue` here. We don't want any blocking behaviour. Use  `ConcurrentLinkedQueue` instead.

2023-11-30 22:02 UTC, nea89o commented on src/main/java/at/hannibal2/skyhanni/utils/DelayedRun.kt
> +    val map = mutableListOf<Pair<() -> Any, SimpleTimeMark>>()
The naming of both of these variables could use some improvement: Maybe `tasks` and `delayedTasks`.

2023-11-30 22:02 UTC, nea89o commented on src/main/java/at/hannibal2/skyhanni/utils/DelayedRun.kt
> +            time.isInPast().also { if (it) runnable() }
I don't think the `also` one line style here serves to improve readability.

2023-12-01 11:53 UTC, lineargraph approved these changes

2024-01-16 23:27 UTC, nea89o approved these changes
Just had a thought about using a TreeMap instead :upside_down_face:, but no, this looks great.

2024-01-20 11:33 UTC, hannibal002 requested changes
The logic looks fancy, thanks <3
Not sure if im missing something but one small thing here looks misleading or wrong to me

2024-01-20 11:33 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/DelayedRun.kt
> +        futureTasks.drainTo(tasks)
I think drainTo should happen before removeIf

2024-01-20 11:33 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/DelayedRun.kt
>      fun runNextTick(run: () -> Unit) {
The current logic feels like it is "run in 2 ticks from now", right?

2024-01-20 11:43 UTC, Thunderblade73 commented
Since both suggestion are for one and the same issue:
It's 1 tick must happend but up to 1 extra tick could have happend.
I wanted to have this behavior so it is guaranteed that one tick has parsed, without that we would always execute the runNextTick in the subTick before the next Tick which is misleading. 
And also some stupid stuff could happen without that:
Say you run a runNextTick in a LorenzTickEvent. Then it could be possible that the code executes immediately after that event Listener finishes since the next Listener could be the checkRuns one and therefore no time has parsed for it.

2024-01-20 11:55 UTC, hannibal002 commented
The idea behind "run in next tick" for me was not a "provide at least 50ms delay" but rather "run in the next tick in the main thread".
But your logic is better.
Now the function executes in between 50 and 100 ms, instead of 1 and 50 ms. this feels more consistent.
And the extra 50ms will hurt no one.

Now only one question remains to me: should we rename the function runNextTick to something else?

2024-01-20 12:01 UTC, Thunderblade73 commented
The name is fine. Also documented the behavior.

2024-01-20 12:11 UTC, hannibal002 approved these changes

2024-01-20 12:12 UTC, merged