Feature: Add lobby size widget and player join/leave notifications
hannibal00212/SkyHanni pull request #756
Opened 2023-12-03 16:19 UTC by brandonwamboldt

2023-12-03 18:07 UTC, Thunderblade73 requested changes

2023-12-03 18:07 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/misc/SocialFeatures.kt
> +        players = mutableListOf<String>()
use ```players.clear()``` and change players to a val

2023-12-03 18:07 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/misc/SocialFeatures.kt
> +        val initialLoad = players.isEmpty()
change to ```if(players.isEmpty()) return``` no need for the variable

2023-12-03 18:07 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/misc/SocialFeatures.kt
> +        val playersInfo = TabListData.getTabList().filter { it.startsWith("§8[" ) }.map { it.removeColor().split("] ").last().split(" ").first() }.distinct()
change to regex. 
Somewhat like this (not tested):
```Kotlin
val regex = "\\].{5}(\\S)+".toRegex()
TabListData.getTabList().mapNotNull{regex.find(it)?.groupValues?.get(1)}
```

2023-12-03 18:07 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/misc/SocialFeatures.kt
> +    }
make players and playerInfo a ```set``` then the code becomes much simpler
```Kotlin
val leave = players - playerInfo
if(config.playerLeaveNotifications && config.playerNotificationLobbySize >= playersInfo.size){
  leave.foreach{
    LorenzUtils.chat("§7${player} has left your lobby", false)
  }
}
leave.foreach{
  players.remove(it)
}
val join = playerInfo - player
if(config.playerJoinNotifications && config.playerNotificationLobbySize >= playersInfo.size){
  join.foreach{
    LorenzUtils.chat("§7$it has joined your lobby", false)
  }
}
join.foreach{
  players.add(it)
}
```

2024-03-14 11:37 UTC, hannibal002 requested changes
Thunder's Changes

2024-04-04 00:27 UTC, closed without merging