Backend: ItemCategory
hannibal00212/SkyHanni pull request #811
Opened 2023-12-17 11:50 UTC by Thunderblade73

2024-01-14 06:27 UTC, CalMWolfs requested changes
didnt read the main logic too closely but it looked good i think. here is just a few smaller things

2024-01-14 06:27 UTC, CalMWolfs commented on .github/workflows/build.yml
not really sure why this is in this pr

2024-01-14 06:27 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/utils/UtilsPatterns.kt
could be formatted slightly better to be more readable, especially the rarityLoreLinePattern

2024-01-14 06:27 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/utils/UtilsPatterns.kt
> +    val rarityLoreLinePattern by patternGroup.pattern("item.lore.rarity.line", "^(?:§.){2,3}(?:.§. (?:§.){4})?(?:SHINY )?(?<Rarity>${LorenzRarity.entries.joinToString(separator = "|") { it.rawName }}
maybe this could be done in a separate function `${LorenzRarity.entries.joinToString(separator = "|") { it.rawName }}` but not super necessary

2024-01-14 11:03 UTC, Thunderblade73 commented on .github/workflows/build.yml
auto formatting, that is why

2024-01-14 17:48 UTC, CalMWolfs approved these changes
worked during my brief testing

2024-01-16 17:18 UTC, hannibal002 requested changes
Not tested the code yet, just broad coding style tips

2024-01-16 17:18 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/test/SkyHanniDebugsAndTests.kt
> +        val category = itemStack.getItemCategoryOrNull(logError = true)?.name ?: "UNCLASSIFIED"
logError is already default true, can be omitted

2024-01-16 17:18 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/ItemCategory.kt
> +    NONE,
Plese move none to the bottom and leave a empty line between.

2024-01-16 17:18 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/ItemCategory.kt
> +enum class ItemCategory {
Group this list by parent categories like in hand usefable, wearable, tool-like, in storage comsumables + arrows, pet-like, and maybe others

2024-01-16 17:18 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
> +        val rarityId = pet.getInternalName().asString().last() - '0'
Worse readability, is this worth the performance gain?

2024-01-16 18:56 UTC, hannibal002 requested changes
This item does not work with item rarity detection anymore. Maybe we should add unit testing with this item data against the new function.
'```
{"type":"Item","data":"H4sIAAAAAAAAAFWTy46jRhSGq8c9M24v0llESpYVaaIsRh4Bvk4rGxq7bXoasDHGDRurKMpQdnERl3bjXV4gDxBl7/fwo2SRx4hSuGfUipBA9Z//nPOdU6IFQBO8oT64jmhMcIY2xU2+Kxm7AG+VpIyLixZoFChogKsp9ckdQ0EOAPi3BVqL2mbsY5LxCqoPPuDuZ78v4F5bGPqo3el2+m2E/X6720Ub7OEh8XsDnjfLkpRkBSX5FWgW5LkoM5K3eNGLJnhrI1aSiz/JPglU5V5AK5Hhjhl6jzJVR0mgWY6oj3BPO8wFw1I7+mL/RVVkiqf3T27EcnfJdiqV+zw31FbLrmGFW301rvTIEXhuZVjzyol0/miidjCpZo17LlVzhcqBGt9WnuSm3sQ2HN73ax3Bk8QdmbAULb759NSVeqE/tSvXvmf40U5xZL/0nZqVv1p+9ZmMTE2Rxw4vsbxmreeyFgIz/q/VfrvyFDUwqEzR1BTwKHl66LzWeIjE1IvsLY7uIl/ple7j/Mmf2N0zx2LYred1DubOsXaiZi33emQzbRQI7kQTHWspOdFy70ZqV9uqPUdSK2elCvrI3rqWdjAmGt9pGOoW90dzyd3ehc4BC2qQnNk2c/6dCl82c35PLfDep3nKUHUFLh+SjDTP4g+n40BDAcXwjsb+DTwd0UeRR346HfuyRxktqhs4Q1lRQYtG5GcIPvGMCaIxt3ofxb//+gOqcUEYowGJMeHqYB9SRmASwyopM/ALV0KCfLhJMkgQDuFiV92yBO9gRVBWm359IuB7bvMIiWGNSOPgE4eo4Qyv4M3IGY1IgiRx/bfTEZ+O7HTcodMxg99O9dsemw5czMaKKj/AqWwp48XC4NJrRhNc6igioHOWerMySzmtkiEPTlEBkw1UCCNehgrKR2jDuicc+7Q+8oVdj5+LDMlFkVGvLEjeANcZyvia1mUaZMgn9Z920QDfpfXS1iEq1vWYALz/pwmuX0WcsCQD79Jz+5e/+ceZbFrOmlOvFVO+Xcu6qsnWeMSJy5LHPwjDASEeGbQ33SFpd/2B1/7cwZv2ZiBKPur3BTREl+Cq4BeVFyhKOcjvK++ZA70B70YoQgEBDfAfQyNXpz4EAAA\u003d"}
```

2024-01-18 15:35 UTC, hannibal002 requested changes
Tested and works fine now. Maybe we can create a custom item category for potions by checking for the name ending in " potion"?

2024-01-18 15:35 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
> +        if (isPet(cleanName)) {
I have the feeling the is pet logis is less heavy, should get called first.

2024-01-18 15:35 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
> +            val itemRarityEnum = LorenzRarity.getByName(rarity)
omit the suffix enum in both variable names

2024-01-20 09:08 UTC, hannibal002 approved these changes

2024-01-20 09:08 UTC, merged