Only show vacuum bag on your own vacuums
hannibal00212/SkyHanni pull request #833
Opened 2023-12-25 17:18 UTC by alexiayaa

This prevents the vacuum bag from showing as item stack size in SkyMart and the Auction House, as it can be confusing.

2023-12-26 01:41 UTC, RayDeeUx commented
- auction house check is not robust enough; vaccums with more than (and not including) 0 bids would fail this check
- hanni wants regex checks instead of `contains()` string operations now iirc

2023-12-26 01:42 UTC, RayDeeUx commented
what i'd suggest for the auction house check is through a chestname regex pattern instead

as for bz check, yeah there's no easy way around it except through lore line looping so just revise it to use regexpattern

2023-12-26 02:37 UTC, alexiayaa commented
I didn't mention bazaar, it's (obviously) not there if it's on the auction house.

SkyMart could use an inventory title check too I suppose. I'll double check AH once Derpy is gone, since I only tried accessing it through the museum today.

2023-12-26 02:45 UTC, RayDeeUx commented
silly me, pretend i meant player trading!

2023-12-27 10:04 UTC, hannibal002 commented
Isn't it smarter to use an allowed list instead of a denied list for checking where to show this? Only in own inventory, storage and chests on island, right?
Who knows how many other edge cases we have to filter out otherwise, just think of the show block on other players islands or neu PV or auction house display in hub.

2023-12-27 12:06 UTC, alexiayaa commented
PV is actually not a problem since the lore shows the player's own vacuum bag (I don't remember if SkyHanni does anything with the stack size there) but yeah I guess, there could be many other edge cases.

2023-12-27 12:13 UTC, j10a1n15 commented
I feel like this could be done with a listOf(blockedLines) and then
```kotlin
val blockedLines = listOf("Click to trade!",...)

if (blockedLines.any { it in lore }) return ""
```

2024-01-02 21:54 UTC, hannibal002 requested changes
Please dont use "early return" but rather a new function that has a good descriptive name and then use `if(!function()){gardenVacuumPatterm..`

2024-01-06 10:22 UTC, hannibal002 approved these changes

2024-01-06 10:22 UTC, merged