Highlight own bids in Auction House
hannibal00212/SkyHanni pull request #843
Opened 2023-12-27 17:48 UTC by alexiayaa

- Green: Won
- Gold: Outbid
- Red: Lost

2024-01-20 12:10 UTC, Thunderblade73 requested changes
Looks good, only one thing

2024-01-20 12:10 UTC, Thunderblade73 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/AuctionsHighlighter.kt
> +    private val endedPattern by RepoPattern.pattern("auctions.highlight.ended", "§7Status: §a(?:Sold|Ended)!")
add a repoGroup please

2024-02-16 10:36 UTC, hannibal002 requested changes
Please implement Thunderblade73's suggestion

2024-02-23 22:49 UTC, hannibal002 requested changes
Have not yet tested. code looks coorect. Just some code cleanup ideas

2024-02-23 22:49 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/AuctionsHighlighter.kt
> +                            group("player").removeColor().substringAfterLast(" ")
Use String.cleanPlayerName()

2024-02-23 22:49 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/AuctionsHighlighter.kt
>      fun onBackgroundDrawn(event: GuiContainerEvent.BackgroundDrawnEvent) {
Since the whole event logic is getting complicated, maybe only calculate colors and slot on inventory open, then cache it and use the cacke here

2024-12-20 02:43 UTC, CalMWolfs commented
Your pull request has been inactive for an extended period and appears to be either a draft or awaiting resolution of merge conflicts or requested changes. Therefore, I am closing it for now. Feel free to reopen it when it’s ready for review.

2024-12-20 02:43 UTC, closed without merging