Feature: Dragon Weight + Superior Notifier
hannibal00212/SkyHanni pull request #844
Opened 2023-12-27 18:19 UTC by Thunderblade73

Adds an Hud that calcualtes the current Dragon Weight.
Adds an chat message to the dragon death with the weight.
Adds an notifcation title when an Superior is spawned

2024-07-02 07:32 UTC, hannibal002 commented
old

2024-07-02 10:12 UTC, Thunderblade73 commented
Can this get a "Waiting for Hypixel". Since I'm still waiting for the primal dragon update. Since that breaks the whole logic here.

2024-07-03 10:06 UTC, Thunderblade73 commented
Nevermind the waiting for Hypixel. Since Hypixel confirmed yesterday that the shelved the primal dragon update.
![image](https://github.com/hannibal002/SkyHanni/assets/85900443/a25d0a73-20bf-4f53-9c71-755ae0e23954)

2025-03-16 15:03 UTC, hannibal002 requested changes
now sure what i did wrong but i could not get the display to show:

1. i placed 5 eyes
2. i enabled the weight hud
3. i placed 2 more eyes
4. drag spawned with 7 eyes from me and 1 eye from soomeeone else
5. no display visible anywhere before during or after the fight

2025-03-16 15:03 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/combat/DragonFeatures.kt
> +            if (!widgetActive) widgetErrorGUI else display(),
this will recreate the widget every frame

2025-03-16 15:03 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/combat/DragonFeatures.kt
> +        if (!(enableDisplay() && dragonSpawned)) return
please simplify this check

2025-03-16 16:52 UTC, Thunderblade73 commented
> now sure what i did wrong but i could not get the display to show:
> 
> 1. i placed 5 eyes
> 2. i enabled the weight hud
> 3. i placed 2 more eyes
> 4. drag spawned with 7 eyes from me and 1 eye from soomeeone else
> 5. no display visible anywhere before during or after the fight

Did testing right no and worked without me touching the code. Did you enable it inside the config? (As it is default off)

2025-03-16 17:00 UTC, hannibal002 commented
> Did testing right no and worked without me touching the code. Did you enable it inside the config? (As it is default off)

yes i did enable it, but not from the beginning. see step 2 above

2025-03-16 17:10 UTC, Thunderblade73 commented
> > Did testing right no and worked without me touching the code. Did you enable it inside the config? (As it is default off)
> 
> yes i did enable it, but not from the beginning. see step 2 above

Ok. Maybe you did not see it? As it is quiet small.
I can't test something that works on my side.

Since it should still work (you just miss 5 eyes since the didn't get counted)

2025-03-17 09:16 UTC, hannibal002 requested changes
I have updated the description. please confirm if they are still fine with you.

2025-03-17 09:24 UTC, Thunderblade73 commented
> I have updated the description. please confirm if they are still fine with you.

Is fine. Thanks for correcting it.

2025-03-17 09:59 UTC, merged