Feature: Fame Cost
hannibal00212/SkyHanni pull request #847
Opened 2023-12-27 23:27 UTC by walkerselby

A silly little feature, showing how much actual money your fame is worth. Wild.

2024-01-16 23:19 UTC, nea89o requested changes

2024-01-16 23:19 UTC, nea89o commented on src/main/java/at/hannibal2/skyhanni/config/features/misc/MiscConfig.java
> +    @ConfigOption(name = "Fame Cost", desc = "Show cost equivalent for your fame in the lore of your fame rank")
I feel like this should clarify using gems, some people might see this as "useful for knowing how many booster cookies to buy".

2024-01-16 23:19 UTC, nea89o commented on src/main/java/at/hannibal2/skyhanni/features/fame/FameCost.kt
> +        event.toolTip.add("§7Fame Cost: §a$${calculateDollarValue(fameAmount).round(2).addSeparators()}")
Maybe add this line below the actual fame cost, instead of all the way at the bottom.

2024-02-05 15:56 UTC, walkerselby commented
This PR is now stale. Will revisit and re-implement when I have time.

2024-02-05 15:56 UTC, closed without merging