Feature: Pet Exp Share Display
hannibal00212/SkyHanni pull request #850
Opened 2023-12-28 13:16 UTC by Thunderblade73

![image](https://github.com/hannibal002/SkyHanni/assets/85900443/c5841403-2d64-4007-b6ac-04d0a4bb6419)

2023-12-28 13:18 UTC, alexiayaa requested changes

2023-12-28 13:18 UTC, alexiayaa commented on src/main/java/at/hannibal2/skyhanni/features/misc/PetExpShareDisplay.kt
> +        val petCandyUsed = stack.getPetItem() ?: return
```suggestion
        val petItem = stack.getPetItem() ?: return
```

2023-12-28 13:18 UTC, alexiayaa commented on src/main/java/at/hannibal2/skyhanni/features/misc/PetExpShareDisplay.kt
> +        if (petCandyUsed != "PET_ITEM_EXP_SHARE") return
```suggestion
        if (petItem != "PET_ITEM_EXP_SHARE") return
```

2024-01-11 10:45 UTC, CalMWolfs approved these changes
Config option description is just missing a fullstop but the rest is looking good to me

2024-01-14 18:08 UTC, CalMWolfs approved these changes
worked

2024-01-16 18:01 UTC, hannibal002 approved these changes

2024-01-16 18:02 UTC, merged