[WIP] More Repo Patterns
hannibal00212/SkyHanni pull request #871
Opened 2024-01-01 23:29 UTC by CalMWolfs

start to migrate a lot of patterns over to the repo patterns
let me know if any key names have mistakes or dont make sense

currently not changing any patterns to make them more specific e.g. `.* -> //d+` for ints

2024-01-01 23:33 UTC, j10a1n15 commented on src/main/java/at/hannibal2/skyhanni/data/PurseAPI.kt
> +    private val coinsPattern by RepoPattern.pattern(
I'd respect it if you dont do purse pattern since my scoreboard pr needs it and uhh its very diff

2024-01-02 22:00 UTC, CalMWolfs commented
In later prs: 
moving more niche cases over to the repo
making patterns more precise
making more things into patterns instead of string comparisons

2024-01-13 03:08 UTC, CalMWolfs commented
This pr should hopefully now be done let me know if you see any issues with it. If there is a pattern in the code that isnt migrated yet its prob because its in a list or there is some other weird thing to do with it but do let me know and i can clarify for you
In future prs to skyhanni please use repo patterns and follow similar naming and formatting conventions to what i have done in this pr
Later additional prs will include edits to make patterns more exact, optimise when patterns are used and use repo pattern lists once nea's pr is merged

2024-02-16 08:28 UTC, hannibal002 requested changes
Looked thought all the changes, looks good overall.
Thanks for the many fixes.
I've marked you some cases where I'm not sure if this is ideal.

2024-02-16 08:28 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/combat/mobs/SpawnTimers.kt
> +        "^☄ [a-z0-9_]{2,22} placed an arachne crystal! something is awakening!\$"
`$` -> `\$` is this intended?

2024-02-16 08:28 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/misc/compacttablist/TabListReader.kt
> +    private val tabListSPattern by patternGroup.pattern(
typo? we should fix it as well

2024-02-16 08:28 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
> +        UtilsPatterns.amountFrontPattern.matchMatcher(input) {
The new name does not describe that this pattern is part of readItemAmount

2024-02-16 08:28 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt
> +        val matcher = UtilsPatterns.amountBehindPattern.matcher(string)
Same here

2024-02-16 10:21 UTC, hannibal002 approved these changes

2024-02-16 10:21 UTC, merged