Backend: Renderable progressBar
hannibal00212/SkyHanni pull request #887
Opened 2024-01-07 13:55 UTC by Thunderblade73

simply the progressBar we used in /ff extracted to a renderable

Depends on: #885

2024-01-16 22:54 UTC, nea89o requested changes

2024-01-16 22:54 UTC, nea89o commented on src/main/java/at/hannibal2/skyhanni/utils/NumberUtil.kt
> +    fun Number.percentOf(maxValue: Number) = maxValue.toDouble().takeIf { it != 0.0 }?.let { max ->
Misnomer: percentage is part out of a 100. Maybe `fractionOf` or `progressTowards`?

2024-01-16 22:54 UTC, nea89o commented on src/main/java/at/hannibal2/skyhanni/utils/ColorUtils.kt
> +    )
Not sure if RGB is the best color space for blending. It is probably fine, but i think the function name should indicate that the blending is done in RGB.

2024-02-19 12:41 UTC, hannibal002 approved these changes

2024-02-19 12:42 UTC, merged