Feature: SkyblockXPInChat
hannibal00212/SkyHanni pull request #919
Opened 2024-01-13 15:29 UTC by Thunderblade73

## Preview
![image](https://github.com/hannibal002/SkyHanni/assets/85900443/b42fcb5b-907d-456e-8adf-5c9baab0b2ae)
## Discord
https://discord.com/channels/997079228510117908/1188397928398716989

2024-01-13 17:27 UTC, CalMWolfs requested changes
feature worked and seems very cool, just these two small changes

2024-01-13 17:27 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/data/ActionBarStatsData.kt
> +    ;
can we get the enum names to be all capitals like the rest of the codebase and can you also add a trailing comma to the final one so we get cleaner changelogs in future if a new stat is added

2024-01-13 17:27 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/features/chat/ChatConfig.java
> +    @ConfigOption(name = "Skyblock XP Chat", desc = "Prints the Skyblock XP message into the chat")
punctuation

2024-01-13 17:38 UTC, CalMWolfs approved these changes
lgtm

2024-01-16 22:38 UTC, nea89o requested changes

2024-01-16 22:38 UTC, nea89o commented on src/main/java/at/hannibal2/skyhanni/data/ActionBarStatsData.kt
> +),
Formatting.

2024-01-16 22:38 UTC, nea89o commented on src/main/java/at/hannibal2/skyhanni/data/ActionBarStatsData.kt
> +                null
Not sure if this is more clear, but this is something you can do: 

```suggestion
                value.pattern.matchMatcher(event.message) {
                    val newValue = group(1)
                    if (value.value != newValue) {
                        value.value = newValue
                        ActionBarValueUpdate(value)
                    } else null
                }
```

2024-01-16 22:38 UTC, nea89o commented on src/main/java/at/hannibal2/skyhanni/data/ActionBarStatsData.kt
> +            entries.mapNotNull { value ->
Not the biggest fan of using `value` as a name here.

2024-01-17 21:08 UTC, nea89o approved these changes

2024-01-18 16:43 UTC, hannibal002 requested changes
Does work fine!
![image](https://github.com/hannibal002/SkyHanni/assets/24389977/7918cc44-000b-4888-94e3-66631e24d4e1)

2024-01-18 16:43 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/data/ActionBarStatsData.kt
> +    var value: String = ""
please add `private set`

2024-01-18 16:43 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/chat/ChatConfig.java
> +    @ConfigOption(name = "Skyblock XP Chat", desc = "Prints the Skyblock XP message into the chat.")
Please use the wording "send" over "print"

2024-01-20 09:05 UTC, hannibal002 approved these changes

2024-01-20 09:06 UTC, merged