Feature: Tier Boosted Pet Display
hannibal00212/SkyHanni pull request #920
Opened 2024-01-13 15:53 UTC by Thunderblade73

![image](https://github.com/hannibal002/SkyHanni/assets/85900443/76518e37-5a64-41a2-825f-b4f98dd22d08)

2024-01-13 16:13 UTC, CalMWolfs requested changes
Pr looks fine apart from those two things. Which prob also applies to the other pr of yours that is very similar but I won't rereview that. Though I do have a suggestion, instead of having two features like this with similar logic what if you made a drop-down list for the user to select which pet items they want to display a symbol for. This would make adding new ones much easier and stop some code duplication but this is up to you

2024-01-13 16:13 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/features/misc/pets/PetConfig.java
> +    @ConfigOption(name = "Show Tier Boost", desc = "Shows an §c● §7by a pet when an tier boost core is equipped")
Maybe it's just me but "an" sounds funny I think both could just be "a". Also missing the fullstop at the end of the description

2024-01-13 16:13 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/features/misc/pets/PetConfig.java
> +    @FeatureToggle
I don't feel this feature qualifies for this annotation but up to you

2024-01-14 13:28 UTC, Thunderblade73 commented
merged with #850

2024-01-14 13:28 UTC, closed without merging