Change: Pet item display scale
hannibal00212/SkyHanni pull request #939
Opened 2024-01-19 17:22 UTC by Thunderblade73

allows scaling of the pet item display

2024-01-19 22:16 UTC, CalMWolfs requested changes
2 small things

2024-01-19 22:16 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/features/misc/pets/PetConfig.java
> +    @ConfigOption(name = "Pet Item Scale", desc = "The scale at which the Pet Item will be displayed")
```suggestion
    @ConfigOption(name = "Pet Item Scale", desc = "The scale at which the Pet Item will be displayed.")
```

2024-01-19 22:16 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/misc/PetItemDisplay.kt
> +    private val scale get() = SkyHanniMod.feature.misc.pets.petItemDisplayScale
```suggestion
    private val config get() = SkyHanniMod.feature.misc.pets
```
to fit with the majority of the codebase then use config.whatever later on

2024-01-20 10:47 UTC, hannibal002 requested changes
See Cal's suggestion

2024-01-20 11:07 UTC, Thunderblade73 commented
Now fixed.

2024-01-20 11:24 UTC, hannibal002 approved these changes

2024-01-20 11:25 UTC, merged