Add /pd short command for party disband
hannibal00212/SkyHanni pull request #962
Opened 2024-01-29 20:36 UTC by ItsEmpa

2024-01-29 23:24 UTC, CalMWolfs requested changes
All looks good apart from this

2024-01-29 23:24 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/commands/PartyCommands.kt
> +        if (command == "pk" || command == "pt" || command == "pp" || command == "pd" && config.shortCommands) {
This line should not be changed as you don't tab complete player names for p disband

2024-01-29 23:30 UTC, CalMWolfs approved these changes
Lgtm

2024-01-30 21:14 UTC, hannibal002 approved these changes

2024-01-30 21:15 UTC, merged