Bug Fix: Fix pets menu detection for /ff
hannibal00212/SkyHanni pull request #970
Opened 2024-02-01 17:40 UTC by martimavocado

2024-02-02 11:43 UTC, CalMWolfs requested changes
idk if what i did works as i made the suggestions on github but it should be formatted like this

2024-02-02 11:43 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/CaptureFarmingGear.kt
> +    private val petsRegex by RepoPattern.pattern("garden.fortuneguide.petsmenu", "Pets(?: \\(\\d+/\\d+\\) )?")
```suggestion
    private val petMenuPattern by patternGroup.pattern(
    "petsmenu", 
    "Pets(?: \\(\\d+/\\d+\\) )?"
    )
```

2024-02-02 11:43 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/CaptureFarmingGear.kt
> +        if (petsRegex.matches(event.inventoryName)) pets(farmingItems, items, outdatedItems)
```suggestion        
        petMenuPattern.matchMatcher(event.inventoryName) {
            pets(farmingItems, items, outdatedItems)
            return
        }
```

2024-02-02 12:39 UTC, CalMWolfs requested changes

2024-02-02 12:39 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/CaptureFarmingGear.kt
> +    private val petMenuPattern by patternGroup.pattern("garden.fortuneguide.petsmenu", "Pets(?: \\(\\d+/\\d+\\) )?")
```suggestion
    private val petMenuPattern by patternGroup.pattern(
        "petsmenu", 
        "Pets(?: \\(\\d+/\\d+\\) )?"
    )
```
You still need to change the pattern key

2024-02-02 12:55 UTC, CalMWolfs approved these changes

2024-02-05 11:03 UTC, hannibal002 approved these changes

2024-02-05 11:04 UTC, merged