Internal Change: Lorenz Utils cleanup (LanguageUtils/ChatUtils)
hannibal00212/SkyHanni pull request #978
Opened 2024-02-03 23:11 UTC by Thunderblade73

## Why
Because it bothered me that LorenzUtils has so much stuff in it. Additionally a lot of function the could be group better under it's own util.
## What
changed addOrPut (uses merge now)
### moved some stuff
| Function                   | Move to Utility            |
| -------------------------- | ------------------ |
| ticks                      | TimeUtils          |
| toChromaColor              | ColorUtils         |
| debug                      | ChatUtils          |
| userError                  | ChatUtils          |
| error                      | ChatUtils          |
| chat                       | ChatUtils          |
| internalChat               | ChatUtils          |
| clickableChat              | ChatUtils          |
| hoverableChat              | ChatUtils          |
| sendQueuedChatMessages     | ChatUtils          |
| sendMessageToServer        | ChatUtils          |
| drainTo                    | LanguageUtils      |
| weakReferenceList          | LanguageUtils      |
| filterToMutable            | LanguageUtils      |
| transformIf                | LanguageUtils      |
| conditionalTransform       | LanguageUtils      |
| indexOfFirst               | LanguageUtils      |
| dynamic                    | LanguageUtils      |
| getPropertiesWithType      | LanguageUtils      |
| makeAccessible             | LanguageUtils      |
| removeFinal                | LanguageUtils      |
| put                        | LanguageUtils      |
| equalsOneOf                | LanguageUtils      |
| getOrNull                  | LanguageUtils      |
| toSingeltonListOrEmpty     | LanguageUtils      |
| addOrPut                   | LanguageUtils      |
| sumAllValues               | LanguageUtils      |
| nextAfter                  | LanguageUtils      |
| onChange                   | LanguageUtils      |
| onToggle                   | LanguageUtils      |
| afterChange                | LanguageUtils      |
| editCopy                   | LanguageUtils      |
| moveEntryToTop             | LanguageUtils      |
| addAsSingeltionList        | LanguageUtils      |
| sorted                     | LanguageUtils      |
| sotedDesc                  | LanguageUtils      |

2024-02-03 23:18 UTC, CalMWolfs commented
Only 519 files changed 😂

2024-02-05 19:53 UTC, hannibal002 requested changes
Please don't delete the functions around chat in LorenzUtils. Make them deprecated insteand and let them clall the new functions in the ChatUtils class.
This shuld greatly reduce the amount of merge conflitcs for the next weeks.
After many/most prs are updated to using ChatUtils over LorenzUtils, we can remove the deprecated functions.

2024-02-09 19:14 UTC, hannibal002 requested changes
Waitinf for ReflectionUtil

2024-02-09 23:23 UTC, hannibal002 approved these changes

2024-02-09 23:24 UTC, merged