Fix: BingoCardTips IndexOutOfBoundsException
hannibal00212/SkyHanni pull request #983
Opened 2024-02-05 17:52 UTC by Thunderblade73

## Discord
https://discord.com/channels/997079228510117908/1193356023432495134

2024-02-05 21:53 UTC, CalMWolfs requested changes
just this one thing to match the style of https://github.com/hannibal002/SkyHanni/pull/871 better and also improves readability of the patterns

2024-02-05 21:53 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/bingo/card/BingoCardTips.kt
> +    private val contributionRewardsPattern by repoGroup.pattern("reward.contribution", "§.§.§7Contribution Rewards.*")
```suggestion
    private val config get() = SkyHanniMod.feature.event.bingo.bingoCard

    private val patternGroup = RepoPattern.group("bingo.card.tips")
    private val inventoryPattern by patternGroup.pattern(
        "card", 
        "Bingo Card"
    )
    private val rewardPattern by patternGroup.pattern(
        "reward", 
        "§.§.§7Reward"
    )
    private val contributionRewardsPattern by patternGroup.pattern(
        "reward.contribution", 
        "§.§.§7Contribution Rewards.*"
    )
```

2024-02-28 19:13 UTC, hannibal002 approved these changes
works fine any way

2024-02-28 19:13 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/bingo/card/BingoCardTips.kt
> +        "§.§.§7Reward"
Technically this string always has to start with `§5§o` as this is a minecraft limitation, not controlled by hypixel.

2024-02-28 19:13 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/bingo/card/BingoCardTips.kt
> +        "card",
rename to "card title" or something

2024-02-28 19:16 UTC, merged

2024-02-28 19:16 UTC, hannibal002 commented
Dont ask please