Change: Option to only show Ender Node tracker while holding a pickaxe
hannibal00212/SkyHanni pull request #984
Opened 2024-02-06 11:22 UTC by Thunderblade73

## Discord
https://discord.com/channels/997079228510117908/1197526187157758033

2024-02-16 22:07 UTC, CalMWolfs requested changes
Just need to change this feature name to be a bit more descriptive

2024-02-16 22:07 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/features/combat/EnderNodeConfig.java
> +        name = "Only Holding Tool",
Maybe this could be only while holding tool

2024-02-19 10:55 UTC, CalMWolfs requested changes
also pushed one punctuation change (before i saw the other thing needed changing)

2024-02-19 10:55 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/combat/endernodetracker/EnderNodeTracker.kt
> +        LorenzUtils.inSkyBlock && IslandType.THE_END.isInIsland() && config.enabled &&
.isInIsland already checks for being in skyblock

2024-02-19 14:07 UTC, hannibal002 requested changes
It is working fine. Only small cleanup ideas.

2024-02-19 14:07 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/combat/EnderNodeConfig.java
> +        desc = "Only shows the tracker if holding a pickaxe, drill or gauntlet."
Maybe add "in hand" at the end

2024-02-19 14:07 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/combat/endernodetracker/EnderNodeTracker.kt
> +            (!config.onlyPickaxe || ItemCategory.miningTools.containsItem(InventoryUtils.getItemInHand()))
Maybe extract into function "hasItemInHand()" for readability

2024-02-19 14:07 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/ItemCategory.kt
> +        val miningTools = listOf(ItemCategory.PICKAXE, ItemCategory.DRILL, ItemCategory.GAUNTLET)
Remove redundant qualifier name

2024-02-19 23:11 UTC, CalMWolfs approved these changes
lgtm

2024-02-20 17:31 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/combat/endernodetracker/EnderNodeTracker.kt
> +            (!config.onlyPickaxe || ItemCategory.miningTools.containsItem(InventoryUtils.getItemInHand()))
I was thinking of this, but It's fine.
![image](https://github.com/hannibal002/SkyHanni/assets/24389977/c8802150-0bd2-4f25-b610-8133c69ab91b)

2024-02-20 17:31 UTC, hannibal002 approved these changes

2024-02-20 17:32 UTC, merged