Fix: Add support for Roman Numerals to unique visitors grabber
hannibal00212/SkyHanni pull request #988
Opened 2024-02-09 01:20 UTC by martimavocado

also added .isRoman() to stringutils

2024-02-09 16:58 UTC, hannibal002 commented
Maybe use `String.romanToDecimalIfNecessary()` instead?

2024-02-09 17:16 UTC, hannibal002 requested changes
see dms

2024-02-09 18:22 UTC, alexiayaa requested changes

2024-02-09 18:22 UTC, alexiayaa commented on src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/CaptureFarmingGear.kt
> +        "§7Progress to Tier (?<nextTier>\\d+|I{1,3}|IV|V|VI{1,3}|IX|X):.*"
```suggestion
        "§7Progress to Tier (?<nextTier>\\w+:.*"
```

2024-02-09 18:29 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/CaptureFarmingGear.kt
> +        "§7Progress to Tier (?<nextTier>\\d+|I{1,3}|IV|V|VI{1,3}|IX|X):.*"
this

2024-02-09 19:52 UTC, hannibal002 requested changes
The pattern does not detect for me.

Trying to debug `tierPattern` at CaptureFarmingGear line 151 gives me this:
Method threw 'java.lang.NoSuchFieldException' exception.

2024-02-09 21:57 UTC, martimavocado commented
> The pattern does not detect for me.

try enabling "force local loading" in repopattern settings

2024-02-09 22:26 UTC, hannibal002 requested changes
one small but important thing

2024-02-09 22:26 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/garden/fortuneguide/CaptureFarmingGear.kt
> +                    tier = group("nextTier").romanToDecimalIfNecessary()
Add the removed -1 back again. (tier = nextTier - 1)

2024-02-10 00:17 UTC, hannibal002 approved these changes

2024-02-10 00:17 UTC, merged